### ISSUE TITLE
typo in kindlekey.py breaks key retrieval in Kindle for Mac

### ISSUE THREAD

**Issue by mizuOda** [noDRM/DeDRM_tools#1]
@Daniele has caught typo in kindlekey.py that breaks key retrieval, causing decryption on new installations of Kindle for Mac using DeDRM 7.2.1 to fail. Same is happening with v10.0.1. 

Please see [Pull request #1936 in Apprentice Harper's repo](https://github.com/apprenticeharper/DeDRM_tools/pull/1936)

In a nutshell: v10.0.1 kindlekey.py line 1529 should be `b'DSN',\` rather than `b'DSN'`

I tested this on my Mac and correction fixes problem. Thank you for considering this revision.

**Comment by noDRM** [comment]
Thanks for letting me know, I've merged that PR into my repo.

**Comment by mizuOda** [comment]
Thank you!

**Comment by noDRM** [comment]
This fix is now included in v10.0.2.

**Comment by mizuOda** [comment]
Thank you! I have updated the [Mac post ](https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508)on MobileRead.
