### ISSUE TITLE
6.1 + 10.0.3 blacklisting dedrm

### ISSUE THREAD

**Issue by kzssc** [noDRM/DeDRM_tools#102]
### Question / bug report

Not entirely sure what I've missed.. DeDRM seems to be blacklisted by Calibre due to it being too old? (Attaching log below.) Grateful for any input - many thanks! 

### Which version of Calibre are you running?

6.1

### Which version of the DeDRM plugin are you running?

10.0.3 and 10.0.2

### Log output

calibre, version 6.1.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:Blacklisting the DeDRM version (10, 0, 2) plugin as it is too old and causes crashes. Update it to the latest version to use it.

calibre 6.1  embedded-python: True
macOS-12.4-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '21.5.0', 'Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101')
Python 3.10.1
OSX: ('12.4', ('', '', ''), 'arm64')
Interface language: en_GB
Successfully initialized third party plugins: DeACSM (0, 0, 15)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 483, in add_plugin
  File "calibre/customize/ui.py", line 671, in initialize_plugin
calibre.customize.InvalidPlugin: Blacklisting the DeDRM version (10, 0, 2) plugin as it is too old and causes crashes. Update it to the latest version to use it.

**Comment by ElleKayEm** [comment]
Make sure you install 10.0.3 and you will be fine.  It is only 10.0.2 and older that is blacklisted in calibre 6.1.

**Comment by kzssc** [comment]
> Make sure you install 10.0.3 and you will be fine. It is only 10.0.2 and older that is blacklisted in calibre 6.1.

Thanks! I can confirm that i've downloaded 10.0.3 (numerous times, in fact) but it still doesn't seem to work :(

**Comment by ElleKayEm** [comment]
Make sure that's the one you're actually trying to load.  It's really easy to mistakenly grab an older version if it's still there.

**Comment by noDRM** [comment]
Try completely deinstalling the plugin, then restart Calibre, then re-install 10.0.3.

**Comment by kzssc** [comment]
> Try completely deinstalling the plugin, then restart Calibre, then re-install 10.0.3.

many thanks! it works now - need to manually delete the older version of plugins in ~/Library/Preferences/calibre/plugins.
