### ISSUE TITLE
Calibre 6.2.1 on Mac won't upload 10.0.3 "DeDRM_plugin.zip" as instructed in ReadMe.txt.  

### ISSUE THREAD

**Issue by Tangleten** [noDRM/DeDRM_tools#117]
Would appreciate some guidance on this.  I used "Load Plugin from file" on calibre Plugins page but the zip file wasn't then available. The only file available was "alfcrypto_src.zip" which doesn't work.

**Comment by ElleKayEm** [comment]
Download DeDRM_tools_10.0.3.zip from here: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Unzip it and load DeDRM_plugin.zip.

**Comment by Tangleten** [comment]
Thank you.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
