### ISSUE TITLE
Unable to de-drm .azw3 book

### ISSUE THREAD

**Issue by riverLethe9** [noDRM/DeDRM_tools#12]
I have the latest tools properly installed in Calibre. This is not a KFX book and I have previously converted azw3 books without error. But this one seems to be different. I will attach the log file from Calibre's debug mode.
[tmpdfxdxjir.txt](https://github.com/noDRM/DeDRM_tools/files/7790013/tmpdfxdxjir.txt)

**Comment by ElleKayEm** [comment]
Don't forget to add your Kindle's serial number to DeDRM's customization.  Also, you're still using Apprentice Harper's DeDRM 7.2.1 in this log.  Latest noDRM version is 10.0.2.

**Comment by MischievousSilverfish** [comment]
Hello. I've had the same issue as OP. Adding serial number (tried with no spaces) solved the issue for me. It would be amazing if you could add instructions for that in the README or somewhere in the plugin itself so that people are aware that you have to do that.

**Comment by ElleKayEm** [comment]
It's in the DeDRM_plugin_ReadMe.txt.

**Comment by riverLethe9** [comment]
Thank you for the quick replies. I updated the DeDRM_tools and added my serial number with no spaces. Unfortunately, it did not work. Here is an updated log file.
[tmpzk23bvfs.txt](https://github.com/noDRM/DeDRM_tools/files/7793831/tmpzk23bvfs.txt)

**Comment by j-howell** [comment]
Your log shows a filename of

> The Skills Training Manual for Radically Open Dialectical Behavior Therapy A Clinicians Guide for Treating Disorders of Overcontrol by Thomas R. Lynch [Lynch, Thomas R.] (z-lib.org).azw3

If you downloaded it from z-lib then (1) it is likely pirated and (2) it has DRM you won't be able to remove because the do not know the Kindle serial number of the original owner of that file.
