### ISSUE TITLE
Cannot remove DRM from recently downloaded Kindle books

### ISSUE THREAD

**Issue by DaveHarrington** [noDRM/DeDRM_tools#125]
### Question / bug report

Hi - I have a docker image where I install Calibre and NoDRM to remove DRM from my kindle azw3s. Just recently (the last couple of weeks), books I download from Amazon will not convert (error below). I've tested with the same ebook downloaded a few weeks ago vs today and it's just started failing, so I'm confident it's due to a recent change in the azw3 format. Also having it in Docker makes it pretty trivial to reproduce.

Calibre Version: 6.3.0
NoDRM Version: 10.0.3

Let me know if there's any extra logs I can grab or whatever.

### Which version of Calibre are you running?

6.3.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
1% Converting input to HTML...
InputFormatPlugin: MOBI Input running
on /function/test.azw3
Found KF8 MOBI of type 'standalone'
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/ebooks/conversion/cli.py", line 419, in main
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 242, in __call__
  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
  File "calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
calibre.ebooks.DRMError: Positioning: The Battle for Your Mind
```

**Comment by ElleKayEm** [comment]
This log doesn't show what's going on with DeDRM.  Let's see an import log: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by DaveHarrington** [comment]
Do you know how to create the import log if I'm using `ebook-convert`?

**Comment by ElleKayEm** [comment]
No idea.  But what I'm looking for is the debug log from when you first add a problem book to calibre.  Does that help?

**Comment by agentxan** [comment]
I just tried on windows 10 using calibre 6.3 and if I remove the dedrm plugin I get the same error 

C:\Calibre6Portable\Calibre Portable\Calibre>ebook-convert.exe ../B084DTX7RZ_EBOK.azw converted.epub
1% Converting input to HTML...
InputFormatPlugin: MOBI Input running
on C:\Calibre6Portable\Calibre Portable\B084DTX7RZ_EBOK.azw
Found KF8 MOBI of type 'standalone'
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\ebooks\conversion\cli.py", line 419, in main
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
  File "calibre\ebooks\mobi\reader\mobi8.py", line 85, in __call__
  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm
calibre.ebooks.DRMError: A Hint of Hope: A Towers of the Earth novella

but if I install the dedrm plugin and rerun the command I get 

C:\Calibre6Portable\Calibre Portable\Calibre>ebook-convert.exe ../B084DTX7RZ_EBOK.azw converted.epub
DeDRM(88b0966) v10.0.3: Trying to decrypt B084DTX7RZ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Hint of Hope: A Towers of the Earth novella
Got DSN key from database kindle_key_1660694324_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID +woO2cUvS2.
Decrypting. Please wait . . . done
Decryption succeeded after 0.1 seconds
DeDRM(88b0966) v10.0.3: Finished after 0.1 seconds
DeDRM(88b0966) v10.0.3: Trying to decrypt 6kgpsvg7.azw3
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Hint of Hope: A Towers of the Earth novella
Got DSN key from database kindle_key_1660694324_1
Found 4 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM(88b0966) v10.0.3: Finished after 0.0 seconds
DeDRM(88b0966) v10.0.3: Trying to decrypt c_h39_g9.azw3
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Hint of Hope: A Towers of the Earth novella
Got DSN key from database kindle_key_1660694324_1
Found 4 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM(88b0966) v10.0.3: Finished after 0.0 seconds
DeDRM(88b0966) v10.0.3: Trying to decrypt kaxpwbt4.azw3
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Hint of Hope: A Towers of the Earth novella
Got DSN key from database kindle_key_1660694324_1
Found 4 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM(88b0966) v10.0.3: Finished after 0.0 seconds
1% Converting input to HTML...
InputFormatPlugin: MOBI Input running
on C:\Users\jbean\AppData\Local\Temp\calibre_10xf6f7j\b9z4pkhz.azw3
Found KF8 MOBI of type 'standalone'
Parsing all content...
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Trimming 'images/00004.jpeg' from manifest
Trimming 'images/00006.jpeg' from manifest
Creating EPUB Output...
67% Running EPUB Output plugin
Rescaling image from 827x1323 to 741x1186 images/00003.jpeg
Splitting markup on page breaks and flow limits, if any...
        Looking for large trees in text/part0004.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0002.html...
        No large trees found
        Looking for large trees in text/part0017.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0003.html...
        No large trees found
        Looking for large trees in text/part0016.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0024.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0027.html...
        No large trees found
        Looking for large trees in text/part0009.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0011.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0018.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0023.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0010.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0021.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0007.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0012.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0015.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0019.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0020.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0022.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0000.html...
        No large trees found
        Split into 3 parts
        Looking for large trees in text/part0001.html...
        No large trees found
        Looking for large trees in text/part0008.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0014.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0025.html...
        No large trees found
        Looking for large trees in text/part0026.html...
        No large trees found
        Looking for large trees in text/part0005.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0006.html...
        No large trees found
        Split into 2 parts
        Looking for large trees in text/part0013.html...
        No large trees found
        Split into 2 parts
The cover image has an id != "cover". Renaming to work around bug in Nook Color
EPUB output written to C:\Calibre6Portable\Calibre Portable\Calibre\converted.epub
Output saved to   C:\Calibre6Portable\Calibre Portable\Calibre\converted.epub

**Comment by ElleKayEm** [comment]
Yes, DeDRM should kick in both when you first add the book and when you try to convert.  The log I'm asking for should show what's going on here.

**Comment by DaveHarrington** [comment]
Hi @ElleKayEm - turned out to be my error - some sort of Lambda permissions thing. Though I have no idea why it was working before? Thanks for your time and efforts, this is great!

**Comment by ElleKayEm** [comment]
Lambda permissions?  Never heard of that.

**Comment by DaveHarrington** [comment]
@ElleKayEm - I'm running this in a docker container on AWS Lambda - https://aws.amazon.com/lambda/
