### ISSUE TITLE
A Python error showed up when DeDRM_tools 10.0.3 installed to Calibre 6.3.0

### ISSUE THREAD

**Issue by iammrallblue** [noDRM/DeDRM_tools#127]
calibre 6.3  embedded-python: True
macOS-12.5-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 64, 0) && KFX Output (1, 64, 0) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 479, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 300, in load
  File "calibre/customize/zipplugin.py", line 395, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/hank/Downloads/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by Piseed** [comment]
Open file explorer, go to /Users/hank/Downloads/DeDRM_tools_10.0.3/DeDRM_tools_10.0.3, select all the files there, zip'em and move this zip to Downloads, for example. When installing the plugin, use this zip instead of the original.

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip.

**Comment by ElleKayEm** [comment]
@Piseed Make sure your browser doesn't automatically unzip everything and you won't need to do that.

**Comment by OnlyIronically** [comment]
> Open file explorer, go to /Users/hank/Downloads/DeDRM_tools_10.0.3/DeDRM_tools_10.0.3/_plugin folder_, select all the files there, zip'em and move this zip to Downloads, for example. When installing the plugin, use this zip instead of the original.

That doesn't work, it's mentioned in the comments within __init__.py that compressing the file yourself from the source code won't work you will get the following error: ModuleNotFoundError: No module named '__version' 

It's recommended to use make_release.py to generate the zip file but I haven't been able to get that to work.

**Comment by ElleKayEm** [comment]
The OP here just hadn't unzipped DeDRM_tools_10.0.3.zip.  Once that and only that is unzipped, you load DeDRM_plugin.zip.

**Comment by noDRM** [comment]
Closing this issue as there's no response and it was most likely user error.
