### ISSUE TITLE
Remove DRM failed but no error message

### ISSUE THREAD

**Issue by xinluh** [noDRM/DeDRM_tools#130]
### Question / bug report

I have a file that looks to be DRM'ed with ADE, but importing into Calibre didn't remove the DRM. There is no error in the log. Any pointer to how to further debug this?

Tried the key imported from DeASCM as well as ADE 4.5. Curiously the file also fails to load on ADE with a generic error message `Errors were encountered in this item`, but the archive doesn't seem to be corrupted and can be unzipped.

### Which version of Calibre are you running?

6.3

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
DeDRM v10.0.3: Trying to decrypt <filename>.epub
DeDRM v10.0.3: Verifying zip archive integrity
FontDecrypt: Checking OPS/package.opf for IETF font obfuscation keys ... found 'URN:ISBN:... (p...)
FontDecrypt: Checking OPS/package.opf for Adobe font obfuscation keys ... not found
FontDecrypt: There's remaining entries in encryption.xml, adding file ...
DeDRM v10.0.3: Post-processing took 0.1 seconds
DeDRM v10.0.3: Finished after 0.1 seconds
Added <filename> to db in: 0.0
Added 1 books in 0.5 seconds```

**Comment by ElleKayEm** [comment]
If it won't even open in ADE, that's no good.  Seems like there is a problem with the book itself.

**Comment by noDRM** [comment]
What do you mean with "looks to be"? Do you know that this is supposed to work with ADE? The log message "There's remaining entries in encryption.xml" strongly hints to some other, non-Adobe DRM.

**Comment by xinluh** [comment]
I think the file may be partially corrupted somehow (the server for retrieving the epub was downloading at 2kb/s and keep getting timed out). Tried to retrieve the epub again today and now I'm getting a different error like https://github.com/noDRM/DeDRM_tools/issues/109. Going to close this issue and continue the conversation there.

> What do you mean with "looks to be"? Do you know that this is supposed to work with ADE? The log message "There's remaining entries in encryption.xml" strongly hints to some other, non-Adobe DRM.

The ebook vendor claims that the book is to be read with ADE, and unzipping the file and looking at encryption.xml also shows ADE.
