### ISSUE TITLE
Suggestion: Update README.md comments re Apprentice Harper

### ISSUE THREAD

**Issue by manngo** [noDRM/DeDRM_tools#136]
### Question / bug report

Currently, the README implies that this fork is out of sync with the original.

However Apprentice Harper has indicated that the project is no longer maintained, and noDRM’s version will be used.

Perhaps you could add that this is the spiritual inheritor of the project, and remove the comments about conflicting versions?

### Which version of Calibre are you running?

Not Relevant

### Which version of the DeDRM plugin are you running?

Not Relevant

**Comment by noDRM** [comment]
That seems like a good idea to remove confusion, I'm going to do that.
