### ISSUE TITLE
Removing DRM from my e-Ink Kindle fails, even though the serial number is correct

### ISSUE THREAD

**Issue by Southpaw1496** [noDRM/DeDRM_tools#138]
### Question / bug report

I've been trying to use the tools to strip DRM when importing from my e-Ink Kindle, however, the imported books still appear to be locked with DRM. I have read the FAQ, and I know my Kindle serial number is correct, as I copied it directly from Amazon's website (from Manage Your Content and Devices).

I followed the instructions that I found to the best of my ability, here are the exact steps I took:

- Installed DeDRM (10.0.3) and KFX Input (1.49.0)
- Copied my serial number from amazon.co.uk and added it to the "Kindle eInk ebooks" configuration
- Added `kfx_input_set_format_virtual = False` to Plug-in Tweaks
- Restarted Calibre
- Restarted Calibre again in debug mode
- Mounted Kindle
- Clicked "Device"
- Selected the books I wanted
- Right-clicked -> "Add Books to Library"
- Clicked "Library" to return to my library.

However, the books in my library were KFX ZIP files, and after I closed Calibre, the debug log was littered with the following error:
```
DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
```

As far as I know, I have correctly followed the instructions that came with the tools, so any help or advice would be greatly appreciated.

### Which version of Calibre are you running?

6.4.0

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

Kindle Firmware 5.4.32

### Log output

The log is too big to fit in GitHub, so I uploaded it [here](https://files.southpaw1496.me/calibre-log-01.txt)

**Comment by ElleKayEm** [comment]
You cannot decrypt KFX format directly from a Kindle.  You will need to get the older format from the website for "download & transfer via USB" and select your Kindle for the device.

**Comment by Southpaw1496** [comment]
I have 250 books, do I have to do them each one by one?

**Comment by ElleKayEm** [comment]
Other alternative is Kindle for PC/Mac.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Southpaw1496** [comment]
I can't figure out how to access the books once I've downloaded them. I'm using Kindle for Mac, and while some guides reference the "My Kindle Content" folder in the Documents folder, but I can't seem to find it.

**Comment by ElleKayEm** [comment]
That's where it is on PCs.  Not sure on Macs.  But look in the app under Tools > Options > Content and it will show where they're stored.  (And you can change it if you want.)

**Comment by ZolaLa9** [comment]
In Kindle for Mac, the default location is usually User > Library > Application Support > Kindle > My Kindle Content. Sometimes it's in User > Library> Containers. 

Make sure you're using Kindle for Mac 1.31 or earlier and following these additional instructions specific to Kindle for Mac: https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508
