### ISSUE TITLE
DeDRM_tools-master extracted files don't contain zip

### ISSUE THREAD

**Issue by OnlyIronically** [noDRM/DeDRM_tools#139]
### Question / bug report

Hello,
 I am running into issues installing the plugins from the master zip file. I downloaded the most recent archive and extracted the files using windows' built-in zip/unzip program. However, when I open up the extracted file all the plugins are unzipped so I am unable to install them into calibre.

i.e DeDRM_tools-master.zip ->(unzip)->DeDRM_tools-master ->DeDRM_tools-master->DeDRM_plugin (unzipped)

I have tried zipping the plugins after extracting the files but I run into issues with the new zip file containing a folder of the original.

ex:  (unzip)->DeDRM_tools-master ->DeDRM_tools-master->DeDRM_plugin ->(zip)->DeDRM_plugin.zip

So I run into the "no __init__.py file found" issue when trying to install it into calibre as all the code is contained inside the unzipped file inside the zipped file. 

Has anyone run into this issue before? 
[DeDRM_plugin.zip](https://github.com/noDRM/DeDRM_tools/files/9480580/DeDRM_plugin.zip)

### Which version of Calibre are you running?

6.3

### Which version of the DeDRM plugin are you running?

v10.0.3

**Comment by ElleKayEm** [comment]
On the [release page](https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3), download DeDRM_tools_10.0.3.zip (the top link under Assets).  Unzip that and load DeDRM_plugin.zip into calibre.

**Comment by OnlyIronically** [comment]
Oh I see, my bad I was pulling from the wrong place. Than you.
