### ISSUE TITLE
DRM'd kepub identified as DRM-Free by Obok

### ISSUE THREAD

**Issue by rainrdx** [noDRM/DeDRM_tools#146]
### Question / bug report

First of all thank you for the work. Recently I found there might be some books which are DRM'd but treated as DRM-free by the Obok plug-in.

One such example (a free book) is here: https://books.rakuten.co.jp/rk/7850a94b809d38fab33c8bb7ff7aa9b1/?lid=kobo_pc_mylibrary_prv_book_title

Would love to seek input. Thanks!

### Which version of Calibre are you running?

6.4

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
I've occasionally seen this happen, but in my case restarting calibre and/or the Kobo app has resolved it.  Are you seeing this with the Kobo Desktop app or a Kobo ereader or both?  Not sure if there's some order of opening the Kobo app (or attaching a Kobo ereader), downloading the book, and opening calibre/Obok that consistently prevents or causes the issue.  (I usually download the Adobe DRM version and use DeDRM instead.)

**Comment by rainrdx** [comment]
@ElleKayEm Thank you! Restarting kobo fixed it. Rather weird..
