### ISSUE TITLE
Obok does not allow to import book with the same title (duplicate) as new book

### ISSUE THREAD

**Issue by AzaleeBleue** [noDRM/DeDRM_tools#148]
- Calibre 6.4
- Obok 10.0.3
- Windows 10

Obok is correctly detecting books downloaded by the kobo app and removing the drm.
Once the books are cleaned, Obok is checking if a book with the same title already exists in the library and if found will not allow to import as a new book.
![2022 09 10 211827 - calibre](https://user-images.githubusercontent.com/73590822/189499416-0296cf00-a249-408d-ae02-0529cf3139f5.png)

If there is a settings to disable that behavior, my bad, I've missed it.

Why it's a problem for me:
- I have books from different authors with the same title in my library.
- I have the same book in different langages but with the same title.
- I have the same books, in the same langage, but in different versions or sources.

Just a setting to disable that check and let me do what I want will duplicate would be enough.

Thanks for that very useful tool that allow to possess a bought  ebook like a physical book.

**Comment by ElleKayEm** [comment]
I agree this would be nice.  As a workaround, I change the title of the book already in calibre slightly -- at least temporarily.

**Comment by AzaleeBleue** [comment]
> I agree this would be nice. As a workaround, I change the title of the book already in calibre slightly -- at least temporarily.

The temporary rename is a good idea, thanks.

**Comment by ElleKayEm** [comment]
@noDRM This works for me -- thank you!

**Comment by AzaleeBleue** [comment]
@noDRM same here. When set, it add the potential duplicate as a new book.
Thanks a lot.

**Comment by noDRM** [comment]
Great, thanks for reporting back.
