### ISSUE TITLE
Kindle for Mac version support

### ISSUE THREAD

**Issue by mpluto11** [noDRM/DeDRM_tools#159]
### Question / bug report

Hi, I am just curious if this will work with the latest version of kindle for Mac (v1.37)? I've been parked at 1.26 as it was the oldest version I was able to get running on my machine. I've never updated it (despite how buggy it kinda gets, but since I only use it to download and then import my books into calibre, It's never been too much of an issue), as I have not really wanted to deal with all of the steps involved in making the version I currently have work all over again. 

If not with v1.37 for kindle for Mac, do we have a confirmed version range that this does work with?

ps, thanks for taking up the mantle, for a while I had to resort to somewhat convoluted process of downloading books on my work (windows pc) laptop [which I was able to get kindle for pc 1.19 on], importing them into calibre, and then transferring it over to my own personal laptop..... just being able to not need my work computer anymore is quite lovely.... 

### Which version of Calibre are you running?

6.5

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

1.26.1

### Log output

```log
Paste log output here.
```

**Comment by ZolaLa9** [comment]
Kindle for Mac works through 1.31. It will not work with 1.37. 
More info here: https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by noDRM** [comment]
I don't think we'll ever get support for the newer versions of Kindle4PC or Kindle4Mac. Closing the issue as "not planned" - unless someone else looks into that and makes a PR for newer versions that's not going to happen.
