### ISSUE TITLE
DeDRM Calebre Loading Error

### ISSUE THREAD

**Issue by pliedl** [noDRM/DeDRM_tools#167]
When trying to enable the DeDRM Plugin, I get the following error.  Anyone else having this difficultiy?

![DeDRM Error](https://user-images.githubusercontent.com/25092158/192107577-5d7fedd4-72f7-4b62-bbaf-23b04eee9539.jpg)

**Comment by ElleKayEm** [comment]
Looks like you're trying to load an older version.  Make sure you are loading DeDRM 10.0.3.

**Comment by pliedl** [comment]
That was the problem. Thanks!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
