### ISSUE TITLE
Can't Install on Calibre 5.34 (Linux) -- "It does not contain a top-level __init__.py file"

### ISSUE THREAD

**Issue by ChthonVII** [noDRM/DeDRM_tools#19]
I attempt to install the 10.0.2 zip via Calibre's "preferences -> plugins -> load plugin from file" menu, and Calibre spits out:

> The plugin in '/{path_omitted}/DeDRM_tools_10.0.2.zip' is invalid. It does not contain a top-level __init__.py file

Calibre is v5.34 on Linux.

Any insights?

**Comment by ChthonVII** [comment]
Figured it out: I compared the zip against an officially-sanctioned plugin (ACE) and noticed that deDRM's zip is deflate compressed, while the other has no compression. I extracted deDRM's zip and rebuilt it with no compression, and -- boom! -- it now installs happily.

I don't know whether Calibre is _supposed_ to handle deflate-compressed zip files. If it is, it's Calibre's bug, and I should go file a bug report on them. If it's not, then deDRM's release artifacts should be rebuilt with no compression.

**Comment by noDRM** [comment]
I have never heard of anyone having any deflate-related problems with this plugin. 

Looking at your error message, you tried to import the "DeDRM_tools_10.0.2.zip" file, and you received a proper error message: `Does not contain __init__.py file`. 

The actual plugin ZIP is included within that ZIP, it needs to be extracted first.

**Comment by ChthonVII** [comment]
Hahaha! Indeed, that must be it. Aren't I a fool? Closing the issue now.
