### ISSUE TITLE
Error updating DeDRM - must use Calibre version >=5.0.0

### ISSUE THREAD

**Issue by singleeyephotos** [noDRM/DeDRM_tools#190]
### Question / bug report

I'm using Calibre version 4.23 on a PC, and when I try to update the DeDRM plugin to v. 10, I get an error stating that it only works with Calibre version 5.0 or earlier.  Since I AM using an earlier version, why is this occurring?

### Which version of Calibre are you running?

4.23

### Which version of the DeDRM plugin are you running?

v10.0

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Double-check which version you are trying to install.  The 10.x versions are intended to be compatible with calibre 6, 5, and 4.  Apprentice Harper's DeDRM 7 was compatible with calibre 5.  And DeDRM 6 worked with calibre 4.  Might as well try the current DeDRM 10.0.3.

**Comment by singleeyephotos** [comment]
> Double-check which version you are trying to install. The 10.x versions are intended to be compatible with calibre 6, 5, and 4. Apprentice Harper's DeDRM 7 was compatible with calibre 5. And DeDRM 6 worked with calibre 4. Might as well try the current DeDRM 10.0.3.

Thank you - that worked to get it installed.
