### ISSUE TITLE
No keys are imported on Mac

### ISSUE THREAD

**Issue by JavierRSobrino** [noDRM/DeDRM_tools#192]
### Question / bug report

No keys are imported on Mac after installation of the plugin, therefore I cannot convert any downloaded kindle ebook from the application.
Note: I use a custom directory for the storage of books in Kindle app, if that is significant.

### Which version of Calibre are you running?

6.7.1

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

1.39.0

### Log output

<img width="329" alt="image" src="https://user-images.githubusercontent.com/6039997/197908636-f8c8d110-35ff-4c07-8c8c-98cf7d5ce518.png">

**Comment by ElleKayEm** [comment]
The key is automatically retrieved when you add a book and saved if it is successfully decrypted.  But you'll need an earlier version of Kindle for Mac.  See this post: https://www.mobileread.com/forums/showthread.php?t=283371

And this: https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by JavierRSobrino** [comment]
Ok, I managed to find the problem: after instalation of K4mac 1.30, the program automatically updates to 1.33 even if I did have unmarked automated upgrades. So I have to downgrade it manually everytime I start the program.
