### ISSUE TITLE
Can't DeDRM epub (from Library Genesis)

### ISSUE THREAD

**Issue by rinniepoo** [noDRM/DeDRM_tools#194]
### Question / bug report

Have tried v10.0.3 with Calibre 5.44.0, 6.0.0 and 6.7.1. Have also tried Apprentice Harper's v7.2.1 with aforementioned Calibre versions to no avail. I did get the epub from Library Genesis (if that's relevant?). Not sure where to look to troubleshoot now so hopefully somebody can point me in the right direction? Thank you!

### Which version of Calibre are you running?

6.0.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

calibre Debug log
calibre 6.0  embedded-python: True
Windows-10-10.0.19045 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
calibre 6.0  embedded-python: True
Windows-10-10.0.19045 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.36363636363636
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[0.59] main UI initialized...
[0.59] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Hirini Moko Mead - Tikanga Maori_ Living By Maori Values (2016, Huia Publishers) - libgen.li.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Hirini Moko Mead - Tikanga Maori_ Living By Maori Values (2016, Huia Publishers) - libgen.li.epub is a secure Adobe Adept ePub for UUID e8e0f778-9782-44bb-ab2b-60fa75a677a8
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "C:\Users\ceiha\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 343, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\ceiha\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 346, in adeptkeys
adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[2.66] splash screen hidden
[2.66] Started up in 2.66 seconds with 0 books
Added Tikanga Māori to db in: 0.1
Added 1 books in 0.6 seconds

**Comment by ElleKayEm** [comment]
Looks like you don't have ADE authorized with an Adobe ID.

**Comment by rinniepoo** [comment]
> Looks like you don't have ADE authorized with an Adobe ID.

I installed ADE but it said "Document is licensed for a different user account". I did get the book from LibGen so I guess it just happened to have DRM. Are there any workarounds you can recommend I look into?

**Comment by ElleKayEm** [comment]
If you can't read it with ADE authorized with your Adobe ID, then you're not going to be able to remove DRM from this copy of the book.

**Comment by rinniepoo** [comment]
> If you can't read it with ADE authorized with your Adobe ID, then you're not going to be able to remove DRM from this copy of the book.

I see, thank you for explaining that!

**Comment by ElleKayEm** [comment]
You can close the issue.
