### ISSUE TITLE
I couldn't make free DRM ACSM file 

### ISSUE THREAD

**Issue by mnkhprre** [noDRM/DeDRM_tools#203]
### Which version of Calibre are you running?

4.23

### Which version of the DeDRM plugin are you running?

6.8

### Log output

[tmp9N4aPM.txt](https://github.com/noDRM/DeDRM_tools/files/9971410/tmp9N4aPM.txt)

**Comment by ElleKayEm** [comment]
Looks like your actually running DeDRM 10.0.2 on calibre 4.23.  Suggest trying the latest calibre 6.8 and DeDRM 10.0.3.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
