### ISSUE TITLE
Trying to get book off Kindle and they are not opening......noob here, sorry

### ISSUE THREAD

**Issue by WhyYouNoGet** [noDRM/DeDRM_tools#210]
### Question / bug report

Hello hive mind, I am trying to figure out why some books I am importing to a PC from a kindle are not working with the DeDRM plugin.  

any advice would be much appreciated. 

Thanks

### Which version of Calibre are you running?

6

### Which version of the DeDRM plugin are you running?

10.00

### If applicable, which version of the Kindle software are you running?

6.3.4_user_4132720

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.8  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.8  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 109.9069182389937 x 109.50898203592814
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 3440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 3440},
 'virtual_geometry': {'height': 1440, 'width': 3440, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 940, 'width': 1883, 'x': 1501, 'y': 263},
 'full_screened': False,
 'geometry': {'height': 909, 'width': 1883, 'x': 1501, 'y': 294},
 'maximized': False,
 'normal_geometry': {'height': 909, 'width': 1883, 'x': 1501, 'y': 294},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1440,
                                           'width': 3440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1440, 'width': 3440},
            'virtual_geometry': {'height': 1440,
                                 'width': 3440,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 3440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 3440},
 'virtual_geometry': {'height': 1440, 'width': 3440, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 909, 'width': 1883, 'x': 1501, 'y': 294}
[0.55] main UI initialized...
[0.55] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt B000OZ0NXA_EBOK.prc
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Killing Floor (Jack Reacher, Book 1)
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\USER\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[8.41] splash screen hidden
[8.41] Started up in 8.41 seconds with 0 books
Added Killing Floor (Jack Reacher, Book 1) to db in: 0.1
Added 1 books in 0.4 seconds

**Comment by WhyYouNoGet** [comment]
thanks for the link, I will look into it.  But the issue is these are books on the Kindle that I can tryin got convert using Calibre.

**Comment by ElleKayEm** [comment]
Directly from the Kindle, it would need to be an older E-ink Kindle and have its serial number entered into DeDRM's customization.

**Comment by WhyYouNoGet** [comment]
I was able to make the mobileread stuff work.  thank you for the help.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
