### ISSUE TITLE
Cannot open DRM file from Google Play Book | newbie here, sorry..

### ISSUE THREAD

**Issue by grgyu10** [noDRM/DeDRM_tools#217]
Hello, i want to convert acsm file i got from Google Play book. But Calibre says the format is not supported. anyone can help?

Which version of Calibre are you running?
6.9.0

Which version of the DeDRM plugin are you running?
10.0.3

Log output

calibre, version 6.9.0
WARNING: Could not convert some books: Could not convert the book because no supported source format was found

Koala Kumal-pdf - No supported formats (Available formats: acsm)

**Comment by ElleKayEm** [comment]
That's not the actual book file.  You need Adobe Digital Editions.  Authorize it with an Adobe ID.  Then use it to open the acsm file and the epub or pdf will download.

**Comment by grgyu10** [comment]
> That's not the actual book file. You need Adobe Digital Editions. Authorize it with an Adobe ID. Then use it to open the acsm file and the epub or pdf will download.

Thanks for the help. The book is already in my kindle now :)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by noDRM** [comment]
Looks like this is solved; if not, feel free to re-open.
