### ISSUE TITLE
Plugin is invalid. It does not contain a top-level _init_.py file.

### ISSUE THREAD

**Issue by jcakadub** [noDRM/DeDRM_tools#222]
Sorry -- I solved my own stupid problem.

I have Caliber 6.6.1 and am trying to install DeDRM_tools 10.10.3.  I have downloaded the zip file, and when trying to install, I get the following error: 

calibre, version 6.6.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\Biblioadmin\\Downloads\\DeDRM_tools_10.0.3 (1).zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.6.1  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Annotations (1, 17, 13) && Generate Cover (2, 2, 0) && Job Spy (1, 0, 192) && Library Codes (1, 0, 53) && Quality Check (1, 12, 0) && Zotero Metadata Importer (1, 0, 77)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\Biblioadmin\\Downloads\\DeDRM_tools_10.0.3 (1).zip' is invalid. It does not contain a top-level __init__.py file

Should I download all of the code files and combine them into a ZIP?  Any other suggestions?

**Comment by jcakadub** [comment]
Solved my own problem.

**Comment by TimoKramer** [comment]
ok, but how? how to solve that?

**Comment by ElleKayEm** [comment]
Don't load the whole archive.  Extract DeDRM_plugin.zip and load just that.

**Comment by TimoKramer** [comment]
Haha, yeah got that eventually :)
