### ISSUE TITLE
Need help installing and running kindleykey script

### ISSUE THREAD

**Issue by cmc302a** [noDRM/DeDRM_tools#224]
### Question / bug report

Hello!
Thanks for all the effort put into this.

I have been struggling many hours to get the kindlekey script working under linux, since obtaining the Windows-kindle keys is the only way to get DeDRM to work, without owning a physical kindle, and with kindle-for-windows only working under a wine container. However, the requirements, dependencies and versions are not playing well with each other. For starters, there is no easy way to get PyCrypt, since it's been deprecated for »8 years now... Please, a step-by-step tutorial or walkthrough to get these keys would be very appreciated. 

Keep up the good work!

### Which version of Calibre are you running?

6.7.1

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

1.16.0

**Comment by ElleKayEm** [comment]
Temporarily install Windows calibre with DeDRM where you have Kindle for PC.  Then there are no worries about installing Python or PyCryptodome because it uses calibre's embedded Python.  Once you've successfully decrypted a book there, save the key and import it into your Linux calibre/DeDRM.

**Comment by cmc302a** [comment]
> Temporarily install Windows calibre with DeDRM where you have Kindle for PC. Then there are no worries about installing Python or PyCryptodome because it uses calibre's embedded Python. Once you've successfully decrypted a book there, save the key and import it into your Linux calibre/DeDRM.

Thanks for the advice, unfortunately, Windows Calibre doesn't run in the wine prefix where Kindle for PC resides (it crashes with some "pyby" error message, regardless of the version or architecture of calibre installed). 

Is there really no way to run said scripts? Kindle for PC is running fine!

**Comment by ElleKayEm** [comment]
You should be able to run the kindlekey script from the plugin on its own.  I just have no experience with what you would need as far as installing Python and Pycryptodome under wine.

**Comment by cmc302a** [comment]
Ok, I see. Well, alternatively, could you pinpoint which version of calibre should I download and install? 64-bit is discarded (I created a wine-32 prefix), so only the question is: should I install the "normal" package, or the "portable" one?:

![imagen](https://user-images.githubusercontent.com/39476825/206095310-98cf43da-3cbf-40fd-aa63-2af06ebcdffb.png)

**Comment by ElleKayEm** [comment]
I'd try the regular 32-bit one then.

**Comment by cmc302a** [comment]
Thank you for reading through this. I finally managed to make it work! I posted my guide in the discussion section named "show and tell", I think that's the appropriate place to share it instead of this issue section:

https://github.com/noDRM/DeDRM_tools/discussions/229#discussion-4640708
