### ISSUE TITLE
DeDRM not working on ebook

### ISSUE THREAD

**Issue by billymccom** [noDRM/DeDRM_tools#227]
### Question / bug report

I have installed the new version of Calibre and installed the DRM plugin. I have deleted the book and added it multiple times, and it still won't open. I am using a Mac, with OS Catalina 10.15.7. The ebook in question is a EPUB. Just something I downloaded from the net.

### Which version of Calibre are you running?

6.9.0

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

Using calibre Qt style: True
calibre Debug log
calibre 6.9  embedded-python: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.9  embedded-python: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.00000171210824 x 114.00000171210824
[0.00] Starting up...
[0.13] Showing splash screen...
[0.48] splash screen shown
[0.48] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 762, 'width': 1012, 'x': 91, 'y': 23},
 'full_screened': False,
 'geometry': {'height': 740, 'width': 1012, 'x': 91, 'y': 45},
 'maximized': False,
 'normal_geometry': {'height': 740, 'width': 1012, 'x': 91, 'y': 45},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 800,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 800, 'width': 1280},
            'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 740, 'width': 1012, 'x': 91, 'y': 45}
[1.60] main UI initialized...
[1.60] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt impossible object - mosley, nicholas, 1923-.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: impossible object - mosley, nicholas, 1923-.epub is a secure Adobe Adept ePub for UUID a362fdbf-481c-4400-9d89-148d2563ba8a
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
    defaultkeys, defaultnames = adeptkeys()
  File "/Users/jaydenmccomiskie/Library/Preferences/calibre/plugins/DeDRM.zip/adobekey.py", line 439, in adeptkeys
    raise ADEPTError("Could not find ADE activation.dat file.")
adobekey.ADEPTError: Could not find ADE activation.dat file.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[4.30] splash screen hidden
[4.30] Started up in 4.30 seconds with 38 books
Added Impossible object to db in: 0.0
Added 1 books in 0.8 seconds

**Comment by billymccom** [comment]
Thank you for your reply. I'm sorry I'm new to this. How would I delete the Adobe key?

Thank you,
Jayden


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ElleKayEm** [comment]
In calibre, Preferences > Plugins.  Select DeDRM under File type plugins.  Click Customize plugin > Adobe Digital Editions ebooks.  Select the key and click the red x.  Click ok and apply on your way out.  Then restart calibre.

But if you didn't have ADE authorized with your Adobe ID before opening the acsm file, you may be out of luck.

**Comment by billymccom** [comment]
Hi. Yeah there is nothing to select and delete in "Adobe Digital Editions ebooks".

I've never had issues before. It only started when I recently upgraded to the new Calibre and updated by computer to Catalina.

I also can't find ADE on my laptop anymore.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ElleKayEm** [comment]
If it was ADE 2.0.1, that was a 32-bit program.

How did you download the book?

**Comment by billymccom** [comment]
From SoulSeek. So just a file sharing program. Maybe the ebook is corrupted?



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by noDRM** [comment]
Closing this issue as unfixable. The DeDRM tools can only remove the DRM from books that you have the decryption key for. Books downloaded from filesharing sites that still happen to have DRM are connected to the uploader's account and there's no way to decrypt them.
