### ISSUE TITLE
Y'all am I retarded or is there no DeDRM zip file?

### ISSUE THREAD

**Issue by mortaaarion** [noDRM/DeDRM_tools#228]
### Question / bug report

Okay okay so there's the DeDRM_tools-master.zip, which when unzipped produces the DeDRM_plugin folder. But inside the folder is no zip for Calibre to install. I've tried compressing this DeDRM_plugin folder but Calibre says it lacks an init or whatever. What do I do?

### Which version of Calibre are you running?

6.9.0

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Get the 10.0.3 release here: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

First link under Assets.  Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip.

**Comment by AthulMuralidhar** [comment]
> Get the 10.0.3 release here: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

worked, thx ::)
