### ISSUE TITLE
New Amazon DRM

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [noDRM/DeDRM_tools#23]
### Question / bug report

I just bought a good number of books yesterday, but despite the complement having all the keys in existance up to last year, most of them give me the following error:
```Exception: Incorrect padding - Wrong key```
```DeDRM v10.0.2: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key```

### Which version of Calibre are you running?

5.35.0

### Which version of the DeDRM plugin are you running?

v10.0.2

### If applicable, which version of the Kindle software are you running?

1..33.0.62002

**Comment by l-l-l-l-l-l** [comment]
Rolling back did nothing. The issue here is that every January they expand the number of encryption keys.
I prefer KFX ebooks when available, but I just had the worst timing.
Time to just wait and see.

**Comment by l-l-l-l-l-l** [comment]
OK, it seems to work if I go one by one, but if I batch import them, it fails despite the log showing no errors.

**Comment by ElleKayEm** [comment]
So DRM removal is working.

**Comment by l-l-l-l-l-l** [comment]
Can't really say if I'd count that as "working", but I have no way to see if it's because of the KFX input extension or a weird artifact from this one.
I've tried opening the resulting kfx files with Kindle Previewer, but it says the files are unsupported.

**Comment by ElleKayEm** [comment]
AZW3 format tends to convert better.  But if the misformatting comes from the publisher, they might also be a mess.
