### ISSUE TITLE
DeDRM fails to decrypt: encryption EBX_HANDLER (IndexError: list index out of range)

### ISSUE THREAD

**Issue by michal-devel** [noDRM/DeDRM_tools#233]
**Question / bug report**
I used ACSM Input Plugin to download ebook. It downloads the book correctly, however DeDRM fail to decrypt the file.

**Which version of Calibre are you running?**
5.37

**Which version of the DeDRM plugin are you running?**
v.10.0.3

Please have a look at log file:

```
DeDRM v10.0.3: Trying to decrypt ooqmsq26.pdf
DeDRM v10.0.3: ooqmsq26.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: ooqmsq26.pdf is a PDF ebook (EBX) for UUID xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
DeDRM v10.0.3: Trying UUID-matched encryption key adobe_uuid_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
error writing pdf: Invalid object number: objid=3290
Traceback (most recent call last):
  File "/home/michal/.config/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1820, in getobj
    obj = objs[i]
IndexError: list index out of range
```

I'm happy to help you investigate this issue. At first I created an issue at  [ACSM Input Plugin for Calibre](https://github.com/Leseratte10/acsm-calibre-plugin/issues/44).

**Comment by noDRM** [comment]
Hard to say without having access to both the PDF file and the decryption key. Can you try this test version and see if that works?

[DeDRM_plugin_test_233.zip](https://github.com/noDRM/DeDRM_tools/files/10294127/DeDRM_plugin_test_233.zip)

If it doesn't, I'd need to have the PDF and the key file to take a closer look. If you're willing to share these, my email is on my Github profile.

**Comment by michal-devel** [comment]
I’m back on 27th. I will try the test version, and, if needed, send you the
files you asked for.
Many thanks for your input!

W dniu pt., 23.12.2022 o 10:56 noDRM ***@***.***> napisał(a):

**Comment by michal-devel** [comment]
I has worked flawlessly! I tested the updated plugin on three PDFs and it worked without any problems.

**Comment by noDRM** [comment]
Thanks for confirming, I've added that bugfix to the repository.

**Comment by teerapap** [comment]
I also want to confirm that v10.0.9 solves this problem. 
Thanks a lot for the fix. 😃
