### ISSUE TITLE
Can't remove DRM from epub - hardened DRM?

### ISSUE THREAD

**Issue by tonyfoord** [noDRM/DeDRM_tools#242]
### Question / bug report

First, thank you so much for maintaining this plugin.

I have one recently purchased epub from which the plugin can't remove the drm. This book does open ok in Adobe Digital Editions, and the plugin successfully removes the drm from other epubs I have purchased before and since the one that has the issue.

### Which version of Calibre are you running?

6.10

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.10  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Set KFX metadata (from KFX Output) (1, 65, 0) && KFX Output (1, 65, 0) && KePub Input (3, 6, 3) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (10, 0, 0)
calibre 6.10  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Set KFX metadata (from KFX Output) (1, 65, 0) && KFX Output (1, 65, 0) && KePub Input (3, 6, 3) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (10, 0, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.99999999999999 x 128.18691588785046
[0.00] Starting up...
[0.02] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.36] db initialized
[0.36] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1048, 'width': 1920, 'x': 2, 'y': 0},
 'full_screened': False,
 'geometry': {'height': 1017, 'width': 1920, 'x': 2, 'y': 31},
 'maximized': False,
 'normal_geometry': {'height': 1017, 'width': 1920, 'x': 2, 'y': 31},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 1017, 'width': 1920, 'x': 2, 'y': 31}
[1.38] main UI initialized...
[1.38] Hiding splash screen
Starting QuickView
SMART_DEV (   0.00:  0.001) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.25:  0.823) _startup_on_demand listening on port 9090
SMART_DEV (   1.30:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.32:  0.000) _startup_on_demand broadcast socket listening on port 54982
[3.11] splash screen hidden
[3.11] Started up in 3.11 seconds with 5028 books
DeDRM v10.0.3: Trying to decrypt Ultrasonics.epub
DeDRM v10.0.3: Verifying zip archive integrity
SMART_DEV (   2.35:  1.008) run All IP addresses {'{F220FED4-D30A-4EE3-B20E-ED51EB8E2341}': [{'addr': '192.168.1.54', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}], '{9EA8DECD-ECB2-11E8-8FB6-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x8e\xda\xc5\xec+\x15\x17\x07\xdc\xd63x\xcf\xc0\xb6\x94\xed6NX+\xe0\xb7%C\xf8\x80,\xfd\xc5B\xeb', b'C:\\Users\\tonyf\\Documents\\My Digital Editions\\Ultrasonics.epub']
DeDRM v10.0.3: Ultrasonics.epub is a secure Adobe Adept ePub for UUID 85e518a1-7bc8-4f29-bc89-da4d5e3f0103
DeDRM v10.0.3: Trying UUID-matched encryption key adobe_uuid_85e518a1-7bc8-4f29-bc89-da4d5e3f0103
f0_6iohf.epub is a secure Adobe Adept ePub.
Could not decrypt f0_6iohf.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\tonyf\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 305, in decryptBook
  File "Crypto\PublicKey\RSA.py", line 786, in import_key
  File "Crypto\PublicKey\RSA.py", line 685, in _import_keyDER
ValueError: RSA key format is not supported

DeDRM v10.0.3: Trying Encryption key adobe_uuid_85e518a1-7bc8-4f29-bc89-da4d5e3f0103
f0_6iohf.epub is a secure Adobe Adept ePub.
Could not decrypt f0_6iohf.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\tonyf\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 305, in decryptBook
  File "Crypto\PublicKey\RSA.py", line 786, in import_key
  File "Crypto\PublicKey\RSA.py", line 685, in _import_keyDER
ValueError: RSA key format is not supported

DeDRM v10.0.3: Failed to decrypt with key adobe_uuid_85e518a1-7bc8-4f29-bc89-da4d5e3f0103 after 1.0 seconds
DeDRM v10.0.3: Trying Encryption key default_key
f0_6iohf.epub is a secure Adobe Adept ePub.
Could not decrypt f0_6iohf.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\tonyf\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 342, in decryptBook
  File "C:\Users\tonyf\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 180, in get_xml
AttributeError: 'Decryptor' object has no attribute '_encryption'

DeDRM v10.0.3: Failed to decrypt with key default_key after 6.5 seconds
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 6.5 seconds
Found 1 keys
DeDRM v10.0.3: Ultimately failed to decrypt after 6.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 6.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

**Comment by tonyfoord** [comment]
I think the answer to that is "yes" - I've only ever had one Adobe ID.

**Comment by tonyfoord** [comment]
The only difference I'm aware of with this book is it's from a different publisher (not a different ebook store).

**Comment by ElleKayEm** [comment]
Did you originally download it via ADE or the DeACSM plugin?  And was it setup with your Adobe ID at the time?

**Comment by tonyfoord** [comment]
I originally downloaded it via ADE, I didn't have the DeACSM plugin installed at this time. I then installed the DeACSM plugin and tried again using this to see if this helped. It didn't. I also purchased another copy of the same book from a different bookstore and tried downloading that, also with the same results. Finally, I tried downloading a selection of other books both via ADE and via DeACSM with no problem using either.

**Comment by ElleKayEm** [comment]
Ok, @noDRM will have to take a look.  I don't recall seeing anything like this before.

**Comment by noDRM** [comment]
Damnit, how did this ever work before with that bug ...

In the plugin settings, do you have "Deobfuscate EPUB fonts" enabled or disabled?

Can you test this version and see if that works?
[DeDRM_plugin.zip](https://github.com/noDRM/DeDRM_tools/files/10357664/DeDRM_plugin.zip)

**Comment by tonyfoord** [comment]
Thank you for looking into this. I've always had Deobfuscate ticked. I've just tried the version linked above. It hasn't solved the problem but it does seem to be a significant step forward. Before when I tried to import the book I just got the blank blue cover picture that Calibre uses when it can't extract a cover. With the new version I am now seeing the correct cover art but when I try to open the book I still get the message that it is protected by DRM. I tried this with and without Deobfuscate ticked and the results were the same.

**Comment by noDRM** [comment]
Interesting. Maybe the book has some other junk data in the encryption.xml that either trips up the plugin or Calibre itself. Would you be willing to send me the two versions of the book, the original with DRM (before you imported it) and the one created with this test version that Calibre claims still has DRM? Then I can take a closer look at what the issue might be. My mail address is in my Github profile. 

Also, can you post a new debug log with this test version?

**Comment by tonyfoord** [comment]
Happy to send you both versions of the book but they are each 150MB+ so maybe something like dropbox would be better than email?

**Comment by noDRM** [comment]
Yeah, this here is the interesting block from the log: 

    DeDRM v10.0.3: Trying Encryption key default_key
    ry665qi5.epub is a secure Adobe Adept ePub.
    Adding encryption.xml for the remaining embedded files.
    DeDRM v10.0.3: Decrypted with key default_key after 6.2 seconds

This means that the encryption.xml file (that usually just contains DRM config) has additional non-DRM-related data in it, according to the plugin. That's probably why Calibre thinks the book still has DRM. 

Though, whether that's a bug in my plugin, a bug in Calibre, or just a broken book / mistake by the publisher, I can only say when I have access to the books. If you have a way to upload them somewhere like on Dropbox you can also send me a download link, yeah.

**Comment by tonyfoord** [comment]
I've copied both book files to my Microsoft OneDrive space - the calibre-style title is the partially dedrmed version. This is the link it generated (I haven't tried this before so let me know if there's a problem):

Test (file://DESKTOP-O9LERQK/Users/tonyf/OneDrive/Test)




    On Friday, 6 January 2023 at 10:36:10 GMT, noDRM ***@***.***> wrote:  
 
 


Yeah, this here is the interesting block from the log:
DeDRM v10.0.3: Trying Encryption key default_key
ry665qi5.epub is a secure Adobe Adept ePub.
Adding encryption.xml for the remaining embedded files.
DeDRM v10.0.3: Decrypted with key default_key after 6.2 seconds

This means that the encryption.xml file (that usually just contains DRM config) has additional non-DRM-related data in it, according to the plugin. That's probably why Calibre thinks the book still has DRM.

Though, whether that's a bug in my plugin, a bug in Calibre, or just a broken book / mistake by the publisher, I can only say when I have access to the books. If you have a way to upload them somewhere like on Dropbox you can also send me a download link, yeah.

**Comment by tonyfoord** [comment]
OK, that's interesting. I don't really understand any of this but looks like the problem is at least partly the Calibre reader rather than the dedrm plugin. I copied the apparently still drmed version of the file imported using the test version to an android tablet and Moon+ Reader can open it ok...

**Comment by noDRM** [comment]
That link isn't working, that's just the local path to the file on your computer. You probably need to log in on Onedrive and click on "Share" or something to get a proper link. 

If readers other than Calibre can open the book at least that means that the DRM removal itself is working now (so I'm going to commit that change I made in the test version to the repo later today). But the question is still, is this a bug in Calibre, or is it a bug in the plugin and other readers are just more fault-tolerant than Calibre.

**Comment by tonyfoord** [comment]
Sorry, I thought that didn't look right. Try this:

https://1drv.ms/u/s!AovjImz7oAW-4i-xUFRVTO6FlWXY?e=w57Ifj


    On Friday, 6 January 2023 at 11:04:41 GMT, noDRM ***@***.***> wrote:  
 
 


That link isn't working, that's just the local path to the file on your computer. You probably need to log in on Onedrive and click on "Share" or something to get a proper link.

If readers other than Calibre can open the book at least that means that the DRM removal itself is working now (so I'm going to commit that change I made in the test version to the repo later today). But the question is still, is this a bug in Calibre, or is it a bug in the plugin and other readers are just more fault-tolerant than Calibre.

**Comment by noDRM** [comment]
Looks like that book is using a rarely-used feature of the Adobe DRM that has never been implemented in the tools until now. Calibre was indeed correct, there's still DRM on the book - but only on some files. 

That book not only contains HTML but also a bunch of videos. These videos use a variant of the DRM encryption that's apparently better suited for large already-compressed files - which I've never seen in use before - and the plugin didn't recognize that. So the HTML parts of the book were handled correctly (that's why other readers could open the books), but the videos still had DRM and thus the DRM config remained inside the book, and thus Calibre complained the book has DRM. 

The plugin version I've just pushed should hopefully support that video variant so the DRM should get removed completely with that version and Calibre will hopefully open the book then. Couldn't 100% test that as I don't have your account key, though. 

Would you mind testing this version of the plugin and load the book with DRM into Calibre again and see if that fixes it and the book correctly opens then?

https://github.com/noDRM/DeDRM_tools/suites/10221472192/artifacts/500856155

**Comment by noDRM** [comment]
Yeah, you can delete the folder if you want, since the bug is now fixed I no longer need the book files. Thanks for confirming.
