### ISSUE TITLE
Cannot convert / DRM still present

### ISSUE THREAD

**Issue by hqoiiol** [noDRM/DeDRM_tools#254]
### Question / bug report

I am using DeACSM & DeDRM - I had previously tried pulling the epub directly from ADE with no luck. I am getting a little further with DeACSM, but there is a problem converting / opening book with DRM.

I removed the book from Calibre, enabled debug, and re-imported. Seems like DeACSM is able to pull down the book & convert to EPUB, but I cannot convert or open the file.

Same issue with two books, one I purchased & one on loan.

I did also try pulling down the latest build of DeDRM & no such luck there either.

Any help would be appreciated & let me know what else I can provide

### Which version of Calibre are you running?

6.10

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

Log output is quite long, uploaded it here: https://pastebin.com/edit/Y6CMx0m8

**Comment by ElleKayEm** [comment]
From this log it appears DRM removal was successful:

> DeDRM v10.0.3: Decrypted with key DeACSM_uuid_95d6395e-9694-11ed-a1eb-0242ac120002 after 0.4 seconds
DeDRM v10.0.3: Post-processing took 0.0 seconds
DeDRM v10.0.3: Finished after 0.4 seconds

**Comment by hqoiiol** [comment]
Okay, for what it's worth I tried upgrading to Calibre 6.11 & no luck - but I downloaded the last 5.x release (5.44) & loaded the same plugins and it worked no problem.

No clue... But I appreciate the help
