### ISSUE TITLE
DeDRM not working on epub generated from acsm on ADE

### ISSUE THREAD

**Issue by tankiano** [noDRM/DeDRM_tools#274]
### Question / bug report

I got this ebook in .acsm format and opened it with ADE and converted into epub. Then I imported it on Calibre but the DeDRM plugin won't work.

### Which version of Calibre are you running?

6.12

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

Blacklisting the DeDRM plugin as it is too old and causes crashes
Using calibre Qt style: True
qt.qpa.fonts: Populating font family aliases took 57 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost. 
calibre Log di debug
calibre 6.12  embedded-python: True
macOS-13.0.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'arm64')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 6.12  embedded-python: True
macOS-13.0.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'arm64')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.05] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Built-in Retina Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 1200, 'width': 3360, 'x': 0, 'y': 0}}
{'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1200,
                                'width': 1920,
                                'x': 1440,
                                'y': 0},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': 'BenQ SW240',
 'serial': '',
 'size_in_logical_pixels': {'height': 1200, 'width': 1920},
 'virtual_geometry': {'height': 1200, 'width': 3360, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1200, 'width': 1920, 'x': 1440, 'y': 0},
 'full_screened': True,
 'geometry': {'height': 1200, 'width': 1920, 'x': 1440, 'y': 0},
 'maximized': False,
 'normal_geometry': {'height': 1147, 'width': 1920, 'x': 1440, 'y': 53},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1200,
                                           'width': 1920,
                                           'x': 1440,
                                           'y': 0},
            'index_in_screens_list': 1,
            'manufacturer': '',
            'model': '',
            'name': 'BenQ SW240',
            'serial': '',
            'size_in_logical_pixels': {'height': 1200, 'width': 1920},
            'virtual_geometry': {'height': 1200,
                                 'width': 3360,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1200,
                                'width': 1920,
                                'x': 1440,
                                'y': 0},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': 'BenQ SW240',
 'serial': '',
 'size_in_logical_pixels': {'height': 1200, 'width': 1920},
 'virtual_geometry': {'height': 1200, 'width': 3360, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 1200, 'width': 1920, 'x': 1440, 'y': 0}
Restoring widget to full screen
[0.56] main UI initialized...
[0.56] Hiding splash screen
[0.57] splash screen hidden
[0.57] Started up in 0.57 seconds with 1 books
Starting QuickView
Blacklisting the DeDRM plugin as it is too old and causes crashes
Added Come essere stoici to db in: 0.0
Added 1 books in 0.3 seconds
Saving geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1175, 'width': 1920, 'x': 1440, 'y': 25},
 'full_screened': True,
 'geometry': {'height': 1147, 'width': 1920, 'x': 1440, 'y': 53},
 'maximized': False,
 'normal_geometry': {'height': 1200, 'width': 1920, 'x': 1440, 'y': 0},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1200,
                                           'width': 1920,
                                           'x': 1440,
                                           'y': 0},
            'index_in_screens_list': 1,
            'manufacturer': '',
            'model': '',
            'name': 'BenQ SW240',
            'serial': '',
            'size_in_logical_pixels': {'height': 1200, 'width': 1920},
            'virtual_geometry': {'height': 1200,
                                 'width': 3360,
                                 'x': 0,
                                 'y': 0}}}

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by tankiano** [comment]
Hi EllaKayEm, thanks for the quick reply! I am already using the latest update (13 July 2022).

**Comment by ElleKayEm** [comment]
Log shows old Apprentice Harper version 7.2.1.

**Comment by tankiano** [comment]
I tried both, but none works. I must have copied the wrong log. Here is with the latest version:

Using calibre Qt style: True
qt.qpa.fonts: Populating font family aliases took 55 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost. 
calibre Log di debug
calibre 6.12  embedded-python: True
macOS-13.0.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'arm64')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.12  embedded-python: True
macOS-13.0.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'arm64')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.04] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Built-in Retina Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 875, 'width': 1440, 'x': 0, 'y': 25},
 'full_screened': False,
 'geometry': {'height': 847, 'width': 1440, 'x': 0, 'y': 53},
 'maximized': True,
 'normal_geometry': {'height': 847, 'width': 1440, 'x': 0, 'y': 53},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Built-in Retina Display',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Built-in Retina Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 847, 'width': 1440, 'x': 0, 'y': 53}
Restoring widget to maximized
[0.49] main UI initialized...
[0.49] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Come essere stoici-1.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Come essere stoici-1.epub is a secure Adobe Adept ePub for UUID 57d1a810-ebf3-45a7-af1d-9d3b6ab7b221
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Trying a new default key
o6b6hs_x.epub is a secure Adobe Adept ePub.
Could not decrypt o6b6hs_x.epub because of an exception:
Traceback (most recent call last):
  File "/Users/***/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 327, in decryptBook
    decryptor = Decryptor(bookkey, encryption)
  File "/Users/***/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 150, in __init__
    self._aes = AES.new(bookkey, AES.MODE_CBC, b'\x00'*16)
  File "Crypto/Cipher/AES.py", line 232, in new
  File "Crypto/Cipher/__init__.py", line 79, in _create_cipher
  File "Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto/Cipher/AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.3: Failed to decrypt with new default key after 0.2 seconds
DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[2.30] splash screen hidden
[2.30] Started up in 2.30 seconds with 1 books
Added Come essere stoici to db in: 0.0
Added 1 books in 0.4 seconds
Saving geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 875, 'width': 1440, 'x': 0, 'y': 25},
 'full_screened': False,
 'geometry': {'height': 847, 'width': 1440, 'x': 0, 'y': 53},
 'maximized': True,
 'normal_geometry': {'height': 847, 'width': 1440, 'x': 0, 'y': 53},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Built-in Retina Display',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}

**Comment by tankiano** [comment]
I forgot to mention I did the conversion to epub on my e-reader (android) and I am using calibre on my laptop (macos).

**Comment by ElleKayEm** [comment]
Do you have ADE on your laptop authorized with the same Adobe ID as whatever app you used to download the epub on your Android ereader?

**Comment by tankiano** [comment]
I tried to authorize ADE on my laptop, but I get an error message saying that I can only use an ID Adobe that hasn't been used to authorize other devices.

**Comment by ElleKayEm** [comment]
That's a problem.  DeDRM is retrieving the key from ADE on your laptop.  That key would work if it was authorized with the same ID as the app where you downloaded the book.  OR if you had originally downloaded the book with ADE on your laptop.  I don't know how this can be resolved.

**Comment by tankiano** [comment]
I managed! I deauthorized ADE on the android reader and authorized it on the laptop. Then I opened the .acsm on ADE on my laptop, generated a new .epub version, and imported it on Calibre. Now I can open the new .epub on my e-reader (Onyx Boox Note Air 2 Plus).

Thanks for your help and for maintaining this plugin!

**Comment by ElleKayEm** [comment]
Fantastic!  Thanks for describing how you were able to get it to work.  If you're all set, you can close the issue.
