### ISSUE TITLE
Calibre 6.xx - InvalidPlugin 10.0.3 - top-level __init__.py file missing

### ISSUE THREAD

**Issue by Mathiasw** [noDRM/DeDRM_tools#275]
I have recently upgraded to Calibre 6.12 (also tried 6.11 and 6.00) and whenever I try to install the plugin I get that error.

calibre, version 6.11.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Volumes/Downloads/Calibre Kindle Mobipocket Iliad/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.11  embedded-python: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 479, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 298, in load
  File "calibre/customize/zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Volumes/Downloads/Calibre Kindle Mobipocket Iliad/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip.

**Comment by Mathiasw** [comment]
Arg! I didn't think to actually look IN the zip, I just threw it at Calibre. Thanks!
