### ISSUE TITLE
Exception: Failed to decrypt KFX DRM voucher with any key

### ISSUE THREAD

**Issue by salchint** [noDRM/DeDRM_tools#279]
Hi,
I use `calibre-portable 6.12.0` and `DeDRM_tools_10.0.3` on Windows 10.
I have tried to import/remove DRM from the only e-book, that I have on Kindle at the moment. I have Amazon's Kindle App in version 1.39.2 installed on the same PC. Also, the KFX plugin is installed too as you advised in your documentation.
The DRM removal failed. Please have a look at the attached logs for details about the problem
[tmp5kijv14i.txt](https://github.com/noDRM/DeDRM_tools/files/10694179/tmp5kijv14i.txt)

**Comment by ElleKayEm** [comment]
You can't decrypt kfx format downloaded with 1.39.  See this post for workarounds: https://www.mobileread.com/forums/showthread.php?t=283371
