### ISSUE TITLE
Issue with DRM and Plug in Tools 10-2 not working

### ISSUE THREAD

**Issue by RuthBath** [noDRM/DeDRM_tools#283]
Hi, I updated the plug in but it isn't breaking DRM. Debug code is below. I know enough to be dangersous and would appreciate help. I removed book and started Calibre in debug mode. I have my Kindle serial code registered so am at a bit of a loss as has worked before. Have uploaded file of code.  TIA 
[tmpj9lkew7i.txt](https://github.com/noDRM/DeDRM_tools/files/10717674/tmpj9lkew7i.txt)

**Comment by ElleKayEm** [comment]
Looks like you don't have the correct serial number for that copy of the book.  Make sure when downloading from the website that you've chosen the correct E-ink Kindle.  Make sure the serial number is entered in DeDRM correctly.  Copy and paste from the website is the easiest way.

**Comment by RuthBath** [comment]
THank you! We must be channelling cos the moment I hit send I thought ...wrong registration!  Thank you once again

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by RuthBath** [comment]
Thank you . I will go and look how to do that.  Many thanks
