### ISSUE TITLE
DeDRM difficulty w. recent Kindle ebook.

### ISSUE THREAD

**Issue by FlyingSquirrel2020** [noDRM/DeDRM_tools#293]
1st time using DeDRM_tools_10.0.3. I've followed directions as best I could, but still am having trouble w. "There's a Body in the Window Seat!" azw3 document, published November 2022, from Amazon. I'm running windows 10 and Calibre 6.10.

Here is the most recent log file:

[tmp67ugtuuw.txt](https://github.com/noDRM/DeDRM_tools/files/10832239/tmp67ugtuuw.txt)

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle (not a Fire) for the device?  Enter its serial number into DeDRM's customization.  Try copy and paste from the website.

**Comment by FlyingSquirrel2020** [comment]
That seems to have worked. Thanks for the guidance!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by FlyingSquirrel2020** [comment]
Great, thanks!
