### ISSUE TITLE
Obok DeDRM couldn't be decrypted

### ISSUE THREAD

**Issue by yuukiyuuna** [noDRM/DeDRM_tools#295]
### Question / bug report

It tried multiple keys without success, and the key in the log was replaced with "xxxxxxxx"

The kobo desktop version is 4.35.18074

### Which version of Calibre are you running?

6.13.0

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

C:\Users\qq984>calibre-debug -g
calibre 6.13  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 157.8252427184466 x 158.5664739884393
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
[0.00] Starting up...
[0.00] Showing splash screen...
[1.17] splash screen shown
[1.17] Initializing db...
[1.19] db initialized
[1.19] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Restoring geometry for: jobs_dialog_geometry
{'frame_geometry': {'height': 610, 'width': 591, 'x': 24, 'y': 169},
 'full_screened': False,
 'geometry': {'height': 579, 'width': 591, 'x': 24, 'y': 200},
 'maximized': False,
 'normal_geometry': {'height': 579, 'width': 591, 'x': 24, 'y': 200},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 579, 'width': 591, 'x': 24, 'y': 200}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 553, 'width': 1468, 'x': 406, 'y': 326},
 'full_screened': False,
 'geometry': {'height': 522, 'width': 1468, 'x': 406, 'y': 357},
 'maximized': False,
 'normal_geometry': {'height': 522, 'width': 1468, 'x': 406, 'y': 357},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 522, 'width': 1468, 'x': 406, 'y': 357}
[2.66] main UI initialized...
[2.66] Hiding splash screen
Starting QuickView
[3.64] splash screen hidden
[3.64] Started up in 3.64 seconds with 6 books
Running Obok DeDRM v10.0.3
DEBUG:    3.9 didn't find device
Obok v10.0.1
Copyright © 2012-2022 Physisticated et al.
C:\Users\qq984\AppData\Local\Temp\tmpl0cgwf6l
DEBUG:    3.9 got kobodir C:/Users/qq984/AppData/Local/Kobo/Kobo Desktop Edition
Found 8 possible keys to try.
DEBUG:    7.3 BookListTableWidget:get_books - book_num: 0
DEBUG:    7.3 BookListTableWidget:get_books - book: 無法成為神明的少女
DEBUG:    7.3 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.3 - Decrypting 無法成為神明的少女
Trying key:  b'xxxxxxxx'
Bad JPEG: dc04d7
Decryption failed, trying next key.
Trying key:  b'xxxxxxxx'
Bad JPEG: 57d5f8
Decryption failed, trying next key.
Trying key:  b'xxxxxxxx'
Bad JPEG: 9c0024
Decryption failed, trying next key.
Trying key:  b'xxxxxxxx'
Bad JPEG: 5bf76a
Decryption failed, trying next key.
Trying key:  b'xxxxxxxx'
Bad JPEG: 3be410
Decryption failed, trying next key.
Trying key:  b'xxxxxxxx'
Bad JPEG: 7ecd5b
Decryption failed, trying next key.
Trying key:  b'xxxxxxxx'
Bad JPEG: 8321be
Decryption failed, trying next key.
Trying key:  b'xxxxxxxx'
Bad JPEG: a73053
Decryption failed, trying next key.
Obok DeDRM v10.0.3 - Couldn't decrypt 無法成為神明的少女
DEBUG:    7.4 DecryptAddProgressDialog::do_book_action - book decryption failed: '無法成為神明的少女'
Obok DeDRM v10.0.3 - wrapping up results.
Saving geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 553, 'width': 1468, 'x': 406, 'y': 326},
 'full_screened': False,
 'geometry': {'height': 522, 'width': 1468, 'x': 406, 'y': 357},
 'maximized': False,
 'normal_geometry': {'height': 522, 'width': 1468, 'x': 406, 'y': 357},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}

**Comment by ElleKayEm** [comment]
It looks like in the OP that DRM was detected properly, couldn't be removed, and so the book was not imported.

**Comment by WolffHobbitStomper** [comment]
Here's a log showing the import of the same book from desktop app and device. Device succeeds, desktop fails.
NB. I've edited the log to remove unrelated info, and add some comments
[log.txt](https://github.com/noDRM/DeDRM_tools/files/10845452/log.txt)

**Comment by yuukiyuuna** [comment]
Can't use the Kobo desktop app alone?
Unfortunately, I don’t have KOBO devices, it seems that there is no way

I think the log does it seem to try to decrypt with 5 or 6 key areas. Is it the problem that the correct key is obtained?

**Comment by ElleKayEm** [comment]
I'm able to use Kobo Desktop alone.  Obok correctly detects books with DRM and decrypts them.  Just checked now.  I had calibre open.  I opened Kobo Desktop.  It updated, restarted, and downloaded recent books.  Left it open.  Used Obok to add a DRMed book to calibre, and it successfully decrypted.

**Comment by yuukiyuuna** [comment]
> I'm able to use Kobo Desktop alone. Obok correctly detects books with DRM and decrypts them. Just checked now. I had calibre open. I opened Kobo Desktop. It updated, restarted, and downloaded recent books. Left it open. Used Obok to add a DRMed book to calibre, and it successfully decrypted.

I was the Kobo desktop app that was installed yesterday. Maybe the version is too new?
Can you please ask your Kobo desktop app version?

And my OKOB plug -in directory points to this, I don't know if it is consistent with your directory structure
![屏幕截图 2023-02-28 093005](https://user-images.githubusercontent.com/17798350/221729542-8d5e7185-281b-4b73-8858-4d2f3d679941.png)

**Comment by ElleKayEm** [comment]
Kobo Desktop version 4.35.18074
I have the same directory structure.  Although I didn't configure Obok to point to it.

{
  "finding_homes_for_formats": "Add new entry",
  "kobo_directory": "",
  "kobo_serials": []
}

**Comment by yuukiyuuna** [comment]
> Kobo Desktop version 4.35.18074 I have the same directory structure. Although I didn't configure Obok to point to it.
> 
> { "finding_homes_for_formats": "Add new entry", "kobo_directory": "", "kobo_serials": [] }

My kobo desktop app version is exactly the same as yours

Unfortunately, according to your configuration, I modified the plug-in configuration, restarted caliber and tried again. The program still failed to decrypt successfully, and the error was the same as before.

I don't know why the program got eight keys and none of them could be decrypted. I think the problem is here, but I don't know how to fix it

**Comment by ElleKayEm** [comment]
Is it one specific book or all that you're having trouble with?  Have you tried with the Adobe DRM version and DeDRM?

**Comment by yuukiyuuna** [comment]
> Is it one specific book or all that you're having trouble with? Have you tried with the Adobe DRM version and DeDRM?

I currently only have one book on kobo and want to test if the plugin is available

I haven’t used Adobe DRM and DeDRM to try to decrypt it. I need to find related tutorials. DeDRM_plugin is available for kindle decryption, but I don’t know how to configure the kobo desktop app. I will try to configure it in the afternoon

I read the relevant source code of obok. I don’t understand the __oldcookedeviceid function in legacy_obok.py. Are the userkeys obtained by this function obtained from cookies?
![QQ截图20230228112955](https://user-images.githubusercontent.com/17798350/221746399-0b8d8c54-0590-4102-9aa7-12ebaa7abe09.jpg)

**Comment by ElleKayEm** [comment]
Only Obok works for the books downloaded with the Kobo app or device.  But you can also get Adobe DRM epubs of Kobo books which DeDRM can handle.

No idea what's going on with the code there.  I'm just another user.

**Comment by yuukiyuuna** [comment]
> Only Obok works for the books downloaded with the Kobo app or device. But you can also get Adobe DRM epubs of Kobo books which DeDRM can handle.
> 
> No idea what's going on with the code there. I'm just another user.

Ok, I'll try to decode it with DeDRM.

Thank you for answering so many of my questions. Finally, can I ask the version of your caliber?
I want to use a virtual machine to install the same version to try and rule out the problem of my system

**Comment by ElleKayEm** [comment]
calibre 6.13

**Comment by yuukiyuuna** [comment]
> calibre 6.13

I learned how to convert kobo's e-books through Dedrm, which needs to be downloaded through Adobe Digital Edition. But this is more troublesome, I still want to find out why obok is not available, and use obok first to resolve

To this end, I installed calibre6.13.0 and python3.10.0 in my win10 virtual machine. This virtual machine can successfully convert kobo e-books, but not kindle e-books.
I reset my win11 computer, reinstalled calibre6.13.0, python3.10.10, the result kindle is available but kobo is still not available

Looking at the debug log, the win10 virtual machine found 12 usable keys to decrypt during conversion, but my win11 computer only has 8

Now I don't know if it's because of the Windows version or the hardware. In short, this phenomenon is very strange.
It seems that I can only decode kobo e-books through my virtual machine

**Comment by ElleKayEm** [comment]
No need to install Python for this if you're using Windows calibre.  It uses its own embedded Python.  How are you downloading the Kindle books which won't decrypt in the Win10 virtual machine?

I don't know why Obok can't seem to find the correct key in Windows 11.  You can open and read the book in Kobo Desktop?

I usually use the Adobe DRM version myself.  I occasionally get books from other stores which also use that DRM.

**Comment by yuukiyuuna** [comment]
> No need to install Python for this if you're using Windows calibre. It uses its own embedded Python. How are you downloading the Kindle books which won't decrypt in the Win10 virtual machine?
> 
> I don't know why Obok can't seem to find the correct key in Windows 11. You can open and read the book in Kobo Desktop?
> 
> I usually use the Adobe DRM version myself. I occasionally get books from other stores which also use that DRM.

After these two days I tried repeatedly, I finally found the problem
It's a proxy problem

Initially, I used the V2rayN system proxy to log in to the kobo account, and the obok plug-in only found 8 keys to try
But if I switch to a tun-mode agent (such as Clash for Windows), I can convert kobo's e-books, and the number of keys obtained at this time is 12.

It seems that the problem lies in the kobo software. The difference in the proxy method will cause the correctness of the plug-in to obtain the key. This should be a bug. Of course, it may also be a problem with kobo software

I think this problem should be informed to you. If there are users who have the same problem as me in the future, you can try my solution.

**Comment by yuukiyuuna** [comment]
> No need to install Python for this if you're using Windows calibre. It uses its own embedded Python. How are you downloading the Kindle books which won't decrypt in the Win10 virtual machine?
> 
> I don't know why Obok can't seem to find the correct key in Windows 11. You can open and read the book in Kobo Desktop?
> 
> I usually use the Adobe DRM version myself. I occasionally get books from other stores which also use that DRM.

I didn't expect that the different proxy methods would cause such a result. For this reason, I reset my system no less than ten times to rule out the impact of the system environment.

Anyway, the result is good
Thank you for always answering my questions during this period
