### ISSUE TITLE
DeDRM 10.0.3 not working with Calibre 6.13.0 (ADE EPUB file)

### ISSUE THREAD

**Issue by Robnina** [noDRM/DeDRM_tools#296]
The plugin seems to be working fine on another computer, but I cannot get it to work on this machine. Logfile follows below.

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.13  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3) && Overdrive Link (2, 54, 0)
calibre 6.13  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3) && Overdrive Link (2, 54, 0)
QPA platform: windows
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.4890510948905 x 133.24590163934425
[0.00] Starting up...
[0.00] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.62] db initialized
[0.62] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 960, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 960, 'width': 1440},
 'virtual_geometry': {'height': 960, 'width': 1440, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 919, 'width': 1440, 'x': 0, 'y': -6},
 'full_screened': False,
 'geometry': {'height': 890, 'width': 1440, 'x': 0, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 890, 'width': 1440, 'x': 0, 'y': 23},
 'screen': {'depth': 32,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 960,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 960, 'width': 1440},
            'virtual_geometry': {'height': 960, 'width': 1440, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 960, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 960, 'width': 1440},
 'virtual_geometry': {'height': 960, 'width': 1440, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 890, 'width': 1440, 'x': 0, 'y': 23}
Restoring widget to maximized
[2.52] main UI initialized...
[2.52] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Ashes to Ashes.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Ashes to Ashes.epub is a secure Adobe Adept ePub for UUID 13afa5b9-d500-4239-aeae-6c0651e21594
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
[5.86] splash screen hidden
[5.86] Started up in 5.86 seconds with 5399 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xda-\x07UR\x10\xb5\x06\xcc\x1a\x1eU\xb1 \\}\x0c\x8c\xac,}]\xc9\x80&\xbbJ\xbc\x91\x89\x19\xb6', b'C:\\Users\\robni\\Documents\\My Digital Editions\\Ashes to Ashes.epub']
Added Ashes to Ashes to db in: 0.1
Added 1 books in 0.8 seconds

**Comment by ElleKayEm** [comment]
Delete the saved Adobe key from DeDRM's customization.  Re-add the book letting DeDRM automatically retrieve the key.

**Comment by Robnina** [comment]
Awesome! Thanks so much. Cannot believe I missed such a simple thing.... :)
