### ISSUE TITLE
unable to DeDRM from ADE

### ISSUE THREAD

**Issue by smaosmao** [noDRM/DeDRM_tools#31]
I am able to open the ebook file in Adobe Digital Editions. However, when I load it into Calibre, the plugin fails to DeDRM. Debug report is below. I encountered this issue with both this fork of the tool and with Apprentice Alf's version.

-

calibre Debug log
calibre 5.36 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2)
calibre 5.36 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 108.0 x 108.0
physicalDpi: 81.68844221105527 x 81.64285714285714
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.66] splash screen shown
[0.66] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
[1.45] main UI initialized...
[1.45] Hiding splash screen
Starting QuickView
DeDRM v10.0.2: Trying to decrypt Living for the Future.pdf
DeDRM v10.0.2: Living for the Future.pdf is a PDF ebook for UUID d7467447-9d3e-4e34-8f74-83fdd17b417b
DeDRM v10.0.2: Trying encryption key default_key
This seems to be an Adobe ADEPT PDF with Adobe's new DRM
This DRM cannot be removed yet. 
Try getting your distributor to give you a new ACSM file, then open that in an old version of ADE (2.0).
If your book distributor is not enforcing the new DRM yet, this will give you a copy with the old DRM.
DeDRM v10.0.2: Book uses unsupported (too new) Adobe DRM.
DeDRM v10.0.2: Finished after 0.1 seconds
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 315, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
[8.50] splash screen hidden
[8.50] Started up in 8.50 seconds with 58 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x8d\x1f\xb9k\x1fG$5\xbc\xad\x08\x0b\xf2\xc2\xd6!\xbb\t\xca\xb3dE\xc6y\x7fz\xa9E\x0f\xa1\xf0\x1e', b'C:\\Users\\dnewh\\Documents\\My Digital Editions\\Living for the Future.pdf']
Added Living for the Future to db in: 0.2
Added 1 books in 1.0 seconds

**Comment by ElleKayEm** [comment]
As it says in the log:

> This seems to be an Adobe ADEPT PDF with Adobe's new DRM
This DRM cannot be removed yet.
Try getting your distributor to give you a new ACSM file, then open that in an old version of ADE (2.0).
If your book distributor is not enforcing the new DRM yet, this will give you a copy with the old DRM.

**Comment by smaosmao** [comment]
Ah, right - thanks.
