### ISSUE TITLE
AZW3 file drm cannot be removed

### ISSUE THREAD

**Issue by Togatov** [noDRM/DeDRM_tools#320]
calibre Debug log
calibre 3.48  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (10, 0, 3)
calibre 3.48  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (10, 0, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.25] splash screen shown
[0.25] Initializing db...
[0.26] db initialized
[0.26] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Loaded cached store plugin for: Amazon FR Kindle at version: 16
Loaded cached store plugin for: ManyBooks at version: 2
Loaded cached store plugin for: Świat Ebooków at version: 2
Loaded cached store plugin for: Virtualo at version: 10
Loaded cached store plugin for: Woblink at version: 15
Loaded cached store plugin for: LitRes at version: 2
Loaded cached store plugin for: Google Books at version: 7
Loaded cached store plugin for: Legimi at version: 10
Loaded cached store plugin for: Project Gutenberg at version: 7
Loaded cached store plugin for: Empik at version: 9
Loaded cached store plugin for: ebook.de at version: 6
Loaded cached store plugin for: XinXii at version: 2
Loaded cached store plugin for: Nexto at version: 6
[1.37] main UI initialized...
[1.37] Hiding splash screen
[1.38] splash screen hidden
[1.38] Started up in 1.38 seconds with 0 books
objc[6658]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffb4751cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x117304cd8). One of the two will be used. Which one is undefined.
DeDRM v10.0.3: Trying to decrypt Beginner's Russian with Interactive Online Workbook, 2nd edition.azw3
Using Library AlfCrypto Python
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 944, in KindleMobiDecrypt
  File "site-packages/calibre/customize/zipplugin.py", line 185, in load_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 105, in <module>
  File "site-packages/calibre/customize/zipplugin.py", line 181, in load_module
  File "calibre_plugins.dedrm.topazextract", line 246
    if debug: print("%d records in header " % nbValues, end=' ')
                                                           ^
SyntaxError: invalid syntax
Added Beginner's Russian with Interactive Online Workbook, 2nd edition to db in: 0.4
Added 1 books in 1.0 seconds

It is an AZW3 file not the KFX file from amazon so I'm not sure what is going wrong and why the drm cannot be removed. I did put the amazon kindle serial number in correctly in the dedrm plugin. Thanks!

**Comment by noDRM** [comment]
This particular bug is now fixed with f86cff285be1ed43c296e4adc2c3899ca14fd64b, so I'm going to close this issue.
