### ISSUE TITLE
Can't install DeDRM plugin in Calibre

### ISSUE THREAD

**Issue by jeanjyi** [noDRM/DeDRM_tools#326]
### Question / bug report

Whenever I try to import the DeDRM_plugin.zip file into Calibre, I keep getting the error message: InvalidPlugin:The plugin in '/Users/jeanyi/Downloads/DeDRM_tools-master/DeDRM_plugin.zip" is invalid. It does not contain a top-level __init__.py file

But when I unzip and check the folder DeDRM_plugin, I am able to find a top-level __init__.py file. What do I do?

### Which version of Calibre are you running?

6.17.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Paste log output here.
```

**Comment by joecool1029** [comment]
unzip the zip, inside is another zip with the same name, that will install just fine.

**Comment by ElleKayEm** [comment]
Download DeDRM_tools_10.0.3.zip from here : 
https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Unzip that and you will find 2 zips (plugins) and 3 text files (readmes).

**Comment by jeanjyi** [comment]
> Download DeDRM_tools_10.0.3.zip from here : https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
> 
> Unzip that and you will find 2 zips (plugins) and 3 text files (readmes).

Thank you, that worked!
