### ISSUE TITLE
kindlekey.py crashes on M1 Macs

### ISSUE THREAD

**Issue by TuxSH** [noDRM/DeDRM_tools#33]
This line: https://github.com/noDRM/DeDRM_tools/blob/v10.0.2/DeDRM_plugin/kindlekey.py#L1190 , causes the following message to be printed: `Python is loading libcrypto in an unsafe way`. After that, the process is promptly terminated by the OS.

Moreover, `/usr/lib/libcrypto.dylib` does not even exist on M1 Macs.

It might be simpler to remove that portion of code and use pycryptodome/pure-python code as the data to decrypt is very small anyway.

**Comment by noDRM** [comment]
That's probably for the best. All the code with native crypto binaries is probably outdated like hell anyways, as there's just hardcoded binaries in the repo back from when Apprentice Harper compiled them... and as you said, it shouldn't cause large delays when just decrypting ebooks with a couple megabytes. 

I'll try to get rid of all that code in the future.

**Comment by TuxSH** [comment]
Alfcrypto is still needed for mobi/azw3 and topaz as far as I'm aware. libcrypto code, however, can be entirely replaced by pycrypto
