### ISSUE TITLE
How to remove DRM from azw3 files?

### ISSUE THREAD

**Issue by catqueenpurr** [noDRM/DeDRM_tools#341]
### Question / bug report

I have installed the DeDRM plugin. But when I try to convert azw3 files to a different format (e.g. txt), it says "Cannot convert. This book is blocked by DRM"

Is there a trick to make it work? 

I've attached the debug of one book. But it happens with all my books, so it doesn't seem to be book specific. 

I get the books by going to my Amazon account and then selecting "More Actions > Download & transfer via USB".

I made sure that I imported by books after installing the plugin (as the FAQ says the plug in removes DRM after a book is imported). 

### Which version of Calibre are you running?

6.19.1

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

Using calibre Qt style: True
calibre Debug log
calibre 6.19.1  embedded-python: True
macOS-12.6.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Mon Apr 24 21:10:53 PDT 2023; root:xnu-8020.240.18.701.5~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6.6', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
calibre 6.19.1  embedded-python: True
macOS-12.6.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Mon Apr 24 21:10:53 PDT 2023; root:xnu-8020.240.18.701.5~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6.6', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 72.00000108133152 x 72.00000108133152
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.21] db initialized
[0.21] Constructing main UI...
[0.94] main UI initialized...
[0.94] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Easy Spanish Stories For Beginners_ 5 Spanish Short Stories For Beginners (With Audio) (Learn Spanish With Stories) (Spanish Edition).azw3
Using Library AlfCrypto Python
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Easy Spanish Stories For Beginners: 5 Spanish Short Stories For Beginners (With Audio) (Learn Spanish With Stories) (Spanish Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/madhu/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/madhu/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[3.01] splash screen hidden
[3.01] Started up in 3.01 seconds with 2 books
Added Easy Spanish Stories For Beginners: 5 Spanish Short Stories For Beginners (With Audio) (Learn Spanish With Stories) (Spanish Edition) to db in: 0.0
Added 1 books in 0.6 seconds

**Comment by ElleKayEm** [comment]
Are you choosing an E-ink Kindle (not a Fire) when downloading?  Looks like you need to add that Kindle's serial number to DeDRM's customization.

**Comment by catqueenpurr** [comment]
Oh, I only have a fire. So I guess that means I am out of luck?

**Comment by catqueenpurr** [comment]
Unfortunately, the older Kindle for Mac won't work on modern Macs. I guess this is something I will have to leave... Thanks for the assitance provided!

**Comment by ElleKayEm** [comment]
Kindle for Mac is a 64-bit program starting with version 1.25.  So I believe any of the versions from that one up to version 1.31 should work with method 2B.
