### ISSUE TITLE
Unable to import DeDRM plugin after running make_release

### ISSUE THREAD

**Issue by jibin23** [noDRM/DeDRM_tools#357]
I downloaded the source code, then ran "python make_release.py". This output a .zip file, which I tried importing as a plugin in Calibre. However, it failed, stating there is a missing __init__ file. How to proceed here?

<img width="515" alt="Screenshot 2023-06-25 at 3 30 15 PM" src="https://github.com/noDRM/DeDRM_tools/assets/6236473/3bdf66dc-f0e5-4e74-a029-98911384727e">

**Comment by ElleKayEm** [comment]
That file is more than just the one plugin.  Unzip that file and load just DeDRM_plugin.zip.

**Comment by jibin23** [comment]
Got it. Sorry, I missed that & Thanks!
