### ISSUE TITLE
Adobe Digital Editions Scrypt does not work

### ISSUE THREAD

**Issue by jlevy-dev** [noDRM/DeDRM_tools#36]
### Question / bug report

Hey all it is not possible to use this script. I can not install PyCrypto to be able to run this [script ](https://github.com/apprenticeharper/DeDRM_tools/blob/master/Other_Tools/DRM_Key_Scripts/Adobe_Digital_Editions/adobekey.pyw). If anyone knows how to get this running please lmk. Thanks

### Which version of Calibre are you running?

5.36

### Which version of the DeDRM plugin are you running?

 v10.0.2

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Use this one: https://github.com/noDRM/DeDRM_tools/blob/master/DeDRM_plugin/adobekey.py
