### ISSUE TITLE
2 Problems with Amazon Kindle files

### ISSUE THREAD

**Issue by ahorkay** [noDRM/DeDRM_tools#361]
### Question / bug report

1. I have seven or eight Kindle .azw books that I am able to import into Calibre, and they seem to have been DeDRMed (at least no error saying they weren't). But when I double-click on them to open them, I get a message, "Books with the same titles as the following already exist in calibre." However, that's not true (and if it were true, I would have received that error message when importing it, not when trying to open it). So there's no way to open the book (and no way to tell for sure if it's been DeDRMed) because all it does is installs a duplicate copy (unless you click cancel). And if you try to open the second copy, the same thing happens. The log output for when I first added the book is included, in case that helps. 

2. Most of my Kindle books have .azw extensions, but I have four that don't. The files in their folders have the extensions .apnx, .kcr, .mbpV2 and .phl and Calibre won't let me select any of them as being a book to add to calibre or decrypt. Anyone have any idea what these are or how one could add them to Calibre? I do have backup copies of these books (which I bought on a previous older computer, which do have .azw extensions and I can try to import them, but Calibre and the tools won't DeDRM the backup copies. I also have an older laptop and tried to download and deDRM them there (with Calibre 3.48, Tools 10.0.3 and KFX Input 1.51, but that doesn't seem to work either.

### Which version of Calibre are you running?

6.22.0

### Which version of the DeDRM plugin are you running?

10.0.5s (same happens with 10.0.3)

### If applicable, which version of the Kindle software are you running?

1.40.1; also using KFX Input 2.1.0

### Log output

Using calibre Qt style: True
calibre Debug log
calibre 6.22  embedded-python: True
macOS-13.4.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 1, 0) && DeDRM (10, 0, 5) && Package KFX (from KFX Input) (2, 1, 0) && KFX metadata reader (from KFX Input) (2, 1, 0) && KFX Input (2, 1, 0) && Obok DeDRM (10, 0, 3)
calibre 6.22  embedded-python: True
macOS-13.4.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 1, 0) && DeDRM (10, 0, 5) && Package KFX (from KFX Input) (2, 1, 0) && KFX metadata reader (from KFX Input) (2, 1, 0) && KFX Input (2, 1, 0) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000162950651 x 107.50000161448803
[0.00] Starting up...
Failed to read metadata from font file: /Users/alexhorkay/Library/Fonts/CALVINN.TTF tuple index out of range
[0.05] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.94] main UI initialized...
[0.94] Hiding splash screen
Starting QuickView
2023-07-02 20:19:51.730 calibre-debug[4571:147844] +[CATransaction synchronize] called within transaction
2023-07-02 20:20:07.374 calibre-debug[4571:147844] +[CATransaction synchronize] called within transaction
2023-07-02 20:20:15.759 calibre-debug[4571:147844] +[CATransaction synchronize] called within transaction
Gather KFX-ZIP (from KFX Input) 2.1.0: Importing /Users/alexhorkay/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B00INWLOBG_EBOK/B00INWLOBG_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 10 file(s) as /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/wtf6bn9y.kfx-zip
DeDRM v10.0.5: Trying to decrypt wtf6bn9y.kfx-zip
[33.83] splash screen hidden
[33.83] Started up in 33.83 seconds with 99 books
Decrypting KFX-ZIP ebook: wtf6bn9y
Got DSN key from database kindle_key_1688334415_1
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.585af528-1889-4caa-90f3-2718962c6dbf.voucher
strategy
AES
AES/CBC/PKCS5Padding
HmacSHA256
mac
voucher
8b3842516b5eb6f0491002485ec827d3
f705c1ac946a3c02b86ddd2ce6ef53b48b3842516b5eb6f0491002485ec827d3
bytearray(b'\x00_\x00\x00TLACNDIE6HmdHS5I2cgdSCCanaiPKBE3ACP5//SvDESAIP')
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "/Users/alexhorkay/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/Users/alexhorkay/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 1349, in decryptvoucher
    raise ex
UnboundLocalError: local variable 'ex' referenced before assignment
strategy
AES
AES/CBC/PKCS5Padding
HmacSHA256
mac
voucher
8b3842516b5eb6f0491002485ec827d3
f705c1ac946a3c02b86ddd2ce6ef53b48b3842516b5eb6f0491002485ec827d3
bytearray(b'\x00t\x00\x00n78drvSSrS5S3dME56rnthnS2277677_Mnn8nS7TLACND6IE6HmdHS5I2cgdSCCanaiPKBE3ACP5//SvDESAIP')
Decryption failed, trying next fallback 
Decryption succeeded
KFX DRM voucher successfully decrypted
Decrypting KFX DRMION: B00INWLOBG_EBOK.azw
Decryption succeeded after 0.6 seconds
DeDRM v10.0.5: Finished after 0.6 seconds
Package KFX (from KFX Input) 2.1.0: Packaging /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/y94h79kv.kfx-zip
Processing container: B00INWLOBG_EBOK.azw
Processing container: CR!54RCMDC78D6E59JXBC1TS89RFQ73.azw.res
Processing container: CR!60VMS81PWS0VQ3B05PCDV6S0M066.azw.res
Processing container: CR!DDDVKH62J55DSA2KWSA3Q1K2NWN2.azw.md
Processing container: CR!QQFHA601GD5BKD2MQQWZJHQFXNXV.azw.res
Processing container: CR!R893R8T0QX30547T54444MT4X990.azw.res
Processing container: CR!TCHV64W9WD70SDEMEK3ZX7YGJRYA.azw.res
Processing container: CR!V7K62YRRE939S396JWDYA1RMG7FV.azw.res
Processing container: CR!X79HPVZXG544516SCS981YWHAN2Y.azw.res
Features: CanonicalFormat-1, kfxgen.textBlock-1, max_id-696, reflow-style-2
Metadata: ASIN=B00INWLOBG, asset_id=CR!6FM16H1RDS5ZV1WRD5BCT9BZX9AJ, author="Sutherland, John", cde_content_type=EBOK, content_id=B00INWLOBG, cover_image=825x1329, creator_version=2.15.0, file_creator=YJConversionTools, is_sample=False, issue_date=2014-02-06, kfxgen="7.111.1.1/PackageVersion:YJReaderSDK-1.6.444.5 Month-Day:03-20", language=en, pages=306, publisher="Aurum Press Ltd", reading_orders=1, selection=enabled, title="Jumbo: The Unauthorised Biography of a Victorian Sensation"
KFX container created may be too large for some devices (22786925 bytes)
Package KFX (from KFX Input): Imported as /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/ndugg5ny.kfx
KFX metadata reader (from KFX Input) activated for /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/vlayd3mg_add_books/0/B00INWLOBG_EBOK.kfx
Gather KFX-ZIP (from KFX Input) 2.1.0: Importing /Users/alexhorkay/Calibre Library/John Sutherland/Jumbo_ The Unauthorised Biography of a Victorian Sensation (326)/Jumbo_ The Unauthorised Biography of a Vic - John Sutherland.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/3xyssjg3.kfx-zip
DeDRM v10.0.5: Trying to decrypt 3xyssjg3.kfx-zip
Decrypting KFX-ZIP ebook: 3xyssjg3
Got DSN key from database kindle_key_1688334415_1
Found 1 keys to try after 0.5 seconds
The .kfx-zip archive does not contain an encrypted DRMION file
Decryption succeeded after 0.5 seconds
DeDRM v10.0.5: Finished after 0.5 seconds
Package KFX (from KFX Input) 2.1.0: Packaging /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/apz76563.kfx-zip
Processing container: Jumbo_ The Unauthorised Biography of a Vic - John Sutherland.kfx
Added Jumbo: The Unauthorised Biography of a Victorian Sensation to db in: 0.1
Added 1 books in 2.6 seconds
Features: CanonicalFormat-1, kfxgen.textBlock-1, max_id-696, reflow-style-2
Metadata: ASIN=B00INWLOBG, asset_id=CR!6FM16H1RDS5ZV1WRD5BCT9BZX9AJ, author="Sutherland, John", cde_content_type=EBOK, content_id=B00INWLOBG, cover_image=825x1329, creator_version=2.15.0, file_creator=YJConversionTools, is_sample=False, issue_date=2014-02-06, kfxgen="7.111.1.1/PackageVersion:YJReaderSDK-1.6.444.5 Month-Day:03-20", language=en, pages=306, publisher="Aurum Press Ltd", reading_orders=1, selection=enabled, title="Jumbo: The Unauthorised Biography of a Victorian Sensation"
KFX container created may be too large for some devices (22786925 bytes)
Package KFX (from KFX Input): Imported as /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/mrgky7xt.kfx
KFX metadata reader (from KFX Input) activated for /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/au03j2yy_add_books/0/Jumbo_ The Unauthorised Biography of a Vic - John Sutherland.kfx
Gather KFX-ZIP (from KFX Input) 2.1.0: Importing /Users/alexhorkay/Calibre Library/John Sutherland/Jumbo_ The Unauthorised Biography of a Victorian Sensation (327)/Jumbo_ The Unauthorised Biography of a Vic - John Sutherland.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/w0nml5to.kfx-zip
DeDRM v10.0.5: Trying to decrypt w0nml5to.kfx-zip
Decrypting KFX-ZIP ebook: w0nml5to
Got DSN key from database kindle_key_1688334415_1
Found 1 keys to try after 0.5 seconds
The .kfx-zip archive does not contain an encrypted DRMION file
Decryption succeeded after 0.5 seconds
DeDRM v10.0.5: Finished after 0.5 seconds
Package KFX (from KFX Input) 2.1.0: Packaging /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/wnqxs0_i.kfx-zip
Processing container: Jumbo_ The Unauthorised Biography of a Vic - John Sutherland.kfx
Added Jumbo: The Unauthorised Biography of a Victorian Sensation to db in: 0.1
Added 1 books in 92.1 seconds
Features: CanonicalFormat-1, kfxgen.textBlock-1, max_id-696, reflow-style-2
Metadata: ASIN=B00INWLOBG, asset_id=CR!6FM16H1RDS5ZV1WRD5BCT9BZX9AJ, author="Sutherland, John", cde_content_type=EBOK, content_id=B00INWLOBG, cover_image=825x1329, creator_version=2.15.0, file_creator=YJConversionTools, is_sample=False, issue_date=2014-02-06, kfxgen="7.111.1.1/PackageVersion:YJReaderSDK-1.6.444.5 Month-Day:03-20", language=en, pages=306, publisher="Aurum Press Ltd", reading_orders=1, selection=enabled, title="Jumbo: The Unauthorised Biography of a Victorian Sensation"
KFX container created may be too large for some devices (22786925 bytes)
Package KFX (from KFX Input): Imported as /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/4dnuwm8m.kfx
KFX metadata reader (from KFX Input) activated for /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/snbyexbx_add_books/0/Jumbo_ The Unauthorised Biography of a Vic - John Sutherland.kfx
Gather KFX-ZIP (from KFX Input) 2.1.0: Importing /Users/alexhorkay/Calibre Library/John Sutherland/Jumbo_ The Unauthorised Biography of a Victorian Sensation (326)/Jumbo_ The Unauthorised Biography of a Vic - John Sutherland.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/hb58584u.kfx-zip
DeDRM v10.0.5: Trying to decrypt hb58584u.kfx-zip
Decrypting KFX-ZIP ebook: hb58584u
Got DSN key from database kindle_key_1688334415_1
Found 1 keys to try after 0.5 seconds
The .kfx-zip archive does not contain an encrypted DRMION file
Decryption succeeded after 0.5 seconds
DeDRM v10.0.5: Finished after 0.5 seconds
Package KFX (from KFX Input) 2.1.0: Packaging /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/gyskfv4s.kfx-zip
Processing container: Jumbo_ The Unauthorised Biography of a Vic - John Sutherland.kfx
Added 0 books in 10.6 seconds
Features: CanonicalFormat-1, kfxgen.textBlock-1, max_id-696, reflow-style-2
Metadata: ASIN=B00INWLOBG, asset_id=CR!6FM16H1RDS5ZV1WRD5BCT9BZX9AJ, author="Sutherland, John", cde_content_type=EBOK, content_id=B00INWLOBG, cover_image=825x1329, creator_version=2.15.0, file_creator=YJConversionTools, is_sample=False, issue_date=2014-02-06, kfxgen="7.111.1.1/PackageVersion:YJReaderSDK-1.6.444.5 Month-Day:03-20", language=en, pages=306, publisher="Aurum Press Ltd", reading_orders=1, selection=enabled, title="Jumbo: The Unauthorised Biography of a Victorian Sensation"
KFX container created may be too large for some devices (22786925 bytes)
Package KFX (from KFX Input): Imported as /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/0ls3v3dt.kfx
KFX metadata reader (from KFX Input) activated for /var/folders/_0/rpk4fnpn17d_7h6mlv1tbv600000gn/C/calibre_6.22.0_tmp_03rlv1my/dqg3t7io_add_books/0/Jumbo_ The Unauthorised Biography of a Vic - John Sutherland.kfx

**Comment by ahorkay** [comment]
I should maybe have added that I don't have a Kindle (I use a Kobo ebook reader). And I forgot to attach two screen grabs that may help illustrate what I tried to say.
1. <img width="520" alt="Screenshot 2023-07-02 at 8 24 33 PM" src="https://github.com/noDRM/DeDRM_tools/assets/28722274/09b82ba2-c24b-4dc1-ba97-216a69be8d80">
2. <img width="493" alt="Screenshot 2023-07-02 at 8 55 32 PM" src="https://github.com/noDRM/DeDRM_tools/assets/28722274/6c83387a-5cbc-4ec3-8506-3e8385fb8905">

**Comment by ElleKayEm** [comment]
What extension does the book have in calibre?  Sounds like that extension is set to open with calibre itself, instead of the calibre ebook viewer.

For the second issue, try deleting the book from Kindle for Mac.  Then download using right-click on mouse and selecting "Download", or use menu bar "File > Download".  Don't open the book in Kindle for Mac or you'll get KCR again.

**Comment by ahorkay** [comment]
The book has a .kfx extension in Calibre.

Thanks for the second issue suggestion; I should have though tot try that.

**Comment by ElleKayEm** [comment]
Looks like it's successfully DeDRMed then.  It would show kfx-zip otherwise.  Re-associate that extension.  Or set KFX to open in the calibre viewer (Preferences > Behavior).  Or just try converting to epub if you want it for your Kobo.

**Comment by ahorkay** [comment]
That worked! Perfect, thanks for that... Issue 1 is solved.

Issue 2 is still a problem — deleting the books from Kindle for Mac and readding only readded the same .kcr, .spnx, .mbpV2 etc. files. I didn't reopen them at all. And on my older (High Sierra) laptop (with Calibre 3.48, Tools 10.0.5s, KFX Input 1.51 and Kindle 1.17.1) downloading does give me .azw files, but Calibre/Tools won't decrypt them. Should I go back and try an even older version or is there a better solution?

**Comment by ElleKayEm** [comment]
Kindle for Mac 1.17 doesn't download KFX files at all.  With that version of calibre, use DeDRM 6.8.1: https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1

DeDRM 10.x is intended to be backward compatible with older versions of calibre, but hasn't gotten much testing on those.  DeDRM 6.8.1 should be fine though with those versions of calibre and Kindle for Mac

**Comment by ahorkay** [comment]
That worked! Everything's happily planted on my Kobo reader now. Thanks again!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
