### ISSUE TITLE
Plugin doesn't work with .lcpl file on Mac OS Ventura 13.3.1.

### ISSUE THREAD

**Issue by MDR61** [noDRM/DeDRM_tools#363]
### Question / bug report

I added a .lcpl ebook to Calibre 6.22 but when I try to convert to MOBI Calibre reply this ebook has protection DRM.
What can I do ?

### Which version of Calibre are you running?

6.22

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

Kindle 10th generation Firmware version 5.15.1.1 (3925020005)

### Log output

```log
[tmpxeaqxduo.txt](https://github.com/noDRM/DeDRM_tools/files/11955894/tmpxeaqxduo.txt)

```

**Comment by ElleKayEm** [comment]
From the log:
> LCP: LCP DRM removal no longer supported due to a DMCA takedown request.

LCP: The takedown request can be found here: 
LCP: https://github.com/github/dmca/blob/master/2022/01/2022-01-04-readium.md 
LCP: More information can be found in the Github repository: 
LCP: https://github.com/noDRM/DeDRM_tools/issues/18

**Comment by MDR61** [comment]
OK, thanks a lot

Il giorno mer 5 lug 2023 alle ore 14:24 ElleKayEm ***@***.***>
ha scritto:

**Comment by ElleKayEm** [comment]
You can close the issue.
