### ISSUE TITLE
[Feature Request] Supporting Comixology?

### ISSUE THREAD

**Issue by rainrdx** [noDRM/DeDRM_tools#365]
### Question / bug report

Thanks noDRM and everyone for your work. Just want to submit a feature request. Comixology now uses the same backend as Kindle. A quick look at the android version seems to suggest that it uses the same KFX files to serve comics. But it uses a different form of key database (map_data_storage_v2.db). The key database uses an encryption key to encrypt the serial number, etc. It seems that audible for android uses the same system but can't find any reference on how the encryption process works. Again just throwing it out there and thank you for looking at this.

### Which version of Calibre are you running?

6.22

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
You can get the key from an older version of Kindle for Android.  Then if you update in place so that your key remains the same, you can get higher res images.  The current release of DeDRM 10.0.3 doesn't support the latest KFX DRM, but the master code does.  Don't know if anyone has tried that with kfx from Kindle for Android yet.

See this post: https://www.mobileread.com/forums/showthread.php?t=352278

I have no suggestions for Audible.

**Comment by rainrdx** [comment]
> You can get the key from an older version of Kindle for Android. Then if you update in place so that your key remains the same, you can get higher res images. The current release of DeDRM 10.0.3 doesn't support the latest KFX DRM, but the master code does. Don't know if anyone has tried that with kfx from Kindle for Android yet.
> 
> See this post: https://www.mobileread.com/forums/showthread.php?t=352278
> 
> I have no suggestions for Audible.

Thank you for thinking about this. The master code works for the most recent Kindle for Android. However, I am referring to Comixology for Android, which is a different app with likely shared backbone as Kindle for Android, and seems to have encrypted the sqlite file with a different method. Comixology has HD resolutions for comics I purchased. The Kindle for Android version does not seem to have the highest resolution despite efforts to use the most recent version.

**Comment by ElleKayEm** [comment]
Ah, didn't realize comixology had it's own app now that it's folded into Amazon.

**Comment by jak9od3** [comment]
if your looking for an audible decrypter try [Libation](https://github.com/rmcrackan/Libation)

**Comment by rainrdx** [comment]
> if your looking for an audible decrypter try [Libation](https://github.com/rmcrackan/Libation)

Thank you I am not looking for an audible decrypter. I just meant that audible for android and comixology for android seem to use the same sqlite file format and people online have offered some decryption app for audible for android that implements such a sqlite file decrypter. But I can't find an open source implementation. Just referring to this if anyone is interested in working on this. Still thank you.

**Comment by Satsuoni** [comment]
A brief look at the apk code seems to show that key generation has changed to be random, and key is at least stored in EncryptedSharedPreferences of the app, but may be stored in db itself as well. Unfortunately, I do not have working  Android device or Comixology account, so there is no way for me to test anything _shrug_.  EncryptedSharedPreferences can be extracted using hooks or emulator, I assume... 

Check if there is "encryption_data" table in the db and what it looks like, I guess.

**Comment by rainrdx** [comment]
> A brief look at the apk code seems to show that key generation has changed to be random, and key is at least stored in EncryptedSharedPreferences of the app, but may be stored in db itself as well. Unfortunately, I do not have working Android device or Comixology account, so there is no way for me to test anything _shrug_. EncryptedSharedPreferences can be extracted using hooks or emulator, I assume...
> 
> Check if there is "encryption_data" table in the db and what it looks like, I guess.

Satsuoni, thank you for even looking. Yes there is an encryption_data table with key. I extracted the keys from my WSA. Comixology account is the same as amazon account now. But again already thank you for spending time already.

**Comment by j-howell** [comment]
> Comixology has HD resolutions for comics I purchased. The Kindle for Android version does not seem to have the highest resolution despite efforts to use the most recent version.

I am curious to know of a specific comic that is delivered in higher quality to the Comixology app than to the Kindle for Android app. In the limited testing I have done the same set of files was delivered to either app.

**Comment by rainrdx** [comment]
> > Comixology has HD resolutions for comics I purchased. The Kindle for Android version does not seem to have the highest resolution despite efforts to use the most recent version.
> 
> I am curious to know of a specific comic that is delivered in higher quality to the Comixology app than to the Kindle for Android app. In the limited testing I have done the same set of files was delivered to either app.

Thank you for checking into this.

I dont have any way to check the resolution of the new comixology. But to use this series (https://www.amazon.com/gp/product/B07JJMSBNS) as an example, the old comixology gives me up to 2130*3056 resolution. But the kindle for android gives me 1812*2600.

Not a significant difference. But if it turns out the new comixology just serves the same files as the kindle for android, then the point is moot. Thank you and everyone for looking into this.

**Comment by j-howell** [comment]
> I dont have any way to check the resolution of the new comixology. But to use this series (https://www.amazon.com/gp/product/B07JJMSBNS) as an example, the old comixology gives me up to 2130 * 3056 resolution. But the kindle for android gives me 1812 * 2600.

I was curious so I did a test using volume 17 of that series. I downloaded it using the latest versions of Kindle for Android (8.81.1.0) and Comics & Manga by Comixology (4.0.10) on a Samsung tablet. The set of files downloaded were identical except for the DRM voucher. Image resolution was 1898 x 2723 pixels.

**Comment by rainrdx** [comment]
> > I dont have any way to check the resolution of the new comixology. But to use this series (https://www.amazon.com/gp/product/B07JJMSBNS) as an example, the old comixology gives me up to 2130 * 3056 resolution. But the kindle for android gives me 1812 * 2600.
> 
> I was curious so I did a test using volume 17 of that series. I downloaded it using the latest versions of Kindle for Android (8.81.1.0) and Comics & Manga by Comixology (4.0.10) on a Samsung tablet. The set of files downloaded were identical except for the DRM voucher. Image resolution was 1898 x 2723 pixels.

Ah thank you! Why didn’t I check the file sizes. Well on that thank you! I will close this then.
