### ISSUE TITLE
Cannot install: The plugin in '/tmp/DeDRM_tools_10.0.2.zip' is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by flbjerke** [noDRM/DeDRM_tools#37]
### Question / bug report

calibre, version 5.4.2
FEJL: Uhåndteret undtagelse: <b>InvalidPlugin</b>:The plugin in '/tmp/DeDRM_tools_10.0.2.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.4.2  embedded-python: True is64bit: True
Linux-5.4.0-96-lowlatency-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-96-lowlatency', '#109-Ubuntu SMP PREEMPT Wed Jan 12 17:51:01 UTC 2022')
Python 3.8.5
Interface language: da
Successfully initialized third party plugins: KindleUnpack - The Plugin (0, 75, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 276, in load
  File "calibre/customize/zipplugin.py", line 371, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/tmp/DeDRM_tools_10.0.2.zip' is invalid. It does not contain a top-level __init__.py file

### Which version of Calibre are you running?

5.4.2

### Which version of the DeDRM plugin are you running?

not running

### Log output

```log
......
```

**Comment by LaHaine** [comment]
It is in the README, you must unzip DeDRM_tools_10.0.2.zip and load included zip file into calibre.

**Comment by flbjerke** [comment]
Thank you. I missed there are zip-files in the zip-file.
