### ISSUE TITLE
issue converting libby file to non drm epub

### ISSUE THREAD

**Issue by zatehlun** [noDRM/DeDRM_tools#394]
Hi, newbie to Calibre/deDRM

I downloaded a acsm file from Libby and converted it to epub through ADE. Now I'm trying to remove DRM using deDRM in order to send to Kindle. I have installed the 10.0.9 deDRM and am using Calibre 6.25. I have installed deDRM and imported the epub to Calibre. But everytime I send the new epub to my Kindle, the upload fails. Please let me know what I'm doing wrong? Thanks!

**Comment by ElleKayEm** [comment]
Can you read the epub with calibre's ebook viewer?  If so, the DRM is removed and send-to-Kindle is the issue.

**Comment by zatehlun** [comment]
Thanks for your quick reply! I realized that it was because I had opened the original acsm file with my original AdobeID (thus fulfilling it). But I wanted to change the AdobeID and so deauthorized the AdobeID and tried to use a new AdobeID. Because of that the deDRM plugin could not work. But using a new acsm file with the new AdobeID, the deDRM plugin worked like a charm. Thank you so much
