### ISSUE TITLE
 No decryption on an AZW3 file just downloaded to PC when  opened with Calibre

### ISSUE THREAD

**Issue by rlsmith46** [noDRM/DeDRM_tools#399]
### Question / bug report

**_The file was inserted in the Library with no error message, however when I attempt to view it in Calibre, it informs me that it still has DRM and can't be viewed.
It opens properly in my Kindle for PC software, however._**

### Which version of Calibre are you running?
6.26

### Which version of the DeDRM plugin are you running?
v.10.0.9

### If applicable, which version of the Kindle software are you running?
Kindle for PC  latest version

### Log output

Microsoft Windows [Version 10.0.19045.3448]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Susanne>calibre-debug -g
calibre 6.26  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 73.06067415730337 x 73.15199999999999
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[1.27] main UI initialized...
[1.27] Hiding splash screen
Starting QuickView
[2.22] splash screen hidden
[2.22] Started up in 2.22 seconds with 47 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe7>\x97\xe0_j\x98\xfd\xac\xaa\x96\xcbc\xe6\xa9~V\xb5\x8eKRcc\x1c\xa9\xacX\x8d\xa9\x81\xdb\x0f', b"D:\\All Larrys Stuff\\Kindle\\Downloaded books\\Susanne's Kindle\\White Trash.azw3"]
DeDRM v10.0.9: Trying to decrypt White Trash.azw3
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: White Trash
Got DSN key from database default_key-Sue-0
Found 4 keys to try after 1.0 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 4 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 1.0 seconds
searching for kinfoFiles in C:\Users\Susanne\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Susanne\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\Susanne\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4209357491' and UserName 'Susanne'
Decrypted key file using IDString '4209357491' and UserName 'Susanne'
DeDRM v10.0.9: Found 2 new keys
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: White Trash
Got DSN key from database key_0
Got DSN key from database key_1
Found 4 keys to try after 1.2 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Susanne\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\Susanne\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\Susanne\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\Susanne\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.9: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Susanne\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\Susanne\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added White Trash to db in: 0.1
Added 1 books in 1.8 seconds

**Comment by ElleKayEm** [comment]
Is this from or for an E-ink Kindle?  Looks like you don't have the Kindle's serial number entered in DeDRM's customization.

**Comment by rlsmith46** [comment]
I own an e-ink kindle, but I downloaded this AZW3 file for the PC  I will
insert my e-ink kindle ID and let you know the result.

Thanks for tor the quick response.

**Comment by rlsmith46** [comment]
Thanks  That solved the problem nicely..  I bought the item from an  Amazon
account associated with an E-Ink reader.  I didn't realize that if I
downloaded it to my PC, it would carry the linkage to the E-ink's serial
number.

Not only did you quickly resolve my problem, but I learned something new.—
which make for a great day.

Thank you very much.

I will close out the issue on the blog shortly.
Larry Smith

**Comment by ElleKayEm** [comment]
When downloading from the website, you have to choose a device (a PC isn't an option).  You must have chosen that Kindle.  Maybe it's the only one you have tied to that account.

**Comment by rlsmith46** [comment]
Thanks for the tip! yes, it is the only one on that account
