### ISSUE TITLE
DeDRM v10.0.3 fails on magazine from eInk Kindle

### ISSUE THREAD

**Issue by dhdurgee** [noDRM/DeDRM_tools#409]
I am looking to backup the magazines from my Kindle given Amazon's latest changes to their magazine policy.  I connected my Kindle via USB and copied a magazine over.  When I attempted to import it into Calibre the DRM is not removed.  I have no problems using Amazon's "Download via USB" option on my books, but magazines don't seem to be available.

[DeDRM_Log.txt](https://github.com/noDRM/DeDRM_tools/files/12795443/DeDRM_Log.txt)

**Comment by ElleKayEm** [comment]
Is it an E-ink Kindle?  In other words, not a Fire?  If so, you need to enter that Kindle's serial number into DeDRM's customization.  My old magazine subscription has a download & transfer via usb option for past issues.  Magazines are listed seperately from books.  Don't know if it's different if you only bought single issues.  IIRC, these don't convert very well to other formats.

**Comment by dhdurgee** [comment]
Opps!  Somehow missed this Kindle serial.  That fixed it.  Closing issue.
