### ISSUE TITLE
DRM not working

### ISSUE THREAD

**Issue by costrone** [noDRM/DeDRM_tools#417]
I got the log below. Thank you so much in advance for your help.

Using calibre Qt style: True
calibre Registro de depuración
calibre 6.29  embedded-python: True
macOS-12.6.8-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Thu Jul  6 22:18:26 PDT 2023; root:xnu-8020.240.18.702.13~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6.8', ('', '', ''), 'x86_64')
Interface language: es
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
calibre 6.29  embedded-python: True
macOS-12.6.8-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Thu Jul  6 22:18:26 PDT 2023; root:xnu-8020.240.18.702.13~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6.8', ('', '', ''), 'x86_64')
Interface language: es
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 128.00000192236715
[0.00] Starting up...
[0.03] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[1.13] main UI initialized...
[1.13] Hiding splash screen
Starting QuickView
DeDRM v10.0.9: Trying to decrypt Cronicas del Silo (pack) - Hugh Howey.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Cronicas del Silo (pack) - Hugh Howey.epub is a secure Adobe Adept ePub for UUID acca4ff2-f8a9-41e0-aa04-9ca92cf3b5a6
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 565, in ePubDecrypt
    defaultkeys, defaultnames = adeptkeys()
  File "/Users/iou/Library/Preferences/calibre/plugins/DeDRM.zip/adobekey.py", line 385, in adeptkeys
    raise ADEPTError("Could not find ADE activation.dat file.")
adobekey.ADEPTError: Could not find ADE activation.dat file.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[10.11] splash screen hidden
[10.11] Started up in 10.11 seconds with 5 books
Added Crónicas del Silo (pack) to db in: 0.0
Added 1 books in 1.2 seconds

**Comment by ElleKayEm** [comment]
DeDRM can't find your Adobe key.  Was this downloaded with ADE on the same machine and user where calibre/DeDRM is installed?

**Comment by costrone** [comment]
That was the problem. I downloaded the epub file on another computer and then sent it to my email. I was using Calibre in a different machine. I used ADE again to download the book and now DeDRM worked porperly.

Thank you so much!
