### ISSUE TITLE
Success Report

### ISSUE THREAD

**Issue by isotopp** [noDRM/DeDRM_tools#425]
### Question / bug report

I was using DeDRM 10.0.3, but that became unworkable (only "Download for USB" was still working).

Upgraded to NoDRM 10.0.9 – that is a drop-in-replacement, and it works flawlessly from Kindle for Mac for all things I tried, including all the stuff that previously did not work.

MacOS 14.1, Calibre 6.9, Kindle 1.40.1 (65626)

### Which version of Calibre are you running?

6.9

### Which version of the DeDRM plugin are you running?

V10.0.9

### If applicable, which version of the Kindle software are you running?

1.40.1

### Log output

Success!

**Comment by ElleKayEm** [comment]
If you're all set, you can close this issue.

**Comment by isotopp** [comment]
Yes, thanks for all the past support in any case.
