### ISSUE TITLE
dedrm not removing drm

### ISSUE THREAD

**Issue by Truenntaya** [noDRM/DeDRM_tools#431]
### Question / bug report

I am on a laptop using the windows kindle app. I've got the plugin and the kfx input and output plugins, but calibre still can't read the books I add. It's as if the plugin wasn't there. I tried 10.0.3 first but I got the same results. I'm getting:

calibre, version 6.29.0
ERROR: No associated program: Windows will try to open Girls' Last Tour Vol. 2 - Tsukumizu.kfx with calibre itself resulting in a duplicate in your calibre library. You should install some program capable of viewing this file format and tell Windows to use that program to open files of this type.

### Which version of Calibre are you running?

6.29

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

2.2.0

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
In calibre go to Preferences > Behavior and check the box next to kfx in the righthand list for "use internal viewer".

**Comment by Truenntaya** [comment]
That worked to get me to the reader, but it isn't working. Here's what the log says:

`calibre, version 6.29.0
ERROR: Loading book failed: Failed to open the book at C:\Users\Name\Calibre Library\Tsukumizu\Girls' Last Tour Vol. 2 (14)\Girls' Last Tour Vol. 2 - Tsukumizu.kfx. Click "Show details" for more info.

Failed to convert book: C:\Users\Name\Calibre Library\Tsukumizu\Girls' Last Tour Vol. 2 (14)\Girls' Last Tour Vol. 2 - Tsukumizu.kfx with error:
KFX metadata reader (from KFX Input) activated for C:\Users\Name\Calibre Library\Tsukumizu\Girls' Last Tour Vol. 2 (14)\Girls' Last Tour Vol. 2 - Tsukumizu.kfx
DeDRM v10.0.9: Trying to decrypt Girls' Last Tour Vol. 2 - Tsukumizu.kfx
Unknown booktype kfx. Passing back to calibre unchanged
InputFormatPlugin: KFX Input running
on C:\Users\Name\Calibre Library\Tsukumizu\Girls' Last Tour Vol. 2 (14)\Girls' Last Tour Vol. 2 - Tsukumizu.kfx
Software versions: KFX Input 2.5.0, calibre 6.29, Windows-10-10.0.19045-SP0
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\Name\Calibre Library\Tsukumizu\Girls' Last Tour Vol. 2 (14)\Girls' Last Tour Vol. 2 - Tsukumizu.kfx
Processing container: C:\Users\Name\Calibre Library\Tsukumizu\Girls' Last Tour Vol. 2 (14)\Girls' Last Tour Vol. 2 - Tsukumizu.kfx
Features: CanonicalFormat-2, max_id-755, yj_double_page_spread-1, yj_jpg_rst_marker_present-1, yj_non_pdf_fixed_layout-2, yj_thumbnails_present-1
Metadata: ASIN=B01MSCQWH5, asset_id=CR!BADZT9P43D7PHF61YXAZE8VMPSM8, author=", Tsukumizu", book_id=sTc42ENIRAa2-nUp_24BTg1, cde_content_type=EBOK, content_id=B01MSCQWH5, continuous_popup_progression=0, cover_image=900x1291, creator_version=2.15.0, description=..., file_creator=YJConversionTools, is_sample=False, issue_date=2017-08-22, kfxgen=7.174.1.0, language=en, publisher="Yen Press", reading_orders=1, title="Girls' Last Tour Vol. 2", yj_double_page_spread=1, yj_fixed_layout=1
ERROR: This book has a layout that is incompatible with calibre conversion. For best results use the KFX Input plugin CLI for conversion.
Converting book to EPUB 3
Book symbol format is base64
Format is fixed layout comic
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 115, in convert
Exception: This book has a layout that is incompatible with calibre conversion. For best results use the KFX Input plugin CLI for conversion.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 941, in viewer_main
  File "calibre\srv\render_book.py", line 932, in render_for_viewer
  File "calibre\srv\render_book.py", line 909, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 62, in extract_book
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre_plugins.kfx_input.__init__", line 126, in convert
calibre.ebooks.conversion.ConversionUserFeedBack: {"msg": "<b>Cannot convert ?</b><br><br>Exception('This book has a layout that is incompatible with calibre conversion. For best results use the KFX Input plugin CLI for conversion.')", "level": "error", "det_msg": "", "title": "KFX conversion failed"}`

**Comment by ElleKayEm** [comment]
Looks like DRM is already removed.

But as it says, "This book has a layout that is incompatible with calibre conversion. For best results use the KFX Input plugin CLI for conversion."

See this post and scroll down to Command Line Interface and unhide the info there: https://www.mobileread.com/forums/showthread.php?t=291290

If you have issues with it, that post is the place to get help.

Honestly, you'd probably be better off using one of the methods to get this in non-kfx format if possible.

**Comment by Truenntaya** [comment]
Alright, thanks!
