### ISSUE TITLE
DeDRM 10.0.9 not removing DRM from kindle 1.17 running in wine

### ISSUE THREAD

**Issue by steinarb** [noDRM/DeDRM_tools#444]
### Question / bug report

Conversion from AZW3 to EPUB fails with:
```
Cannot convert

This book is locked by DRM. To learn more about DRM and why you cannot read or convert this book in calibre.
```

I think this may be caused by DeDRM not finding the kindle key in the wine-installed kindle?

There is something that looks like a key in /home/sb/.wine/drive_c/users/sb/AppData/Local/Amazon/Kindle/storage/.kinf2011 but I haven't been able to make DeDRM pick it up.

The KFX plugin is version 2.6.0

### Which version of Calibre are you running?

7.1.0

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

1.17.44170 running under wine 8 on debian 12

### Log output

```log
Using calibre Qt style: True
calibre Debug log
calibre 7.1  embedded-python: True
Linux-6.1.0-13-amd64-x86_64-with-glibc2.36 Linux ('64bit', 'ELF')
('Linux', '6.1.0-13-amd64', '#1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29)')
Python 3.11.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 6, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 6, 0) && KFX metadata reader (from KFX Input) (2, 6, 0) && KFX Input (2, 6, 0) && OPDS Client (1, 0, 0)
calibre 7.1  embedded-python: True
Linux-6.1.0-13-amd64-x86_64-with-glibc2.36 Linux ('64bit', 'ELF')
('Linux', '6.1.0-13-amd64', '#1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29)')
Python 3.11.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 6, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 6, 0) && KFX metadata reader (from KFX Input) (2, 6, 0) && KFX Input (2, 6, 0) && OPDS Client (1, 0, 0)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 141.4020618556701
[0.00] Starting up...
[0.00] Showing splash screen...
[0.05] splash screen shown
[0.05] Initializing db...
[0.10] db initialized
[0.10] Constructing main UI...
[0.60] main UI initialized...
[0.60] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 2.6.0: Importing /home/sb/Documents/My Kindle Content/B084DCVBQY_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v10.0.9: Trying to decrypt B084DCVBQY_EBOK.azw
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Broken Genius: 1
Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.4 seconds
[36.71] splash screen hidden
[36.71] Started up in 36.71 seconds with 780 books
['zenity', '--modal', '--file-selection', '--title=Select books', '--separator=\n', '--attach=85983256', '--filename=/home/sb/Documents/My Kindle Content/.fgdfg.gdfhjdhf*&^839', '--file-filter=Books | *.lrf *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf *.kfx-zip *.azw8', '--file-filter=EPUB books | *.epub *.kepub', '--file-filter=Kindle books | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=PDF books | *.pdf *.azw4', '--file-filter=HTML books | *.htm *.html *.xhtm *.xhtml', '--file-filter=LIT books | *.lit', '--file-filter=Text books | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Comics | *.cbz *.cbr *.cbc *.cb7', '--file-filter=Archives | *.zip *.rar *.7z', '--file-filter=Wordprocessor files | *.odt *.doc *.docx', '--file-filter=All files | *', '--multiple']
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.9: wine py.exe -3 is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.9: wine python3.exe is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.9: wine python.exe is not python3
wine: failed to open "C:\\Python27\\python.exe": c0000135
DeDRM v10.0.9: wine C:\Python27\python.exe does not exist
DeDRM v10.0.9: Unable to find python3 executable in WINEPREFIX=""
DeDRM v10.0.9: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sb/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/sb/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Broken Genius: 1 to db in: 0.0
Added 1 books in 2.0 seconds
Worker Launch took: 0.01 seconds
Job: 0 Convert book 1 of 1 (Broken Genius: 1) finished
Convert book 1 of 1 (Broken Genius: 1)
	DeDRM v10.0.9: Trying to decrypt ts6upd3b.azw
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Broken Genius: 1
	Found 0 keys to try after 0.4 seconds
	Crypto Type is: 2
	DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.4 seconds
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.9: wine py.exe -3 is not python3
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.9: wine python3.exe is not python3
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.9: wine python.exe is not python3
	wine: failed to open "C:\\Python27\\python.exe": c0000135
	DeDRM v10.0.9: wine C:\Python27\python.exe does not exist
	DeDRM v10.0.9: Unable to find python3 executable in WINEPREFIX=""
	DeDRM v10.0.9: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/sb/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/home/sb/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	mobidedrm.DrmException: No key found in 0 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  cover: '/tmp/calibre_7.1.0_tmp_kavxeid1/7025kcxu.jpeg'
	  output_profile: 'sony'
	  read_metadata_from_opf: '/tmp/calibre_7.1.0_tmp_kavxeid1/eo66r698.opf'
	  verbose: 2
	Resolved conversion options
	calibre version: 7.1.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/tmp/calibre_7.1.0_tmp_kavxeid1/7025kcxu.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_max_image_size': 'none',
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f1c63025150>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.SonyReaderOutput object at 0x7f1c6303b9d0>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/tmp/calibre_7.1.0_tmp_kavxeid1/eo66r698.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v10.0.9: Trying to decrypt ts6upd3b.azw
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Broken Genius: 1
	Found 0 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.0 seconds
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.9: wine py.exe -3 is not python3
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.9: wine python3.exe is not python3
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.9: wine python.exe is not python3
	wine: failed to open "C:\\Python27\\python.exe": c0000135
	DeDRM v10.0.9: wine C:\Python27\python.exe does not exist
	DeDRM v10.0.9: Unable to find python3 executable in WINEPREFIX=""
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/sb/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/home/sb/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	mobidedrm.DrmException: No key found in 0 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on /tmp/calibre_7.1.0_tmp_kavxeid1/ts6upd3b.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 198, in _run_module_as_main
	  File "runpy.py", line 88, in _run_code
	  File "site.py", line 47, in <module>
	  File "site.py", line 43, in main
	  File "calibre/utils/ipc/worker.py", line 215, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
	  File "calibre/customize/conversion.py", line 242, in __call__
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	  File "calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
	calibre.ebooks.DRMError: Broken Genius: 1
```

**Comment by steinarb** [comment]
The calibre 7.1 msi is 64bit which is a possible problem?

Last time I tried this, was a year ago using was debian 11 "bullseye which had wine 5 (I'm now using debian 12.2 with wine 8) and wine and wine64 was two separate entities with two separate wine directories created in the home directory (~/.wine and ~/.wine64) which meant that a 64 bit calibre wouldn't have found settings made by a 32 bit kindle.

But with wine 8 32bit and 64bit seems to have been unified... maybe...? The docs are a bit hard to read.

In any case nothing happens when I try running
```
wine /tmp/calibre-64bit-7.1.0.msi 
```
I.e. no output to the console and no installer opening and starting and no application added to the wine debian applications menu.

First time I tried I didn't have wine64 installed.

So I did
```
apt install wine64
```

And tried the same command again ("wine /tmp/calibre-64bit-7.1.0.msi") but again nothing happened.

**Comment by steinarb** [comment]
If the problem is just reading the file inside wine, isn't a simple fix to just make it possible do read any files in the dialog "Select Kindle for Mac and PC Key files to import"?

The dialog is locked in file type "Kindle for Mac and PC Key files".

**Comment by ElleKayEm** [comment]
In the log, the Linux setup isn't finding Python installed under wine in order to run the key script there.  If you can get an older Windows calibre installed under wine, then DeDRM can use calibre's built-in Python to get the key.

**Comment by ElleKayEm** [comment]
Yes, you'd need DeDRM loaded in Windows calibre to retrieve the key that way.

For the Linux calibre/DeDRM to retrieve the key, you do need Python and Pycrytodome installed under wine.  But I think there may still be issues.  You could try it.

**Comment by steinarb** [comment]
I have now installed python 3.8.6 32 bits from here in wine: https://www.python.org/downloads/windows/
(3.8.6 is the last version that doesn't say "cannot be used on Windows 7 or earlier", and I found [this google hit indicating that wine is windows 7](https://forum.winehq.org/viewtopic.php?p=137814&sid=bb755bac8fa5091a7eb7c59d3bed848b#p137814) (with a workaround, but still)).

[However calibre (on linux) still says "wine py.exe -3" isn't python 3](https://gist.github.com/steinarb/de362aa8b61d6be2c7418879abcc26d5#file-gistfile1-txt-L47).

But running "wine py.exe -3" from the command line, gives me this output:
```
sb@marquez:~$ wine py.exe -3
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:37:30) [MSC v.1927 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
sb@marquez:~$
```

**Comment by ElleKayEm** [comment]
Yeah, I believe there are still issues with that part of the code for retrieving the key from the Linux side.

If wine is Windows 7, try Windows calibre 3.48: https://download.calibre-ebook.com/3.48.0/

DeDRM 10.0.9 is suppose to work with earlier versions of calibre.  But if it doesn't, DeDRM 6.8.1 will: https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1

**Comment by steinarb** [comment]
I'm trying the "install python3 in wine" track a little more before I try installing a calibre in wine.

I cloned DeDRM_tools and looked at the code in wineutils.py and decoded the full command sent to subprocess.check_call() and the response looked OK:
```
b@marquez:~$ wine py.exe -3 -c "import sys; sys.exit(0 if (sys.version_info.major==3) else 1)"
sb@marquez:~$ echo $?
0
sb@marquez:~$
```

So why does this fail when DeDRM wineutils is doing it?

**Comment by steinarb** [comment]
But to clarify: the installation of calibre with DeDRM in wine isn't to run from inside wine?

Installing calibre w/DeDRM is so that DeDRM in calibre in linux can find python and pycrytodome inside wine?

(Because the version of calibre listed is too old to handle KFX files, and the DeDRM version is way to old to handle anything at all...?)

**Comment by ElleKayEm** [comment]
Installing Windows calibre with DeDRM temporarily under Wine for the sole purpose of retrieving your keys is a workaround to avoid needing to install Python and Pycryptodome in Wine.  Once the Windows calibre/DeDRM has your key, you save the key from DeDRM customization, and import it manually into the Linux calibre DeDRM customization.  After that, you'll be able to decrypt any books downloaded with that installation of Kindle for PC in the Linux calibre/DeRM and you can forget about the Windows calibre/DeDRM (unless you need to retrieve keys again).  As for KFX format, Kindle for PC 1.17 does not download KFX format.  That format didn't show up in that app until the following version.  It also won't download any books published since 3 Jan 2023.

**Comment by steinarb** [comment]
>>>>> ElleKayEm ***@***.***>:

> Installing Windows calibre with DeDRM temporarily under Wine for the sole purpose of retrieving your keys is a workaround to avoid needing to install Python and Pycryptodome in Wine.  Once the Windows calibre/DeDRM has your key, you save the key from DeDRM customization, and import it manually into the Linux calibre DeDRM customization.

Ah, ok! Procedure for key export from wine calibre and import into linux calibre understood!

> After that, you'll be able to decrypt any books downloaded with that installation of Kindle for PC in the Linux calibre/DeRM and you can forget about the Windows calibre/DeDRM (unless you need to retrieve keys again). 

Understood!

> As for KFX format, Kindle for PC 1.17 does not download KFX format.  That format didn't show up in that app until the following version.

Ah, OK. I kinda knew that.  That was why I stuck with 1.17 in the first place.  

(It was just that because decrypt started failing I thought that it was using KFX anyway, but probably not.)

> It also won't download any books published since 3 Jan 2023.

Yes, there is that as well...

Right now, 1.17 was the newest version that I've been able to install in wine.

I have been able to install and start newer versions but they all crash after a little while.

1.17 is the newest one that doesn't crash.

**Comment by throwawayli** [comment]
Sadly, I also couldn't get this to work *at all*. There seem to be multiple major problems, as great as this plugin otherwise is (and thanks for making it!):

1. First of all, the readme mentions *nothing* of this process, and it really doesn't. It should state that a wine prefix is required at all, that it needs to be the wineprefix adobe digital editions installed is also in, *which* python version needs to be installed and *how (user-wide, just for one user, ...) and what pycrypto version, I assume pycryptodomex?

2. The UI also mentions *almost nothing* of what is going on. It should at the very least indicate that something is happening once I enter a wine prefix path, ideally whether 1. the path was found at all, 2. the path was found to be a wine prefix, 3. the python and adobe digital editions installs were found inside as expected, 4. whether a key extract was attempted, and 5. whether it failed or succeeded. All of this could be displayed with a simple one line label field added below the wine path that gives at least some single line status message about what the whole process is stuck at right now, that would help a lot.

I hope some of these suggestions help. I currently don't have a windows VM working, so I'm left stuck it seems like, so I wanted to give some feedback how the situation might maybe resolve in the medium term with more people also giving you more useful feedback what may not be working. (Since right now, with what the UI gives away, it's impossible to report back anything about what's going on since the UI doesn't seem to say.)

**Comment by steinarb** [comment]
Ok, success using kindle-in-wine in debian 12.3, albeit only for kindle 1.17, which cannot download books published after january 3 2023.

Here is what I did:

1. [Downloaded windows 32bit calibre 3.48.0](https://download.calibre-ebook.com/3.48.0/)
2. Installed the calibre msi in wine
     ```
     wine ~/Downloads/calibre-3.48.0.msi
     ```
3. [Downloaded DeDRM 6.8.1](https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1)
4. Unpacked the DeDRM_6.8.1.zip and installed DeDRM_Plugin.zip in wine calibre and restarted wine calibre
5. Opened the DeDRM plugin config in calibre: 
    1. Preferences->Plugins
    2. search for plugin
         ```
         dedrm
         ```
    3. Select "DeDRM (6.8.0)"
    4. Click on button "Customize plugin"
    5. Click on "Kindle for Mac/PC ebooks"
    6. Click on the button with the green "+"
    7. Click on "OK" in the dialog that appears
    8. Select the "default_key"
    9. Click on the floppy disk button and save default_key.k4i somewhere
 6. Import key.k4i in the DeDRM plugin running natively in debian

After this calibre in debian can import and convert files downloaded by wine kindle 1.17.

Whether it will actually be used for anything is doubtful.
I have stopped buying ebooks on amazon intended for my Sony reader.

I figure if booksellers won't sell me epubs, prefeably without DRM, they don't want me as a customer.

And there's always dead trees. Much good to be said for dead trees.

**Comment by ElleKayEm** [comment]
Some time ago there were Linux instructions in the Readme or somewhere which got increasingly painfully out-of-date.  (Back before noDRM, maybe before Apprentice Harper's GitHub repo, when we just had Apprentice Alf's blog.)  At some point those instructions were replaced with something basically saying it may work but you were on your own.  Apparently even that is gone now.

**Comment by throwawayli** [comment]
@steinarb maybe it would be worth leaving this open until it also works in the latest version?

Also, does this mean calibre also needs to run in wine for this to work? That wasn't quite clear to me so far.

**Comment by ElleKayEm** [comment]
Running Windows calibre/DeDRM in wine is a workaround to retrieve the key because of the issue with getting Linux calibre/DeDRM to do so.

**Comment by ElleKayEm** [comment]
Also are you able to get the current Kindle for PC (2.2?) to run under Wine?  Or are you using another method to download books?

**Comment by steinarb** [comment]
If the question was to me, then nope. 

That is: kindle 2.2 installs and starts but crashes after a little while before it is possible to do anything useful with it.
Kindle on wine hasn't seen much love for a while it looks like: https://appdb.winehq.org/objectManager.php?sClass=application&iId=10597

1.38 there, which is supposedly "gold" crashes for me in the same way 2.2 crashes.

**Comment by ElleKayEm** [comment]
That's what I thought.  Just wondering if @throwawayli was getting the books another way.  As far as I know, retrieving the key out of wine is the only issue with Linux.  Actually decrypting books should be okay.

**Comment by throwawayli** [comment]
Yeah, I'm using Adobe Digital Editions. latest version of that works fine. But the whole key access part via the wine prefix just doesn't work at all, with latest DeDRM and latest stable Calibre.

**Comment by ElleKayEm** [comment]
Ok, yeah, that's the issue.  You may be able to use the same workaround to retrieve the Adobe key as discussed above.
