### ISSUE TITLE
Adobe Digital Editions 4.5.12.112, DeDRM 10.0.8, Calibre x64 7.1.0 - Authorisation changed, books stopped decrypting.

### ISSUE THREAD

**Issue by JunglePredator** [noDRM/DeDRM_tools#454]
Hi,

I changed my username on my computer & Adobe Digital Editions 4.5 got deauthorised. I had to set up a new Adobe ID as it wouldn't let me use the old one & restarted the computer. Then I downloaded an epub from my library to decrypt it so it'll work on my older Kobo.

The epub failed to decrypt so I then updated both Calibre & DeDRM.

However the epub is still failing to have its DRM removed.

I'm using Adobe Digital Editions 4.5 as it used to be, and I haven't checked in a few years since everything had been working, the newest one that would work with my library's downloads. (Newer versions wouldn't open their books.)

The UUID in the log is correct: UUID fe30fff1-6961-45b7-979b-4dbee68e4998

Not sure what else to check & your FAQ indicated I should try a new issue post.

Log:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 1, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 1, 0) && Count Pages (1, 13, 0) && Extract ISBN (1, 6, 0) && Find Duplicates (1, 10, 8) && Generate Cover (2, 3, 2) && Goodreads (1, 7, 9) && Goodreads Sync (1, 16, 3) && KFX metadata reader (from KFX Input) (2, 1, 0) && KFX Input (2, 1, 0) && Manage Series (1, 5, 1) && Modify ePub (1, 8, 1) && Obok DeDRM (10, 0, 9) && Quality Check (1, 13, 4)
calibre 7.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 1, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 1, 0) && Count Pages (1, 13, 0) && Extract ISBN (1, 6, 0) && Find Duplicates (1, 10, 8) && Generate Cover (2, 3, 2) && Goodreads (1, 7, 9) && Goodreads Sync (1, 16, 3) && KFX metadata reader (from KFX Input) (2, 1, 0) && KFX Input (2, 1, 0) && Manage Series (1, 5, 1) && Modify ePub (1, 8, 1) && Obok DeDRM (10, 0, 9) && Quality Check (1, 13, 4)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259117 x 93.62457337883959
[0.00] Starting up...
[0.00] Initializing db...
[0.52] db initialized
[0.52] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Key 'F5' for shortcut Re-apply current sort is already used by Next result, ignoring
Key 'F5' for shortcut Re-apply current sort is already used by Next result, ignoring
[1.58] main UI initialized...
[1.58] Started up in 1.58 seconds with 1535 books
Starting QuickView
DeDRM v10.0.9: Trying to decrypt Sister of Starlit Seas.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Sister of Starlit Seas.epub is a secure Adobe Adept ePub for UUID fe30fff1-6961-45b7-979b-4dbee68e4998
DeDRM v10.0.9: Trying Encryption key default_ade_key_uuid_6d339b62-7285-440b-ae18-49bd68f73e0f
ilz48nag.epub is a secure Adobe Adept ePub.
Could not decrypt ilz48nag.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\Jungle\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
  File "C:\Users\Jungle\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with key default_ade_key_uuid_6d339b62-7285-440b-ae18-49bd68f73e0f after 0.1 seconds
DeDRM v10.0.9: Trying Encryption key default_key
ilz48nag.epub is a secure Adobe Adept ePub.
Could not decrypt ilz48nag.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\Jungle\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
  File "C:\Users\Jungle\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v10.0.9: Trying Encryption key default_key_2
ilz48nag.epub is a secure Adobe Adept ePub.
Could not decrypt ilz48nag.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\Jungle\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
  File "C:\Users\Jungle\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with key default_key_2 after 0.1 seconds
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 565, in ePubDecrypt
  File "C:\Users\Jungle\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 293, in adeptkeys
  File "C:\Users\Jungle\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 273, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Failed to check for calibre update: [Errno 11001] getaddrinfo failed
Failed to check for plugin update: [Errno 11001] getaddrinfo failed
stdout+stderr from file dialog helper: [b'', b'']
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xb1{\x99xq4=$\xa3\xef\x90\xe7\xa5sU\x0bY&\x1aKV*\xf2 \xc0xGy%\x10\x91\xc8', b'C:\\Users\\Jungle\\Documents\\My Digital Editions\\Sister of Starlit Seas.epub']
Added Sister of Starlit Seas to db in: 0.7

**Comment by ElleKayEm** [comment]
ADE used to download the book is on the same computer and user as calibre/DeDRM?  Try deleting the saved Adobe key from DeDRM's customization.  Add the book again letting DeDRM automatically retrieve the key.

**Comment by ElleKayEm** [comment]
Incidentally you can authorize your Kobo with your Adobe ID to read your sideloaded library books.

**Comment by JunglePredator** [comment]
> ADE used to download the book is on the same computer and user as calibre/DeDRM? Try deleting the saved Adobe key from DeDRM's customization. Add the book again letting DeDRM automatically retrieve the key.

Yes; only thing that changed from when it was working is the user name.
Deleting the key from DeDRM didn't help; but it's not actually finding the key. The ADE Keys window in configuration stays blank.

> Incidentally you can authorize your Kobo with your Adobe ID to read your sideloaded library books.

I'll have to look into that... off hand it wouldn't let me add anything with DRM that wasn't added through the Chapters account with auto-sync.

**Comment by ElleKayEm** [comment]
I don't know why it isn't working then.  One person recently reported success with this workaround: https://github.com/noDRM/DeDRM_tools/issues/405#issuecomment-1732593861

**Comment by JunglePredator** [comment]
> I don't know why it isn't working then. One person recently reported success with this workaround: [#405 (comment)](https://github.com/noDRM/DeDRM_tools/issues/405#issuecomment-1732593861)

That worked; your plugin imported the encryption key from the DeASCM export & started working while the configuration Window populated with the same key as from the log file I posted.

Thank you.

**Comment by drypen64** [comment]
I use ADE a lot and sometimes when my connection to the internet is spotty it gets..... stuck? I think that's why the workaround works. It basically removes what is stuck. At least that's what I figure is going on.

**Comment by ElleKayEm** [comment]
I could see that affecting DeACSM since it replaces ADE and both have to connect with the Adobe Content Server to download the book.  DeDRM is retrieving the key from the computer it's running on so an internet connect isn't a factor there.  I haven't had any issue myself, but I haven't changed my ADE setup either.  I wonder if it might be an issue with new ADE setups combined with using calibre 7, but I don't want to mess with what's working for me to test that idea.

**Comment by drypen64** [comment]
Yeah, but what if it happens when the book is downloading? I don't know how to test it either but it seems to happen here and there and work arounds for library books are exactly the same. If I delete the .acsm and redownload it to my computer it clears right up so that's why I wondered if it was "stuck" in a slower bandwidth so Calibre coun't access the key.

**Comment by ElleKayEm** [comment]
Again I could see that being an issue if you're using DeACSM to download the book directly into calibre.  But not if you've already downloaded the book with ADE on the same computer and user and are adding the epub/pdf itself to calibre.

This particular issue seems to have cropped up since the update to calibre 7.  May be just a coincidence though.
