### ISSUE TITLE
InvalidPlugin:The plugin in 'E:\\\\DeDRM_tools_10.0.9.zip'isinvalid.It does not contain a top-level init .py file

### ISSUE THREAD

**Issue by cjcxj** [noDRM/DeDRM_tools#470]
### Question / bug report

calibre, version 6.2.1
错误： 未处理的异常: <b>InvalidPlugin</b>:The plugin in 'E:\\下载\\DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.2.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 7, 0) && Package KFX (from KFX Input) (2, 7, 0) && Ebook Translator (2, 2, 0) && KFX metadata reader (from KFX Input) (2, 7, 0) && From KFX (2, 7, 0) && KFX Input (2, 7, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 300, in load
  File "calibre\customize\zipplugin.py", line 395, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'E:\\下载\\DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

### Which version of Calibre are you running?

6.2.1

### Which version of the DeDRM plugin are you running?

10.0.9

### Log output

```log
calibre, version 6.2.1
错误： 未处理的异常: <b>InvalidPlugin</b>:The plugin in 'E:\\下载\\DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.2.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 7, 0) && Package KFX (from KFX Input) (2, 7, 0) && Ebook Translator (2, 2, 0) && KFX metadata reader (from KFX Input) (2, 7, 0) && From KFX (2, 7, 0) && KFX Input (2, 7, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 300, in load
  File "calibre\customize\zipplugin.py", line 395, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'E:\\下载\\DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

```

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.9.zip and load DeDRM_plugin.zip into calibre.

**Comment by cjcxj** [comment]
> 解压DeDRM_tools_10.0.9.zip ，将DeDRM_plugin.zip加载到calibre中。

**Comment by cjcxj** [comment]
> 解压DeDRM_tools_10.0.9.zip ，将DeDRM_plugin.zip加载到calibre中。

thanks
