### ISSUE TITLE
DeDRM v10.0.3 not removing DRM from ePub ebook in Calibre 3.38.1 

### ISSUE THREAD

**Issue by Fanfad** [noDRM/DeDRM_tools#474]
### Question / bug report

Greetings,

DeDRM plugin ist not working on calibre wenn importing a new e-book that is DRM protected. 

The e-book is the following: https://www.kobo.com/ch/de/ebook/il-nome-del-vento-1 and was downloaded in Epub format with the help of Adobe Digital Editions 4.5.

Many thanks in advance and KR.
Fanny

### Which version of Calibre are you running?

3.38.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

calibre 3.38.1  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 3.38.1  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 3)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.21] db initialized
[0.21] Constructing main UI...
[1.59] main UI initialized...
[1.59] Hiding splash screen
[1.61] splash screen hidden
[1.62] Started up in 1.62 seconds with 26 books
objc[1057]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffaec89cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x131e6fcd8). One of the two will be used. Which one is undefined.
DeDRM v10.0.3: Trying to decrypt Il nome del vento.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Il nome del vento.epub is a secure Adobe Adept ePub for UUID 0de2bc9e-9dbb-4bdd-bd46-e37732415341
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v10.0.3: Trying a new default key
fNXHnb.epub is a secure Adobe Adept ePub.
Could not decrypt fNXHnb.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 305, in decryptBook
AttributeError: 'module' object has no attribute 'import_key'

DeDRM v10.0.3: Failed to decrypt with new default key after 0.4 seconds
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
With that version of calibre, try DeDRM 6.8.1: https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1

**Comment by Fanfad** [comment]
Thank you very much ! That works.
