### ISSUE TITLE
Issue v10.0.9 (RC1 for 10.1.0)

### ISSUE THREAD

**Issue by Decanigher** [noDRM/DeDRM_tools#477]
I have an issue to install DeDRM in Calibre. First time 1 or 2 years ago I do not have issue.
The message I received is at the end of my message. Do you have any idea?

calibre, version 7.4.0
ERREUR : Exception non gérée: <b>InvalidPlugin</b>:The plugin in '/Users/xx5253/Downloads/DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

calibre 7.4  embedded-python: True
macOS-14.2.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.2.1', ('', '', ''), 'arm64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 3)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 513, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 299, in load
  File "calibre/customize/zipplugin.py", line 394, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/xx5253/Downloads/DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

### Discussed in https://github.com/noDRM/DeDRM_tools/discussions/379

<div type='discussions-op-text'>

<sup>Originally posted by **noDRM** August  2, 2023</sup>
Since quite a bit of code has changed, this is a beta / RC release before v10.1.0 is released. I don't expect there to be any new bugs, though. 

Versions 10.0.4(s), 10.0.5(s) and 10.0.6(s) were released by other people in various forks, here's a larger version jump to 10.0.9 / 10.1.0 so we don't have conflicting plugin builds with the same version numbers. 

Notable changes: 
- Couple bugfixes for Calibre 4 and Calibre 6 (fixes #101 and #114)
- A bunch of bugfixes for odd PDF files (fixes #104, #183 and #233)
- Fix issues with key retrieval (fixes #109, #115, #116, #119, #134, #214)

For the full changelog, see [CHANGELOG.md](https://github.com/noDRM/DeDRM_tools/blob/master/CHANGELOG.md)

SHA256 checksum of the 10.0.9 ZIP file: `d46e7ff94a46dc871eb9b7e639e6da1883823cd5a9d705d53f51bd9c251aabda`

<hr /><em>This discussion was created from the release <a href='https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9'>v10.0.9 (RC1 for 10.1.0)</a>.</em></div>

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.9.zip.  Load DeDRM_plugin.zip into calibre.

**Comment by Decanigher** [comment]
Thanks

> Unzip DeDRM_tools_10.0.9.zip. Load DeDRM_plugin.zip into calibre.
