### ISSUE TITLE
Doesn

### ISSUE THREAD

**Issue by gaetanov62** [noDRM/DeDRM_tools#479]
I tried on arch linux with calibre version 7.4, the plugin doesn't work

**Comment by gaetanov62** [comment]
I tried on arch linux with calibre version 7.4, the plugin doesn't work

**Comment by gaetanov62** [comment]
I was trying to unlock a book I purchased on Amazon Kindle to read it anywhere

**Comment by ElleKayEm** [comment]
How are you downloading it?

**Comment by gaetanov62** [comment]
I got it straight into my Kindle reader and then imported it into calibre

**Comment by ElleKayEm** [comment]
Is an E-ink Kindle?  Did you enter the Kindle's serial number correctly into DeDRM's customization?  Also, if it is kfx format, are you using DeDRM 10.0.9 and the KFX Input plugin?

**Comment by gaetanov62** [comment]
Yes, I did everything you said but with stable DeDRM 10.0.3

**Comment by gaetanov62** [comment]
Now I tried with DeDRM 10.0.9 and it worked, thank you very much

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by gaetanov62** [comment]
Solved whith last beta version of DeDRM
