### ISSUE TITLE
dedrm of a two-column azw4-ebook mixes columns

### ISSUE THREAD

**Issue by diezoe** [noDRM/DeDRM_tools#486]
Hi
I use calbre 7.4 and DeDrm 10.0.9.
I bougth a book (.azw4 + .mbp) at amazon, downloaded it with kindle for PC 1.17.0 and imported it to the calibre library.
The dedrm basically works however instead of heaving the text of the left and then of the right column, I get the text of one line of the left an one line of the right column. So i would always have to read every second line for the text to make sense.
A picture from within Kindle for PC how it should look like.

![grafik](https://github.com/noDRM/DeDRM_tools/assets/158837215/fb2d6100-d166-4a9c-9554-415817df68e2)

And how I get the ebook/text looks like after loading the book to calibre (from calibre ebook-reader):

![grafik](https://github.com/noDRM/DeDRM_tools/assets/158837215/94af5775-d256-474e-beec-8d526f23b4bc)

If anybody has any help or a solution - please let me know.
Thanks!

**Comment by ElleKayEm** [comment]
The azw4 is a pdf in an Amazon wrapper.  Use the Kindle Unpack plugin to extract the pdf.  Then use an actual pdf viewer instead of calibre's ebook viewer.

**Comment by diezoe** [comment]
Thank you very much. That helped. Initially I tried with an older DeDRM and I got only hyroglyphs. Then it paritally worked (as above) with calibre 4. Then with calibre 7 and the actual DeDRM I got again the same result.
The PDF-conversion works :). Now I can read the book.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
