### ISSUE TITLE
DRM not removed

### ISSUE THREAD

**Issue by fuzzy-dice1** [noDRM/DeDRM_tools#489]
### Question / bug report

Trying to remove DRM and it doesn't seem to be working. Log below. Thanks!

### Which version of Calibre are you running?

7.4.0

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

Using calibre Qt style: True
FFF: INFO: 2024-02-08 12:13:17,874: calibre_plugins.fanficfare_plugin.prefs(216): Using default settings
FFF: DEBUG: 2024-02-08 12:13:17,878: calibre_plugins.fanficfare_plugin.fff_plugin(215): Plugin FanFicFare macmenuhack file_path:/Users/name/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
calibre Debug log
calibre 7.4  embedded-python: True
macOS-13.4.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64')
Python 3.11.5
OSX: ('13.4.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && FanFicFare (4, 31, 0)
calibre 7.4  embedded-python: True
macOS-13.4.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64')
Python 3.11.5
OSX: ('13.4.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && FanFicFare (4, 31, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
[0.00] Starting up...
[0.10] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.35] db initialized
[0.35] Constructing main UI...
[1.89] GUI main window shown
[2.01] main UI initialized...
[2.01] Hiding splash screen
[10.14] splash screen hidden
[10.14] Started up in 10.14 seconds with 1 books
DeDRM v10.0.3: Trying to decrypt puprb6am.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: puprb6am.epub is a secure Adobe Adept ePub for UUID 73c2af5b-c445-4a0c-8178-572c0f50e6f8
DeACSM v0.0.16: Running file type plugin failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 486, in run
    plugin_ret = plugin.run(rpl)
                 ^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
    userkey = codecs.decode(userkeyhex, 'hex')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
DeACSM v0.0.16: Trying to parse file DemonCopperhead_9780571376490_8825857.acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server https://acsepub.contentreserve.com/fulfillment/FulfillmentNotification
Fulfillment notification successful.
Notifying optional server https://ofs.contentreserve.com/ACSNotificationService.svc/Notify
Weird Fulfillment Notification response: 
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://acs.cdn.overdrive.com/ACSStore1/1515-1/79B/E4E/4E/{79BE4E4E-EF2F-4AD1-923D-7F0B74CD527C}Fmt410.epub
Download took 256 ms (HTTP 200)
That's a ZIP file -> EPUB
DeACSM v0.0.16: File successfully fulfilled ...
DeACSM v0.0.16: Executing plugin DeDRM ...
DeACSM v0.0.16: Plugin returned nothing - skipping

**Comment by ElleKayEm** [comment]
Delete the saved Adobe key in DeDRM's customization.  Then try taking the key from the DeACSM plugin and importing it into DeDRM.  You may also want to update to DeDRM 10.0.9.

**Comment by fuzzy-dice1** [comment]
Thank you!
