### ISSUE TITLE
Can't Install noDRM

### ISSUE THREAD

**Issue by divetravis** [noDRM/DeDRM_tools#49]
### Question / bug report

When I attempt to install DeDRM plugin I receive the following error

ModuleNotFoundError: No module named '__version'

Any idea how to correct this?

A couple of notes: The documentation indicates when I extract the DeDRM_tools-master.zip file I will find a DeDRM_Plugin.zip file that I will install via Calibre, however when I unzip the master file I don't actually have a a DEDRM_Plugin.zip file but I do have a directory named DeDRM_plugin. In order to get Calibre to install the plugin I have zipped the DeDRM_plugin directory.  This appears to work except when I attempt to install I get the preceding error.

### Which version of Calibre are you running?

5.38.0

### Which version of the DeDRM plugin are you running?

V 10.0.0

### If applicable, which version of the Kindle software are you running?

1.17.1

### Log output

```log
Paste log output here.
```calibre, version 5.38.0
ERROR: Unhandled exception: <b>ModuleNotFoundError</b>:No module named '__version'

calibre 5.38  embedded-python: True is64bit: False
Windows-10-10.0.22000 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 47, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 326, in add_plugin
  File "calibre\customize\ui.py", line 476, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 290, in load
  File "polyglot\builtins.py", line 123, in reload
  File "importlib\__init__.py", line 169, in reload
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "calibre\customize\zipplugin.py", line 191, in exec_module
  File "calibre_plugins.dedrm.__init__", line 97, in <module>
ModuleNotFoundError: No module named '__version'

**Comment by ElleKayEm** [comment]
Download DeDRM_tools_10.0.2.zip from here: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2

Unzip it and load DeDRM_plugin.zip into calibre.

**Comment by divetravis** [comment]
ElleKayEm, Thank you, Thank You, Thank you!!!! I spent hours trying to figure this out. The version you pointed to worked perfectly.
