### ISSUE TITLE
[bug?] Strange behaviour with KFX fles

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [noDRM/DeDRM_tools#506]
### Question / bug report

I've found a weird issue with KFX files where DeDRM seems to be working out of sync with the (up to date) KFX Input plugin.

When importing the books via "import books from folders and subfolders", at least on the ones I've tried the plugins correctly remove the DRM and give a KFX file, but they also keep the MD file (no idea what's that for) and, while accurately retrieving most of the metadata (like mobi number, author, cover, publishing date or publisher), the title and title alone is shown as a CR!x code as if the DRM wasn't removed. I could check that the DRM was removed (and hi-res images properly merged) by opening them with the Calibre reader (which would have returned an error if the book was still DRMed), and I can retrieve the correct title with the "set metadata from format" option.

### Which version of Calibre are you running?

7.6.0

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

2.3.1.5146

**Comment by j-howell** [comment]
> When importing the books via "import books from folders and subfolders", at least on the ones I've tried the plugins correctly remove the DRM and give a KFX file, but they also keep the MD file (no idea what's that for) and, while accurately retrieving most of the metadata (like mobi number, author, cover, publishing date or publisher), the title and title alone is shown as a CR!x code as if the DRM wasn't removed. I could check that the DRM was removed (and hi-res images properly merged) by opening them with the Calibre reader (which would have returned an error if the book was still DRMed), and I can retrieve the correct title with the "set metadata from format" option.

The incompatibility is between calibre and Amazon's choice of file extensions. A KFX metadata file downloaded using Kindle for PC uses the an extension of .azw.md. Calibre only uses the final .md extension and considers it to be a separate document in markdown format. You can prevent this processing in calibre by going to Preferences, Adding books, Automatic adding and checking "md" the Ignore files with these extensions list.

> Side note: among the books I've purchased there are some that seem to belong to a new "comic series" category or something, where the books (chapter) have no individual purchase page, they are shown and purchased directly from the series page (and the purchase button doesn't say "1-click purchase" like it usually does, but seems to behave almost exactly like that). You can read them directly through Kindle Cloud Reader, but even though they also appear in "Content and devices" as downloadable content, they seemingly cannot be downloaded to Kindle for PC or Kindle for Android, as they are deemed incompatible. Does anyone know which devices may be compatible for download?

I am curious to learn more. Can you provide an example?

I have read about Amazon rolling out scrollable comics (webcomics/fliptoon) in Japan but they are not available to me in the US. Could this be something related?

**Comment by l-l-l-l-l-l** [comment]
> I am curious to learn more. Can you provide an example?
> 
> I have read about Amazon rolling out scrollable comics (webcomics/fliptoon) in Japan but they are not available to me in the US. Could this be something related?

It seems to be fliptoons, yes. Searching around, it seems like fliptoons are only available for Amazon Cloud Reader/Kindle Cloud Reader, i.e. from your web browser, and even then it seems to not always work for some people (I'm lucky in that regard). They just lack the "available in these devices" section and are, for some reason, included among the rest of the content instead of on a separate list. Kindle will still try to download that content every single time if you made the mistake of trying to send it once; after that first failure, any further attempts to send it will return a no compatible devices registered error (would have been nice if they did it from the start), but my KfPC still tries to download them every single time it sychronizes.

Thanks for the info about the .md files; I shall disable them right now (and I hope that fixes the wrong title in future imports, it's tiring to fix them manually when it happens with many books).

**Comment by j-howell** [comment]
> Searching around, it seems like fliptoons are only available for Amazon Cloud Reader/Kindle Cloud Reader, i.e. from your web browser, and even then it seems to not always work for some people (I'm lucky in that regard).

I have seen indications that support for them may also be coming to the Kindle apps for iOS and Android. So far they are not available in my region so I have no experience with them.
