### ISSUE TITLE
ineptpdf_fileopen.pyw error when removing FileOpen DRM "Error: global name 'binascii' is not defined", but previous version ineptpdf_8.4.51.pyw decodes the file successfully

### ISSUE THREAD

**Issue by WeAreLegion999** [noDRM/DeDRM_tools#514]
edit: [solved]
added 

import binascii

at the beginning of the script and it worked. 

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Noticed that that Tetrachroma_FileOpen_ineptpdf was updated few months ago. And I'm using https://www.techstreet.com/direct/www-spdf-test.pdf to test the DRM removal. 

However, it seems that the updated script does not work as intended like the previous script ineptpdf_8.4.51.pyw (or I'm missing a library?) because the PDF is decrypted successfully in the previous version while the updated script returns an error "Error: global name 'binascii' is not defined"

new version: 
![Capture](https://github.com/noDRM/DeDRM_tools/assets/126003477/c5acd0e0-647c-43ac-9edb-716c8a743f44)
Debut txt:
[ineptpdf debug.txt](https://github.com/noDRM/DeDRM_tools/files/14572026/ineptpdf-8.4.51-debug.txt)

old version ineptpdf_8.4.51.pyw: 
![Capture2](https://github.com/noDRM/DeDRM_tools/assets/126003477/02c4410b-9df0-40ed-b5cd-de3de50fa6bc)
Debug txt: 
[ineptpdf-8.4.51-debug.txt](https://github.com/noDRM/DeDRM_tools/files/14572033/ineptpdf-8.4.51-debug.txt)

my Python v2.7.17

Thanks!!

edit: [solved]
added 

import binascii

at the beginning of the script and it worked.

**Comment by noDRM** [comment]
Thanks for the report, I've added that import statement. Thanks for confirming that the new version works.
