### ISSUE TITLE
Issue with removing Kobo DRM

### ISSUE THREAD

**Issue by smirk-1** [noDRM/DeDRM_tools#535]
### Question / bug report

When using the plugin to try to remove Kobo DRM it gives strange behavior, potentially does not recognize that the book has a drm based on how I understand the menu:
![image](https://github.com/noDRM/DeDRM_tools/assets/167384555/56a54f48-756e-4b55-b7b4-530642c5417a)
File is openable in Calibre, but is not readable:
![image](https://github.com/noDRM/DeDRM_tools/assets/167384555/59dc9de5-db32-4e67-a53c-5254f585dd9a)

report is shown with 10.0.3 but I tried 10.0.9 first and got the same issue

### Which version of Calibre are you running?

7.7.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.7  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 7.7  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 89.6470588235294 x 90.53465346534654
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.42] GUI main window shown
[0.44] main UI initialized...
[0.44] Hiding splash screen
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1857, in set_metadata
  File "calibre\db\cache.py", line 1780, in set_cover
  File "calibre\db\backend.py", line 1775, in set_cover
  File "calibre\utils\img.py", line 306, in save_cover_data_to
  File "calibre\utils\img.py", line 209, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty

**Comment by ElleKayEm** [comment]
Try closing Kobo Desktop before opening Obok.  The book should have a red closed lock.  Otherwise it will be imported unchanged.  This book isn't Kobo Plus?

**Comment by smirk-1** [comment]
Closing Kobo and importing the book again did fix it, thank you. Might be something to consider adding to the instructions though.
