### ISSUE TITLE
Purchased book on kindle that was published beyond Jan 2023 download on mac

### ISSUE THREAD

**Issue by PMPRIGBY** [noDRM/DeDRM_tools#543]
### Question / bug report

I have the Kindel 7.9 
Im running Sonoma 14.1
Calibre 7.9
DeDRM 10.0.9
KFX input 

I found my kindle book file and made it into a KFX-ZIP because it kfx awz9. azw8. 
When I try to upload the archived file noting 

### Which version of Calibre are you running?

7.9

### Which version of the DeDRM plugin are you running?

10.0.9

### If applicable, which version of the Kindle software are you running?

7.9

### Log output

```log
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.9bdcd911-3cee-4029-96d2-87604130a97f.voucher
strategy
AES
AES/CBC/PKCS5Padding
HmacSHA256
mac
voucher
8b3842516b5eb6f0491002485ec827d3
f705c1ac946a3c02b86ddd2ce6ef53b48b3842516b5eb6f0491002485ec827d3
bytearray(b'\x00_\x00\x00TLACNDIE6HmdHS5I2cgdSCCanaiPKBE3ACP5//SvDESAIP')
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
```

**Comment by ElleKayEm** [comment]
The KFX Input plugin should handle gathering it into a KFX-zip.  Looks like that may be a book that can't be decrypted.  How did you download the book?  Mind sharing the ASIN?

**Comment by j-howell** [comment]
DeDRM is not compatible with the latest Kindle for Mac app version 7 and up.

You need to use the old Kindle Classic app instead, If you can still find it and if it will run on your Mac.

**Comment by PMPRIGBY** [comment]
Appreciate y’all for answering my concerns promptly! I actually ended up downloading the kindle 1.40v for Mac & it work perfectly no KFX file!

**Comment by brcwyn2k** [comment]
> Appreciate y’all for answering my concerns promptly! I actually ended up downloading the kindle 1.40v for Mac & it work perfectly no KFX file!

Thank you! Your solution works well.

**Comment by ElleKayEm** [comment]
@PMPRIGBY If you're all set, you can close the issue.
