### ISSUE TITLE
Kobo decryption failed

### ISSUE THREAD

**Issue by mcspain84** [noDRM/DeDRM_tools#557]
### Question / bug report

I have downloaded everything in the kobo app but obok tries all decryption keys without success.

### Which version of Calibre are you running?

7.11

### Which version of the DeDRM plugin are you running?

10.0.9

### Log output

calibre 7.11  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 89.6470588235294 x 90.53465346534654
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.56] GUI main window shown
[0.58] main UI initialized...
[0.58] Hiding splash screen
[0.69] splash screen hidden
[0.69] Started up in 0.69 seconds with 0 books
Running Obok DeDRM v10.0.9
DEBUG:    4.6 didn't find device
Obok v10.0.9
Copyright © 2012-2023 Physisticated et al.
C:\Users\marce\AppData\Local\Temp\tmp5efjnr1z
DEBUG:    4.6 got kobodir C:/Users/marce/AppData/Local/Kobo/Kobo Desktop Edition
Found 12 possible keys to try.
DEBUG:    6.9 BookListTableWidget:get_books - book_num: 0
DEBUG:    6.9 BookListTableWidget:get_books - book: Teenage Mutant Ninja Turtles: The IDW Collection, Vol. 1
DEBUG:    6.9 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.9 - Decrypting Teenage Mutant Ninja Turtles: The IDW Collection, Vol. 1
Trying key:  b'7d7c32987fbc11ceb0f5137b8b328b47'
Checking text:b']\xde\xce\xe3\x86&/\xc4Q\x19':
Perhaps utf-8 without BOM
Bad character at 1, value 222
Decryption failed, trying next key.
Trying key:  b'5c72d4e6a082d9125d8942af668df254'
Checking text:b'p\xabqm\xcd\x1c\xd8!XZ':
Perhaps utf-8 without BOM
Bad character at 1, value 171
Decryption failed, trying next key.
Trying key:  b'3ba1bc8c6d2364d1ddf1982a74b644e9'
Checking text:b'\x80\x9d\xbc\xc3\x7f\x81>\xaf\x94w':
Perhaps utf-8 without BOM
Bad character at 0, value 128
Decryption failed, trying next key.
Trying key:  b'9c1fd224ce3c60240c2a8355276c027d'
Checking text:b"\x13\x1e\x06<As\x05'|V":
Perhaps utf-8 without BOM
Bad character at 0, value 19
Decryption failed, trying next key.
Trying key:  b'131763a5a60970a6e61ef9136e5ad381'
Checking text:b'6\xcfM\x06\xff)z{\xe6\x92':
Perhaps utf-8 without BOM
Bad character at 1, value 207
Decryption failed, trying next key.
Trying key:  b'5b79817af8a1e35f95c95695c849a397'
Checking text:b'\xc9\xb5\x13I\xe3>T\xe2\xbaC':
Perhaps utf-8 without BOM
Bad character at 0, value 201
Decryption failed, trying next key.
Trying key:  b'4df3cd7294b2dfda28a5eb42abbebb51'
Checking text:b'Z\xaf\xaeJH\xe2\x1a\x92\xba\x86':
Perhaps utf-8 without BOM
Bad character at 1, value 175
Decryption failed, trying next key.
Trying key:  b'3a9f274f93b86494c56d03b5679e494e'
Checking text:b'i\xbfD\x93\x99Yh\xa7+=':
Perhaps utf-8 without BOM
Bad character at 1, value 191
Decryption failed, trying next key.
Trying key:  b'e00d321cd27c67252942e21234f2a1ee'
Checking text:b'\xfd\x90\xd5z\xb8\x11\x07C\xac\x82':
Perhaps utf-8 without BOM
Bad character at 0, value 253
Decryption failed, trying next key.
Trying key:  b'f7e6720b2b6bfae75cdaa02032b99d8d'
Checking text:b'Lu\xaf\xd9\x04\xec6\xec19':
Perhaps utf-8 without BOM
Bad character at 2, value 175
Decryption failed, trying next key.
Trying key:  b'4afac1e53480f696a51dbfbdb18cd975'
Checking text:b'w\x12\xe6\xca\xab3\xdb\xe9\x89\x8d':
Perhaps utf-8 without BOM
Bad character at 1, value 18
Decryption failed, trying next key.
Trying key:  b'575b3fb3e9aec38e509095bf73056718'
Checking text:b'q\xd6\xdbu\xe4\xe4 \x1ar\x8e':
Perhaps utf-8 without BOM
Bad character at 1, value 214
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt Teenage Mutant Ninja Turtles: The IDW Collection, Vol. 1
DEBUG:    7.0 DecryptAddProgressDialog::do_book_action - book decryption failed: 'Teenage Mutant Ninja Turtles: The IDW Collection, Vol. 1'
Obok DeDRM v10.0.9 - wrapping up results.

**Comment by ElleKayEm** [comment]
I've noticed that books which aren't available for download as a regular epub don't seem to be decryptable when downloaded this way either.

**Comment by mcspain84** [comment]
After three times deinstalling kobo and calibre it suddendly worked.

**Comment by ElleKayEm** [comment]
Hmm...well, that's good.  Thanks for reporting back.
