### ISSUE TITLE
DMR Removal Not Happening

### ISSUE THREAD

**Issue by zeeba2107** [noDRM/DeDRM_tools#568]
### Question / bug report

I'm genuinely at a loss here. I've installed DeDRM 10.0.9, added the KFX Input plugin, added my Kindle Fire serial number through customizations, and even attempted the KFX workaround using Kindle PC (also did not work). All the files were downloaded via "download and transfer via usb" to the same device registered, and they are all books that I have purchased through Amazon in the past. Am I just missing something painfully obvious? 

### Which version of Calibre are you running?

7.13

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

Fire OS 7.3.2.7

### Log output

```log
[1.05] GUI main window shown
Ignoring blacklisted device: The \\?\usb#vid_1949&pid_03c2&mi_00#9&3531a16&0&0000#{6ac27878-a6fa-4155-ba85-f98f491d4f33} device has been blacklisted by the user
[1.09] main UI initialized...
[1.09] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt AOI House Vol. 1.azw3
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: AOI House Vol. 1
Got DSN key from database kindle_key_1720589961_1
Found 6 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 6 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.7 seconds
searching for kinfoFiles in C:\Users\Cole\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Cole\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2829820302' and UserName 'Cole'
DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Cole\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\Cole\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 6 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[79.95] splash screen hidden
[79.95] Started up in 79.95 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x88\x87\xd0\x87l\x16\x1b\t~\xb5\xb1\xea\x8e\xa6\xad\xc6Z\xed43\xcd\x92\x1b}\xc9\xdc\xf0)zn\xf9j', b'C:\\Users\\Cole\\Downloads\\Kindle\\AOI House Vol. 1.azw3']

```

**Comment by ElleKayEm** [comment]
The download & transfer via usb method only works for E-ink Kindles...not Fires.  Their serial numbers do nothing.

Should work with the Kindle for PC copy of the book though.  Let's see a log of that.

**Comment by zeeba2107** [comment]
> The download & transfer via usb method only works for E-ink Kindles...not Fires. Their serial numbers do nothing.
> 
> Should work with the Kindle for PC copy of the book though. Let's see a log of that.

I was afraid of that. Will I end up needing the Android key (saw some say yes in other guides) - cause having issues with that, too.

Here's the log for the PC copy. Appreciate the help!

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.13  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
calibre 7.13  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.45378151260503 x 102.35820895522387
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
[1.05] GUI main window shown
[1.11] main UI initialized...
[1.11] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing C:\Users\Cole\Documents\My Kindle Content\B0D475T4KK_EBOK\B0D475T4KK_EBOK.azw
[15.69] splash screen hidden
[15.69] Started up in 15.69 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x06\x9b\xcci\x87\xca\xac\x039p\x93F\xcc@\xdc8\xcdH\x9a\xb4\xad\xd9!n\x84U\xb7\xf7\x9ej\xe4\x08', b'C:\\Users\\Cole\\Documents\\My Kindle Content\\B0D475T4KK_EBOK\\B0D475T4KK_EBOK.azw']
Gather KFX-ZIP (from KFX Input): Gathered 38 file(s) as C:\Users\Cole\AppData\Local\Temp\calibre_4hrrctiw\xy7zh8ts.kfx-zip
DeDRM v10.0.9: Trying to decrypt xy7zh8ts.kfx-zip
Decrypting KFX-ZIP ebook: xy7zh8ts
Got DSN key from database kindle_key_1720589961_1
Found 2 keys to try after 0.6 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.44db1385-8335-4744-bcda-56205f851d37.voucher
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "C:\Users\Cole\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\Cole\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1368, in decryptvoucher
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
Decryption failed, trying next fallback 
Decryption succeeded
KFX DRM voucher successfully decrypted
Decrypting KFX DRMION: B0D475T4KK_EBOK.azw
Decrypting KFX DRMION: CR!1WC23K8DJX7JZ0PGW3BTE8BHJHG1.azw.res
Decrypting KFX DRMION: CR!29H6WGY2JH49K9J195QCKVMYX0C6.azw.res
Decrypting KFX DRMION: CR!3PPC0808HD52VBVBN27WSEFPQH8M.azw.res
Decrypting KFX DRMION: CR!42YGBPZB895VH9BG3P8HX76TRMPE.azw.res
Decrypting KFX DRMION: CR!4KJFDPPSFX4CS0VR3VGVT7CR19ZZ.azw.res
Decrypting KFX DRMION: CR!4P5CW57J8N2WN9J4C3MY889ZD3TB.azw.res
Decrypting KFX DRMION: CR!5D8MTTRDC16YDDKK946GABWN3GJ5.azw.res
Decrypting KFX DRMION: CR!6WM10PTRP14353G41H8X6FBZXC61.azw.res
Decrypting KFX DRMION: CR!7ZNDGDP2BX7Q1AQH05KH6XYMA5DG.azw.res
Decrypting KFX DRMION: CR!8NF9EM2Y5155K5WN2X1MD5P16VMD.azw.res
Decrypting KFX DRMION: CR!987G5A3ADX6MXEDC105FAJX629RC.azw.res
Decrypting KFX DRMION: CR!9ANZG0ZHHH1193W86TDDA77BPDXR.azw.res
Decrypting KFX DRMION: CR!9EN6QRBC7X14S2MEDRBME7M15BF1.azw.res
Decrypting KFX DRMION: CR!AXJAHSCGZ50K51SFYCP5X21W9RJM.azw.res
Decrypting KFX DRMION: CR!AZ93DNP6ZS24NCWVFF38RHBXPP4T.azw.res
Decrypting KFX DRMION: CR!B5HH1C9SBN6VX21XMD1MTDT92E5X.azw.res
Decrypting KFX DRMION: CR!BKSP6QDCKD32F2F68MGS71ZA1GZH.azw.res
Decrypting KFX DRMION: CR!BM0Y4XTKX90TZFFHEXWZTJMGHAZC.azw.res
Decrypting KFX DRMION: CR!C7QPQV7H814312141RNEPSER0X82.azw.res
Decrypting KFX DRMION: CR!DNWP4GZ3EX3E757D30DN51FFHJVB.azw.res
Decrypting KFX DRMION: CR!DQVB2H3Z696H55CNCMN5NF2G7BKJ.azw.res
Decrypting KFX DRMION: CR!EEPGP2TYGX4JVAYB7K4HXEVRXZDH.azw.res
Decrypting KFX DRMION: CR!GG34T37BTX5JNCQWJV9Y3NMWERRY.azw.res
Decrypting KFX DRMION: CR!J2SMT45DCX5FKDQVXE37C0VDPSGS.azw.res
Decrypting KFX DRMION: CR!J791NWKV991JQ3NTZA4ERTTJR8EN.azw.res
Decrypting KFX DRMION: CR!J8Q64GD5TD01HD5J8P25KTGJ7AM1.azw.res
Decrypting KFX DRMION: CR!JD2WP9ZHNS53F8S4S3F0NXATEM6F.azw.res
Decrypting KFX DRMION: CR!JSD7PQ6ZAX6N1BPQS6FF7ZPGJFCM.azw.res
Decrypting KFX DRMION: CR!M07AN9PQ0H0BFBSQYKB4KREKDR67.azw.res
Decrypting KFX DRMION: CR!P1MPT92XR12756BY1ZH43GYXRBS4.azw.res
Decrypting KFX DRMION: CR!SBZJB1PZN96J1FMFE69PKF13VV62.azw.res
Decrypting KFX DRMION: CR!SWW259X1MN57ZFPAWZ7D00KHBMN9.azw.res
Decrypting KFX DRMION: CR!WVWG0TF4K97SD99JB02XM6CKE8M0.azw.res
Decrypting KFX DRMION: CR!X0FXZ1CYP1241EZPQ59NXW1EAS7J.azw.res
Decrypting KFX DRMION: CR!Z7BHTGR1X12A96RZRA465TJMNC60.azw.res
Decryption succeeded after 5.2 seconds
DeDRM v10.0.9: Finished after 5.4 seconds
Package KFX (from KFX Input) 2.15.0: Packaging C:\Users\Cole\AppData\Local\Temp\calibre_4hrrctiw\qgyc3qrr.kfx-zip
Processing container: B0D475T4KK_EBOK.azw
Processing container: CR!1WC23K8DJX7JZ0PGW3BTE8BHJHG1.azw.res
Processing container: CR!29H6WGY2JH49K9J195QCKVMYX0C6.azw.res
Processing container: CR!3PPC0808HD52VBVBN27WSEFPQH8M.azw.res
Processing container: CR!3ZVM308T8X76D8B344JJ0RGMQ7MM.azw.md
Processing container: CR!42YGBPZB895VH9BG3P8HX76TRMPE.azw.res
Processing container: CR!4KJFDPPSFX4CS0VR3VGVT7CR19ZZ.azw.res
Processing container: CR!4P5CW57J8N2WN9J4C3MY889ZD3TB.azw.res
Processing container: CR!5D8MTTRDC16YDDKK946GABWN3GJ5.azw.res
Processing container: CR!6WM10PTRP14353G41H8X6FBZXC61.azw.res
Processing container: CR!7ZNDGDP2BX7Q1AQH05KH6XYMA5DG.azw.res
Processing container: CR!8NF9EM2Y5155K5WN2X1MD5P16VMD.azw.res
Processing container: CR!987G5A3ADX6MXEDC105FAJX629RC.azw.res
Processing container: CR!9ANZG0ZHHH1193W86TDDA77BPDXR.azw.res
Processing container: CR!9EN6QRBC7X14S2MEDRBME7M15BF1.azw.res
Processing container: CR!AXJAHSCGZ50K51SFYCP5X21W9RJM.azw.res
Processing container: CR!AZ93DNP6ZS24NCWVFF38RHBXPP4T.azw.res
Processing container: CR!B5HH1C9SBN6VX21XMD1MTDT92E5X.azw.res
Processing container: CR!BKSP6QDCKD32F2F68MGS71ZA1GZH.azw.res
Processing container: CR!BM0Y4XTKX90TZFFHEXWZTJMGHAZC.azw.res
Processing container: CR!C7QPQV7H814312141RNEPSER0X82.azw.res
Processing container: CR!DNWP4GZ3EX3E757D30DN51FFHJVB.azw.res
Processing container: CR!DQVB2H3Z696H55CNCMN5NF2G7BKJ.azw.res
Processing container: CR!EEPGP2TYGX4JVAYB7K4HXEVRXZDH.azw.res
Processing container: CR!GG34T37BTX5JNCQWJV9Y3NMWERRY.azw.res
Processing container: CR!J2SMT45DCX5FKDQVXE37C0VDPSGS.azw.res
Processing container: CR!J791NWKV991JQ3NTZA4ERTTJR8EN.azw.res
Processing container: CR!J8Q64GD5TD01HD5J8P25KTGJ7AM1.azw.res
Processing container: CR!JD2WP9ZHNS53F8S4S3F0NXATEM6F.azw.res
Processing container: CR!JSD7PQ6ZAX6N1BPQS6FF7ZPGJFCM.azw.res
Processing container: CR!M07AN9PQ0H0BFBSQYKB4KREKDR67.azw.res
Processing container: CR!P1MPT92XR12756BY1ZH43GYXRBS4.azw.res
Processing container: CR!SBZJB1PZN96J1FMFE69PKF13VV62.azw.res
Processing container: CR!SWW259X1MN57ZFPAWZ7D00KHBMN9.azw.res
Processing container: CR!WVWG0TF4K97SD99JB02XM6CKE8M0.azw.res
Processing container: CR!X0FXZ1CYP1241EZPQ59NXW1EAS7J.azw.res
Processing container: CR!Z7BHTGR1X12A96RZRA465TJMNC60.azw.res
Features: CanonicalFormat-2, max_id-832, yj_double_page_spread-1, yj_jpg_rst_marker_present-1, yj_non_pdf_fixed_layout-2, yj_thumbnails_present-1
Metadata: ASIN=B0D475T4KK, asset_id=CR!8AF3NG097N4HNCNJARWE67GTJX6W, author=Otsuji, book_id=66pDosHqSK6BvmENjqswQA0, cde_content_type=EBOK, content_id=B0D475T4KK, continuous_popup_progression=0, cover_image=1367x1920, creator_version=2.15.0, description=..., file_creator=YJConversionTools, is_sample=False, issue_date=2024-06-18, kfxgen=20.12.238.0, language=en, publisher="Seven Seas Entertainment, LLC.", reading_orders=1, title="My Stepmother and Stepsisters Aren't Wicked Vol. 4", yj_double_page_spread=1, yj_fixed_layout=1
KFX container created may be too large for some devices (102306583 bytes)
Package KFX (from KFX Input): Imported as KFX
KFX metadata reader (from KFX Input) activated for C:\Users\Cole\AppData\Local\Temp\calibre_4hrrctiw\h4oy2z1z_add_books\0\B0D475T4KK_EBOK.kfx

**Comment by ElleKayEm** [comment]
Log shows successful decryption.

**Comment by zeeba2107** [comment]
> Log shows successful decryption.

Guess I'll have to keep playing with that one, then. Thanks for the help, appreciate it!
