### ISSUE TITLE
Cannot remove DRM amazon 

### ISSUE THREAD

**Issue by stern88-hub** [noDRM/DeDRM_tools#579]
### Question / bug report

Calibre cannot remove DRM from Amazon azw book.
Windows 11 Home 23H2 - Kindle for PC version 2.3.0 (70673) - Calibre version 7.15

### Which version of Calibre are you running?

7.15

### Which version of the DeDRM plugin are you running?

10.0.9

### If applicable, which version of the Kindle software are you running?

2.3.0

### Log output

```log
Paste log output here.
```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
EpubMerge: DEBUG: 2024-07-26 14:04:48,094: calibre_plugins.epubmerge.epubmerge_plugin(156): macmenuhack file_path:C:\Users\PS\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 7.15  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && Amazon.com Multiple Countries (1, 0, 0) && Barnes & Noble (1, 5, 5) && EpubMerge (3, 1, 0) && EpubSplit (3, 8, 0) && Extract ISBN (1, 6, 3) && Fantastic Fiction (1, 7, 0) && Find Duplicates (1, 10, 9) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && Kindle hi-res covers (0, 5, 1) && Kobo Books (1, 9, 2) && Manage Series (1, 5, 2) && Obok DeDRM (7, 2, 1) && Reading List (1, 15, 4)
calibre 7.15  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && Amazon.com Multiple Countries (1, 0, 0) && Barnes & Noble (1, 5, 5) && EpubMerge (3, 1, 0) && EpubSplit (3, 8, 0) && Extract ISBN (1, 6, 3) && Fantastic Fiction (1, 7, 0) && Find Duplicates (1, 10, 9) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && Kindle hi-res covers (0, 5, 1) && Kobo Books (1, 9, 2) && Manage Series (1, 5, 2) && Obok DeDRM (7, 2, 1) && Reading List (1, 15, 4)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 165.87755102040816 x 166.25454545454545
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[3.77] db initialized
[3.77] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[9.49] GUI main window shown
[9.59] main UI initialized...
[9.59] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing C:\Users\PS\Downloads\B0BT57ZCF5_EBOK.azw
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\PS\AppData\Local\Temp\calibre_jl3y9lic\v74sot32.kfx-zip
DeDRM v10.0.9: Trying to decrypt v74sot32.kfx-zip
[9.64] Starting the smartdevice driver
SMART_DEV (   0.00:  0.000) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.03:  0.842) _startup_on_demand listening on port 9090
SMART_DEV (   1.06:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.08:  0.000) _startup_on_demand broadcast socket listening on port 54982
[10.75] Finished starting smartdevice
[10.99] splash screen hidden
[10.99] Started up in 10.99 seconds with 60998 books
SMART_DEV (   2.11:  1.018) run All IP addresses {'{364EC005-27EE-4E3E-8570-13D2E34F6888}': [{'addr': '192.168.1.195', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}], '{155BF64C-8F80-11EA-A50F-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xc07T\xd39\xfdd\x0e\xea\xde/\xe5YR\xe1\xfc\xc6\xdfR\xa2%\xa5Q^-\x06\xf5]\xb8R\x14\n', b'C:\\Users\\PS\\Downloads\\B0BT57ZCF5_EBOK.azw']
Decrypting KFX-ZIP ebook: v74sot32
Got DSN key from database default_key
Found 1 keys to try after 0.5 seconds
DeDRM v10.0.9: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.9: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\PS\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\PS\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1390688896' and UserName 'PS'
DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\PS\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\PS\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\PS\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.15.0: Packaging C:\Users\PS\AppData\Local\Temp\calibre_jl3y9lic\v74sot32.kfx-zip
Processing container: B0BT57ZCF5_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0BT57ZCF5_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\PS\AppData\Local\Temp\calibre_jl3y9lic\aaosu6cx_add_books\0\B0BT57ZCF5_EBOK.kfx-zip
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in get_metadata
Exception: Failed to locate a KFX container with metadata

**Comment by ElleKayEm** [comment]
Here is the issue:

> Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import.

**Comment by stern88-hub** [comment]
Thank you so much!

Problem resolved

 

Enjoy your weekend!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
