### ISSUE TITLE
Kindle mobi not decrypted

### ISSUE THREAD

**Issue by fabnicol** [noDRM/DeDRM_tools#58]
### Question / bug report

All recent .mobi ebooks bought from Amazon recently do not get decrypted when added to Calibre. 
Platform is: Win10, Calibre 5.39, latest noDrm release (10.0.2),  Kindle for PC 1.17.0

### Which version of Calibre are you running?

5.39

### Which version of the DeDRM plugin are you running?

v10.0.2

### If applicable, which version of the Kindle software are you running?

1.17.0

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Possibly the bug where they are misidentified as mobi when they are a pdf in an Amazon wrapper.  Try the KindleUnpack plugin to see if you can extract the pdf.

**Comment by fabnicol** [comment]
Not an obvious trick, but correct.

Thanks, this worked!
