### ISSUE TITLE
DeDRM issue

### ISSUE THREAD

**Issue by msy9999** [noDRM/DeDRM_tools#584]
### Question / bug report

I am able to open the epub file but it it is still encrypted after import to calilbre.

### Which version of Calibre are you running?

7.15

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Paste log output here.
```ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Fehlerdiagnoseprotokoll
calibre 7.15  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 7.15  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 105.21682847896439 x 105.10344827586206
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[0.72] GUI main window shown
[0.78] main UI initialized...
[0.78] Hiding splash screen
DeDRM v10.0.3: Trying to decrypt Notes on an Execution - Danya Kukafka.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Post-processing took 0.0 seconds
DeDRM v10.0.3: Finished after 0.3 seconds
[10.20] splash screen hidden
[10.20] Started up in 10.20 seconds with 215 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'@\xb4\xdb\x8f<P\x1e\xfd\x94>i\x0e\xa3\xa3\x9d\xf5\xbeH^\xb7J\x0b\xd2\x1fa\x04\xe5"\x8e\xf2(\xd7', b'C:\\Users\\msydo\\Desktop\\Danya Kukafka\\Notes on an Execution (210)\\Notes on an Execution - Danya Kukafka.epub']
Added Notes on an Execution to db in: 0.2
Added 1 books in 1.0 seconds

**Comment by ElleKayEm** [comment]
Where is the book from? DeDRM isn't recognizing it as an Adobe DRM epub.

**Comment by msy9999** [comment]
> Where is the book from? DeDRM isn't recognizing it as an Adobe DRM epub.

It has been bought online. It is marked by the shop as Adobe DRM protected.

**Comment by ElleKayEm** [comment]
Not sure what is going on then.  Did you download it with Adobe Digital Editions?  If so, was ADE authorized with your Adobe ID?

**Comment by msy9999** [comment]
Yes, it has been downloaded on an e-reader linked with my Adobe ID and imported from there.

**Comment by ElleKayEm** [comment]
Ok, if you install ADE on the computer where you have calibre/DeDRM and authorize it with the same Adobe ID, DeDRM should be able to pick up the key from that.  Recommend updating to DeDRM 10.0.9 as well.

https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by msy9999** [comment]
ADE is already installed  on the same drive as calibre, and I also updated to 10.0.9

**Comment by ElleKayEm** [comment]
Ok, I'm stumped.  The log will usually show more info when something goes wrong. 
 Can you open and read it in ADE?

**Comment by msy9999** [comment]
Yes, no problem with ADE.

**Comment by ElleKayEm** [comment]
When you go into DeDRM's customization, is there a key in the Adobe Digital Editions ebooks section?  Have you been able to decrypt other Adobe DRM books downloaded with ADE?

**Comment by msy9999** [comment]
Yes, the key was already stored in the plugin correctly. I found a way that finally worked: I downloaded all ACSM files with ADE , then downloaded all EPUB files into ADE. I then re-imported the files from the ADE folder into Calibre - voila!

**Comment by msy9999** [comment]
Thanks a ton for your help, very much appreciated!!

**Comment by ElleKayEm** [comment]
I'm glad you got it figued out.  And thanks for the explanation of what worked.
