### ISSUE TITLE
calibre plugin fails on Adobe and Kindle ebooks

### ISSUE THREAD

**Issue by nrbeaton** [noDRM/DeDRM_tools#6]
OS: Arch Linux
DeDRM version: 10.0.2 (the version from the AUR https://aur.archlinux.org/packages/calibre-plugin-dedrm/)
Calibre version: 5.33.2

This used to work just fine (a couple of months ago maybe, on a previous install of Arch) but now it's totally non-functional. 

Fresh installs of Kindle using WINE (versions 1.30, 1.31 and 1.33). I can extract the key fine, import it into the Calibre plugin, but when I try to add a book the DRM does not get removed.

Likewise with ADE version 2.0.1. 

If there's logs or something I can produce then let me know how and I'll post them.

**Comment by ElleKayEm** [comment]
For the Kindle app, do you have KFX downloads disabled?  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371

For ADE, do you have it authorized with your Adobe ID? 

Here's how to get a log:  https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

Please only do one book per log.

**Comment by nrbeaton** [comment]
I did the debug mode with an ADE book and the error message mentioned something about the module `crypto` being missing. So I went hunting and tried installing `pycryptodome` which has fixed the problem (for ADE at least, I haven't tried a Kindle book yet).

So `pycryptodome` is an undeclared dependency?
