### ISSUE TITLE
DRM conversion error in Calibre from Kindle files

### ISSUE THREAD

**Issue by shape55** [noDRM/DeDRM_tools#60]
Hi, I'm using Kindle app 1.26.1 (55093) which is supposedly the last version where DRM removal is possible according to Method 4 [here](https://www.mobileread.com/forums/showthread.php?t=283371) and the latest Calibre 5.40.  I installed the latest DRM tools 10.0.2 but am getting this error: https://www.screencast.com/t/L1mpkHIhvv when trying to convert .azw files downloaded from the Kindle app to EPUB.

If I go into the Plugins prefs it confirms that DeDRM 10.0.2 and KFX Input 1.47.0 are installed.

**Comment by ElleKayEm** [comment]
Let's see the import log: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by shape55** [comment]
Thanks for the instructions link.

calibre Debug log
calibre 5.40  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 47, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0)
calibre 5.40  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 47, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 132.00000198244115 x 132.50000198995036
Using calibre Qt style: True
[0.00] Starting up...
[0.10] Showing splash screen...
[0.74] splash screen shown
[0.74] Initializing db...
[0.78] db initialized
[0.78] Constructing main UI...
[3.33] main UI initialized...
[3.33] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.47.0: Importing /Users/shape2/.Trash/Kindle/My Kindle Content/B09BCMY88V_EBOK/B09BCMY88V_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as /var/folders/77/l619y4256td6rb3q2p96lwhh0000gn/C/calibre_5.40.0_tmp_7jl6pyua/9g2sw07a.kfx-zip
DeDRM v10.0.2: Trying to decrypt 9g2sw07a.kfx-zip
[45.14] splash screen hidden
[45.14] Started up in 45.14 seconds with 1 books
Using Library AlfCrypto Python
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: 9g2sw07a
Found 0 keys to try after 0.3 seconds
DeDRM v10.0.2: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.2: Looking for new default Kindle Key after 0.3 seconds
Found k4Mac kinf2018 file: /Users/shape2/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'shape2'  on file  /Users/shape2/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'99875e48e54f'
Decrypted key file using IDString '99875e48e54f' and UserName 'shape2'
DeDRM v10.0.2: Found 1 new key
Decrypting KFX-ZIP ebook: 9g2sw07a
Got DSN key from database default_key_1
Found 1 keys to try after 2.0 seconds
DeDRM v10.0.2: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.47.0: Packaging /var/folders/77/l619y4256td6rb3q2p96lwhh0000gn/C/calibre_5.40.0_tmp_7jl6pyua/9g2sw07a.kfx-zip
Processing container: B09BCMY88V_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/77/l619y4256td6rb3q2p96lwhh0000gn/C/calibre_5.40.0_tmp_7jl6pyua/cmsqrbo9_add_books/0/B09BCMY88V_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 66, in decrypt_voucher
    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B09BCMY88V_EBOK.azw has DRM and cannot be converted
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 432, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
    md = YJ_Book(stream).get_metadata()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
    raise Exception("Failed to locate a KFX container with metadata")
Exception: Failed to locate a KFX container with metadata
Added B09BCMY88V EBOK to db in: 0.0
Added 1 books in 4.0 seconds

**Comment by ElleKayEm** [comment]
Looks like the book has been moved from its original download location and not all of the files needed for decryption can be located.

**Comment by shape55** [comment]
Aha, you're right.  I was using an alias to the "My Kindle Content" folder and I moved it from its original location when I was installing the older version of the Kindle app. I resolved it and now the file conversions work with no error.  Thank you! :slightly_smiling_face:

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
