### ISSUE TITLE
Unable to open kindle books on Calibre

### ISSUE THREAD

**Issue by PYPeke** [noDRM/DeDRM_tools#601]
Which version of Calibre are you running?
7.14

Which version of the DeDRM plugin are you running?
10.0.9

If applicable, which version of the Kindle software are you running?
2.4.0 (70904)

I am also using KFX Input plugin.

The books open in the Kindle for PC, and I can read them there.

When I downloaded a book to Calibre, it says I need to download a program that can read that format. I assume the DRM has not been removed. The books I tried were all purchased and published many years ago. 

I am not sure if I have the right log, but here is what I found.
What am I doing wrong? Thanks.

applicationpalettechange event ignored
using calibre qt style: true
calibre debug log
calibre 7.14  embedded-python: true
windows-10-10.0.19045-sp0 windows ('64bit', 'windowspe')
('windows', '10', '10.0.19045')
python 3.11.5
windows: ('10', '10.0.19045', 'sp0', 'multiprocessor free')
interface language: none
exe path: c:\program files\calibre2\calibre-debug.exe
successfully initialized third party plugins: gather kfx-zip (from kfx input) (2, 15, 0) && dedrm (10, 0, 9) && package kfx (from kfx input) (2, 15, 0) && kfx metadata reader (from kfx input) (2, 15, 0) && from kfx (2, 15, 0) && kfx input (2, 15, 0) && obok dedrm (10, 0, 9)
calibre 7.14  embedded-python: true
windows-10-10.0.19045-sp0 windows ('64bit', 'windowspe')
('windows', '10', '10.0.19045')
python 3.11.5
windows: ('10', '10.0.19045', 'sp0', 'multiprocessor free')
interface language: none
exe path: c:\program files\calibre2\calibre-debug.exe
successfully initialized third party plugins: gather kfx-zip (from kfx input) (2, 15, 0) && dedrm (10, 0, 9) && package kfx (from kfx input) (2, 15, 0) && kfx metadata reader (from kfx input) (2, 15, 0) && from kfx (2, 15, 0) && kfx input (2, 15, 0) && obok dedrm (10, 0, 9)
qpa platform: windows
devicepixelratio: 1.0
logicaldpi: 96.0 x 96.0
physicaldpi: 91.73814898419865 x 91.80722891566265
[0.00] starting up...
[0.00] showing splash screen...
[0.22] splash screen shown
[0.22] initializing db...
[0.34] db initialized
[0.34] constructing main ui...
debug:    0.0 obok::utilities.py - loading translations
debug:    0.0 obok::dialogs.py - loading translations
debug:    0.0 obok::config.py - loading translations
debug:    0.0 obok::action_err.py - loading translations
[2.58] gui main window shown
[2.88] main ui initialized...
[2.88] hiding splash screen
[25.41] splash screen hidden
[25.41] started up in 25.41 seconds with 1330 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"e\x97l\x15#\xd9\xac\xc7h\xac\xe2\x87\x06\x95\xf4\xf4m'b\xa3\xca\xcc\xc2r}\xc2d\xa2y\x97\xa0\x1e", b'c:\\users\\patti\\documents\\my kindle\\my kindle content\\b000fc146c_ebok\\b000fc146c_ebok.azw']
gather kfx-zip (from kfx input) 2.15.0: importing c:\users\patti\documents\my kindle\my kindle content\b000fc146c_ebok\b000fc146c_ebok.azw
gather kfx-zip (from kfx input): gathered 4 file(s) as c:\users\patti\appdata\local\temp\calibre_6285r_45\gcq32q7u.kfx-zip
dedrm v10.0.9: trying to decrypt gcq32q7u.kfx-zip
decrypting kfx-zip ebook: gcq32q7u
got dsn key from database kindle_key_1723574359_1
found 1 keys to try after 1.0 seconds
decrypting kfx drm voucher: amzn1.drm-voucher.v1.2ee5ea60-16ec-4612-aa7b-7190642caa53.voucher
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
decryption failed, trying next fallback 
traceback (most recent call last):
  file "c:\users\patti\appdata\roaming\calibre\plugins\dedrm.zip\kfxdedrm.py", line 105, in decrypt_voucher
  file "c:\users\patti\appdata\roaming\calibre\plugins\dedrm.zip\ion.py", line 1368, in decryptvoucher
unboundlocalerror: cannot access local variable 'ex' where it is not associated with a value
decryption failed, trying next fallback 
decryption succeeded
kfx drm voucher successfully decrypted
decrypting kfx drmion: b000fc146c_ebok.azw
decryption succeeded after 1.1 seconds
dedrm v10.0.9: finished after 1.1 seconds
package kfx (from kfx input) 2.15.0: packaging c:\users\patti\appdata\local\temp\calibre_6285r_45\x4q3e2nk.kfx-zip
processing container: b000fc146c_ebok.azw
processing container: cr!8djhnvadf90bz0kgyb4yshrd2cv1.azw.res
processing container: cr!w13qxjpqgx4vb0ck3jb7m99vk4ak.azw.md
features: canonicalformat-2, kfxgen.textblock-1, max_id-787, reflow-section-size-5, reflow-style-1
metadata: asin=b000fc146c, asset_id=cr!y5dwbrcp2178h48qjfbh30xjy4ed, author="mccullough, colleen", book_id=huvdcuvkqcm-ghiylqta6w0, cde_content_type=ebok, content_id=b000fc146c, cover_image=793x1300, creator_version=2.15.0, file_creator=yjconversiontools, is_sample=false, issue_date=2009-10-13, kfxgen=20.12.238.0, language=en, nested_span=enabled, pages=752, publisher=harpercollins, reading_orders=1, selection=enabled, title="the thorn birds"
package kfx (from kfx input): imported as kfx
kfx metadata reader (from kfx input) activated for c:\users\patti\appdata\local\temp\calibre_6285r_45\vqahau45_add_books\0\b000fc146c_ebok.kfx

**Comment by ElleKayEm** [comment]
DRM is removed.  If you want to read kfx format with the calibre viewer, set that in the preferences > behavior > in the right column, check the box for kfx under "use internal viewer for".

**Comment by PYPeke** [comment]
Thank you. I checked all the Amazon boxes, but I missed that one.
