### ISSUE TITLE
Some Kobo book can remove DRM and some give me error.

### ISSUE THREAD

**Issue by weskeryiu** [noDRM/DeDRM_tools#610]
### Question / bug report

I have two EPUB files downloaded from Kobo. One is working, and the other gives me an error when I try to read it with Calibre.
The working one is in Traditional Chinese and is called ‘輝夜姬想讓人告白 (1). 
The one that fails is in Japanese and is called ‘【推しの子】 14.’ 

Both EPUBs were downloaded from Kobo, then using Adobe Digital Editions and imported into Calibre on the same computer. While I can drag both books into Calibre without any problems, when I right-click and choose ‘View’ or ‘Convert  books‘, ‘輝夜姬’ opens without issue, but ‘【推しの子】’ gives me an error.

### Which version of Calibre are you running?

7.17

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

no

### Log output(When press 'View')

calibre, version 7.17.0
ERROR: Loading book failed: Failed to open the book at C:\Users\weskeryiu\calibre 書庫\Chi Ban akaxHeng Qiang mengo\[(Tui sinoZi )]  14 (16)\[(Tui sinoZi )]  14 - Chi Ban akaxHeng Qiang mengo.epub. Click "Show details" for more info.

Failed to convert book: C:\Users\weskeryiu\calibre 書庫\Chi Ban akaxHeng Qiang mengo\[(Tui sinoZi )]  14 (16)\[(Tui sinoZi )]  14 - Chi Ban akaxHeng Qiang mengo.epub with error:
DeDRM v10.0.9: Trying to decrypt [(Tui sinoZi )]  14 - Chi Ban akaxHeng Qiang mengo.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Post-processing took 0.0 seconds
DeDRM v10.0.9: Finished after 2.5 seconds
InputFormatPlugin: EPUB Input running
on C:\Users\WESKER~1\AppData\Local\Temp\calibre_5jbohtxh\xy4o2vza.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 965, in viewer_main
  File "calibre\srv\render_book.py", line 956, in render_for_viewer
  File "calibre\srv\render_book.py", line 934, in render
  File "calibre\srv\render_book.py", line 727, in process_exploded_book
  File "calibre\srv\render_book.py", line 270, in create_cover_page
  File "calibre\srv\render_book.py", line 223, in find_epub_cover
  File "calibre\ebooks\oeb\polish\cover.py", line 286, in find_cover_image_in_page
  File "src/lxml/xpath.pxi", line 415, in lxml.etree.XPath.__call__
  File "src/lxml/apihelpers.pxi", line 48, in lxml.etree._documentOrRaise
TypeError: Invalid input object: bytes

### Log output(When press 'Convert books')

calibre, version 7.17.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (【推しの子】 14)

Convert book 1 of 1 (【推しの子】 14)
DeDRM v10.0.9: Trying to decrypt 4pfd1f90.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Post-processing took 0.0 seconds
DeDRM v10.0.9: Finished after 2.5 seconds
Conversion options changed from defaults:
  output_profile: 'generic_eink'
  cover: 'C:\\Users\\WESKER~1\\AppData\\Local\\Temp\\calibre_5yvmw_q4\\qqm3_1zi.jpeg'
  read_metadata_from_opf: 'C:\\Users\\WESKER~1\\AppData\\Local\\Temp\\calibre_5yvmw_q4\\jiip04x5.opf'
  verbose: 2
Resolved conversion options
calibre version: 7.17.0
{'add_alt_text_to_img': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\WESKER~1\\AppData\\Local\\Temp\\calibre_5yvmw_q4\\qqm3_1zi.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_max_image_size': 'none',
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000016AD607B410>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000016AD6055B90>,
 'page_breaks_before': '/',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\WESKER~1\\AppData\\Local\\Temp\\calibre_5yvmw_q4\\jiip04x5.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v10.0.9: Trying to decrypt up4lk7ly.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Post-processing took 0.0 seconds
DeDRM v10.0.9: Finished after 2.5 seconds
InputFormatPlugin: EPUB Input running
on C:\Users\WESKER~1\AppData\Local\Temp\calibre_5yvmw_q4\foyr2v93.epub
Parsing all content...
Parsing OPS/navigation_standard.xhtml ...
Referenced file 'js/kobo.js' not found
The item OPS/images/08X10000000040002200_cover.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_dorigin_01_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_3_001_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_3_002_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_003_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_004_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_005_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_006_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_007_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_008_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_009_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_010_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_011_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_012_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_013_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_014_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_015_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_016_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_017_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_018_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_019_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_020_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_021_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_022_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_023_002.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_024_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_025_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_026_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_027_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_028_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_029_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_030_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_031_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_032_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_033_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_034_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_035_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_036_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_037_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_038_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_039_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_040_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_041_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_042_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_043_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_044_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_045_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_046_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_047_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_048_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_049_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_050_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_051_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_052_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_053_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_054_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_055_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_056_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_057_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_058_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_059_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_060_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_061_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_062_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_063_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_064_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_065_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_066_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_067_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_068_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_069_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_070_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_071_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_072_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_073_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_074_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_075_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_076_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_077_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_078_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_079_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_080_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_081_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_082_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_083_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_084_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_085_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_086_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_087_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_088_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_089_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_090_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_091_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_092_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_093_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_094_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_095_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_096_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_097_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_098_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_099_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_100_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_101_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_102_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_103_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_104_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_105_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_106_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_107_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_108_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_109_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_110_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_111_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_112_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_113_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_114_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_115_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_116_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_117_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_118_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_119_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_120_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_121_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_122_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_123_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_124_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_125_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_126_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_127_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_128_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_129_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_130_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_131_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_132_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_133_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_134_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_135_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_136_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_137_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_138_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_139_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_140_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_141_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_142_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_143_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_144_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_145_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_146_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_147_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_148_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_149_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_150_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_151_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_152_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_153_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_154_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_155_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_156_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_157_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_158_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_159_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_160_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_161_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_162_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_163_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_164_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_165_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_166_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_167_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_168_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_169_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_170_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_171_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_172_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_173_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_174_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_175_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_176_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_177_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_178_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_179_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_180_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_181_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_182_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_183_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_184_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_185_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_186_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_187_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_188_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_189_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_190_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_191_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_192_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_193_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_194_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_195_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_196_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_197_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_198_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_199_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_200_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_201_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_202_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_203_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_1_204_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08X10000000040002200_copyright.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_3_ill_01_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_3_ill_02_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_3_ill_03_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000040_3_ill_04_001.jpg is not a XML document. Removing it from spine.
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1139, in run
  File "calibre\ebooks\conversion\plumber.py", line 1349, in create_oebbook
  File "calibre\ebooks\oeb\reader.py", line 97, in __call__
  File "calibre\ebooks\oeb\reader.py", line 724, in _all_from_opf
  File "calibre\ebooks\oeb\reader.py", line 369, in _spine_from_opf
calibre.ebooks.oeb.base.OEBError: Spine is empty

**Comment by ElleKayEm** [comment]
Doesn't appear to be a DRM issue.  Let's see a debug log of adding the book.

**Comment by weskeryiu** [comment]
> Doesn't appear to be a DRM issue. Let's see a debug log of adding the book.

I just noticed that you mentioned in another post that I can extract the .epub file by renaming it to .zip. I was able to extract ‘推しの子’ and get the jpg inside. So the DRM is removed. The issue might be related to Calibre. Thanks for your help.”

**Comment by ElleKayEm** [comment]
I suspect some comics and manga like this may have non-standard formatting or at least formatting that calibre doesn't handle, yes.
