### ISSUE TITLE
Problem of quality when converting in PDF

### ISSUE THREAD

**Issue by stnnnts** [noDRM/DeDRM_tools#628]
### Question / bug report

Hello,
noDRM works very fine but with some recent files from Amazon that come from PDF files, when I used a conversion to PDF I got a bitmap conversion file of low quality. This is not the case of old Amazon files. I tried epubor and with modern Amazon files I got a nice vectorized pdf. Could you please help to get high quality pdf. 
Thanks in advanced.

### Which version of Calibre are you running?

7.17

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

Kindle Classic for mac

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Are they KFX format?  Use the "From KFX" toolbar action that's part of the KFX Input plugin instead of calibre's conversion.

**Comment by ElleKayEm** [comment]
Scroll down in this post and look under the "spoiler" for "From KFX": https://www.mobileread.com/forums/showthread.php?t=291290
