### ISSUE TITLE
DeDRM not possible for amazon books

### ISSUE THREAD

**Issue by hoodyhero** [noDRM/DeDRM_tools#632]
### Question / bug report

Until last week I had no problem with converting my books. Then I updated my Calibre to the latest Version (7.18). 
I installed all the plug-ins but it was not possible to DeDRM my books. I switched back to the old verion (7.16) with which I had no problems before but am still not able. 

### Which version of Calibre are you running?

7.16

### Which version of the DeDRM plugin are you running?

v.10.0.9

### If applicable, which version of the Kindle software are you running?

2.5.0

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Fehlerdiagnoseprotokoll
calibre 7.15  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.15  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.48] GUI main window shown
[0.55] main UI initialized...
[0.55] Hiding splash screen
[4.66] splash screen hidden
[4.66] Started up in 4.66 seconds with 2 books
Worker Launch took: 0.02 seconds
Job: 0 Buch 1 von 1 (B00GLVJ79M EBOK) konvertieren finished
Buch 1 von 1 (B00GLVJ79M EBOK) konvertieren
	DeDRM v10.0.9: Trying to decrypt 3uma2jf4.azw
	DeDRM v10.0.9: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.6 seconds
	searching for kinfoFiles in C:\Users\Anwender\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Anwender\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '513612208' and UserName 'Anwender'
	DeDRM v10.0.9: Found 1 new key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\Anwender\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
	k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
	  File "C:\Users\Anwender\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
	k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\Anwender\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
	k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  output_profile: 'cybook_opus'
	  verbose: 2
	  read_metadata_from_opf: 'C:\\Users\\Anwender\\AppData\\Local\\Temp\\calibre_110z8_2o\\3uzrh2mq.opf'
	Resolved conversion options
	calibre version: 7.15.0
	{'add_alt_text_to_img': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_max_image_size': 'none',
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002C3133ADD10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.CybookOpusOutput object at 0x000002C3134AD990>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': 'C:\\Users\\Anwender\\AppData\\Local\\Temp\\calibre_110z8_2o\\3uzrh2mq.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v10.0.9: Trying to decrypt 3uma2jf4.azw
	DeDRM v10.0.9: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\Anwender\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Anwender\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '513612208' and UserName 'Anwender'
	DeDRM v10.0.9: Found 1 new key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\Anwender\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
	k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
	  File "C:\Users\Anwender\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
	k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\Anwender\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
	k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on C:\Users\Anwender\AppData\Local\Temp\calibre_110z8_2o\3uma2jf4.azw
	Traceback (most recent call last):
	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 28, in convert
	  File "calibre\ebooks\mobi\reader\mobi6.py", line 90, in __init__
	calibre.ebooks.mobi.reader.mobi6.KFXError: Dies ist ein Amazon KFX-Buch. Es kann nicht verarbeitet werden. Weitere Informationen zum Umgang mit KFX-Büchern finden Sie unter https://www.mobileread.com/forums/showthread.php?t=283371.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 198, in _run_module_as_main
	  File "runpy.py", line 88, in _run_code
	  File "site.py", line 83, in <module>
	  File "site.py", line 78, in main
	  File "site.py", line 50, in run_entry_point
	  File "calibre\utils\ipc\worker.py", line 215, in main
	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "calibre\ebooks\conversion\plumber.py", line 1129, in run
	  File "calibre\customize\conversion.py", line 245, in __call__
	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 34, in convert
	  File "calibre\ebooks\mobi\reader\mobi6.py", line 90, in __init__
	calibre.ebooks.mobi.reader.mobi6.KFXError: Dies ist ein Amazon KFX-Buch. Es kann nicht verarbeitet werden. Weitere Informationen zum Umgang mit KFX-Büchern finden Sie unter https://www.mobileread.com/forums/showthread.php?t=283371.

**Comment by ElleKayEm** [comment]
Use Kindle for PC 2.4.0 (70904) aka 2.4.70904 and install the KFX Input plugin.

**Comment by hoodyhero** [comment]
how do i switch to this version?

**Comment by ElleKayEm** [comment]
Google to find it and see info under method 2 about blocking updates here: https://www.mobileread.com/forums/showthread.php?t=361503

**Comment by hoodyhero** [comment]
@ElleKayEm thank you it worked!
