### ISSUE TITLE
Fail to remove DRM from ADE 2.0/4.5

### ISSUE THREAD

**Issue by ffuentesm** [noDRM/DeDRM_tools#644]
### Question / bug report

I am trying to convert a book I got from ebookcentral.proquest but I keep getting errors. From what I can think of, the website is converting the file for ADE 4.5 while DeAVSM and DeDRM are using 2.0 version of ADE

DeACSM: 0.0.16
ADE 2.0.1

I also tried the ADE 4.5, and still have the DRM message on calibre.

If anyone wants to try to solve this problem of mine. Here is the ASCM file.
[Angelique.zip](https://github.com/user-attachments/files/17264596/Angelique.zip)

### Which version of Calibre are you running?

7.19

### Which version of the DeDRM plugin are you running?

10.0.3

**Comment by ElleKayEm** [comment]
Should work with DeDRM 10.0.9.

**Comment by ffuentesm** [comment]
THANK YOU!!!!!
10.0.9 WORKED!!!!!
