### ISSUE TITLE
Issue with DeDRM

### ISSUE THREAD

**Issue by arealestate** [noDRM/DeDRM_tools#646]
### Question / bug report

![2024-10-07 at 21 30 32@2x](https://github.com/user-attachments/assets/58437513-8435-4876-b7e7-bf55bc05eb4c)

1. I plugged Kindle Scribe into Macbook. 
2. Calibre detected Scribe. 
3. I saved all the Kindle files to computer.
4. When I try to open, the DRM is still active. 

### Which version of Calibre are you running?

7.19.0

### Which version of the DeDRM plugin are you running?

10.0.9

### If applicable, which version of the Kindle software are you running?

5.6.21

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Those copies cannot be decrypted.  Use download and transfer from the website.  Enter your Scribe's serial number into DeDRM's customization.

**Comment by arealestate** [comment]
Thank you

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
