### ISSUE TITLE
DeDRM_tools not working on kfx-zip files

### ISSUE THREAD

**Issue by darklinkc4** [noDRM/DeDRM_tools#649]
### Question / bug report

i think amazon is trying to stop us for removing drm.

### Which version of Calibre are you running?

7.19

### Which version of the DeDRM plugin are you running?

10.0.9

### If applicable, which version of the Kindle software are you running?

2.5.0 (70951)

**Comment by ElleKayEm** [comment]
Use Kindle for PC 2.4.0 (70904) aka 2.4.70904.  Any newer version has DRM that DeDRM can't handle.

**Comment by darklinkc4** [comment]
I got an older version of the Kindle for PC and that did it for me but I just wanted to tell you that so that you know but I do wish you a very good day and I hope someone is able to figure this out but thank you anyways.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
