### ISSUE TITLE
InvalidPlugin error

### ISSUE THREAD

**Issue by briannalnash** [noDRM/DeDRM_tools#652]
### Question / bug report

I'm getting an InvalidPlugin error that states:

InvalidPlugin: The plugin in '/Users/Downloads/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level__init__.py file

### Which version of Calibre are you running?

7.19

### Which version of the DeDRM plugin are you running?

v10.0.03

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
First, I recommend 10.0.9.  Then unzip the main file and load just DeDRM_plugin.zip.

https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by briannalnash** [comment]
That worked. Thanks so much!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
