### ISSUE TITLE
Kindle books suddenly stopped converting

### ISSUE THREAD

**Issue by KarellenX** [noDRM/DeDRM_tools#66]
Hello,

Today I purchased a Kindle book, and for some reason it won't decrypt when I import into Calibre.
I don't recall changing anything in Calibre in the last week.

Here is the debug log from Calibre... https://paste.kodi.tv/oxihatimox.kodi

Is there anything else you might need?

Thanks

= Edit =
I tried adding another book that I downloaded a few weeks ago, and it imported and decrypted ok.

**Comment by ElleKayEm** [comment]
Sounds like Kindle for PC may have updated.  See this post for details on how to get files you can decrypt: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by KarellenX** [comment]
Thanks @ElleKayEm 

I am still using v1.34.1 which is known to work, and has been working for me, and still does except with this particular book.

I am using the batch file method by @dnsb ... https://www.mobileread.com/forums/showpost.php?p=4169993&postcount=19
Which works with v1.34.1, but is broken for v1.35.... https://www.mobileread.com/forums/showthread.php?p=4206273#post4206273

Could it possibly be something else?

Thank you.

**Comment by ElleKayEm** [comment]
The file in your log is KFX format.  Delete it from Kindle for PC and calibre.  Restart Kindle for PC with DNSB's batch file and download it again.

**Comment by KarellenX** [comment]
Thanks. I'll try that when I return home.

**Comment by Iey4iej3** [comment]
If it works, then it might be better to close this issue.

**Comment by KarellenX** [comment]
Sure. I'll close the issue. 
I haven't tried downloading that book again, as I transferred it across from my Kindle instead.
I'll monitor it with my next purchase and see if it causes any problems. 
Anyway, sounds like the problem is at my end, but can't figure out what. You say the file is in kfx format, but I could see the file in my pc and it was definitely in AZW format, same as all the other books in the My Kindle Content folder.
Thanks :)

**Comment by ElleKayEm** [comment]
You can see that it is KFX in the log.  Kindle for PC uses the AZW extension for all of its main book files regardless of kfx, kf8/azw3, or other Amazon format.
