### ISSUE TITLE
Add a warning to the README about running DeDRM on the same machine as Kindle for PC if using it

### ISSUE THREAD

**Issue by C0rn3j** [noDRM/DeDRM_tools#663]
If one attempts KFX decrypt from another Calibre installation outside of the OS running Kindle for PC, it will fail catastrophically, as it relies on data from said machine.

Please add a warning to the README about this, I wasted hours.

**Comment by JsBergbau** [comment]
Still didn't work for me.
I used Memu Play Emulator and this Tutorial https://www.mobileread.com/forums/showthread.php?t=352278
For transfering the file I used sharedrop.io

**Comment by C0rn3j** [comment]
> Still didn't work for me.
> I used Memu Play Emulator 

This issue is about readme entry for Kindle for PC, not Android

**Comment by ElleKayEm** [comment]
> Calibre 7 gives an error that a temp file is already open
Use the alpha auto-release: https://github.com/noDRM/DeDRM_tools_autorelease/releases/tag/autorelease_3373d938749117989dfd0a42cc947bf338d3ffda

**Comment by noDRM** [comment]
Thanks for the report, I've added a note on the Kindle help page.
