### ISSUE TITLE
Unable to open PDF with anything else than Adobe Digital Editions

### ISSUE THREAD

**Issue by SpikedZen** [noDRM/DeDRM_tools#664]
### Question / bug report

File shows up as blank when opened on browser, and is still unreadable/unconvertable by other software.
![image](https://github.com/user-attachments/assets/0aade226-fd1e-4252-84b2-b7fc7a6c9354)

the file in question: 
[Matematiikan opetus ja oppimine - Unknown.pdf](https://github.com/user-attachments/files/17610729/Matematiikan.opetus.ja.oppimine.-.Unknown.pdf)

### Which version of Calibre are you running?

7.11

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Let's see a debug log: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by SpikedZen** [comment]
> Let's see a debug log: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

Hey, thanks for the reply, what ended up working was just converting the PDF into a PDF using Calibre itself, even though it showed the conversion process stuck at 1% for quite a long time. It's not a very clean conversion, but it might still suit my needs.

**Comment by ElleKayEm** [comment]
Alright, so not a DRM issue.  You can close the issue.
