### ISSUE TITLE
DRM fails on all adobe epub books from local library.  It worked fine before.

### ISSUE THREAD

**Issue by Calbooks** [noDRM/DeDRM_tools#677]
### Question / bug report

Debug report follows:

Microsoft Windows [Version 10.0.19045.5131]
(c) Microsoft Corporation. All rights reserved.

C:\Users\hdvid>calibre-debug -g
calibre 7.21  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 81.79119496855346 x 81.8865671641791
ApplicationPaletteChange event ignored
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[1.19] splash screen shown
[1.19] Initializing db...
[1.42] db initialized
[1.44] Constructing main UI...
[1.95] GUI main window shown
[2.00] main UI initialized...
[2.00] Hiding splash screen
[2.00] splash screen hidden
[2.00] Started up in 2.00 seconds with 11 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'?-PX\x06\xadI\xe9\xe4\x98\x93B\xa8C\xb6WJ\x19\x96\xd3N\x82\xb9\x9e\x02t\x10\x8b\xf2\xc1\xc7.', b'C:\\Users\\hdvid\\OneDrive\\Documents\\My Digital Editions\\Funny Story.epub']
DeDRM v10.0.9: Trying to decrypt Funny Story.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Funny Story.epub is a secure Adobe Adept ePub for UUID 1f2cb379-323d-4b01-8a98-24632c2fcdcb
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 565, in ePubDecrypt
  File "C:\Users\hdvid\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 293, in adeptkeys
  File "C:\Users\hdvid\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 273, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Funny Story to db in: 1.5
Added 1 books in 2.7 seconds

### Which version of Calibre are you running?

7.21

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
Paste log output here.
```Microsoft Windows [Version 10.0.19045.5131]
(c) Microsoft Corporation. All rights reserved.

C:\Users\hdvid>calibre-debug -g
calibre 7.21  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 81.79119496855346 x 81.8865671641791
ApplicationPaletteChange event ignored
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[1.19] splash screen shown
[1.19] Initializing db...
[1.42] db initialized
[1.44] Constructing main UI...
[1.95] GUI main window shown
[2.00] main UI initialized...
[2.00] Hiding splash screen
[2.00] splash screen hidden
[2.00] Started up in 2.00 seconds with 11 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'?-PX\x06\xadI\xe9\xe4\x98\x93B\xa8C\xb6WJ\x19\x96\xd3N\x82\xb9\x9e\x02t\x10\x8b\xf2\xc1\xc7.', b'C:\\Users\\hdvid\\OneDrive\\Documents\\My Digital Editions\\Funny Story.epub']
DeDRM v10.0.9: Trying to decrypt Funny Story.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Funny Story.epub is a secure Adobe Adept ePub for UUID 1f2cb379-323d-4b01-8a98-24632c2fcdcb
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 565, in ePubDecrypt
  File "C:\Users\hdvid\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 293, in adeptkeys
  File "C:\Users\hdvid\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 273, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Funny Story to db in: 1.5
Added 1 books in 2.7 seconds

**Comment by ElleKayEm** [comment]
Were the books downloaded with ADE on the same computer and user as calibre with DeDRM?

**Comment by Calbooks** [comment]
Yes. ADE was used to download all books on same computer. All books can be read in ADE. 

I also reinstalled Calibre and DRM plugin with same failing result.

**Comment by ElleKayEm** [comment]
Seems to be finding an incorrect key that it can't decrypt.  Something from a previous ADE install maybe?

**Comment by Calbooks** [comment]
OK. What can one do about it ?

**Comment by ElleKayEm** [comment]
You could try deauthorizing and reauthorizing ADE by deleting the registry key.  Scroll down to the Windows section here: https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html

Or maybe reinstalling ADE completely as well.

Less drastically, some people use the DeACSM (also called ACSM Input) plugin as an ADE replacement.  You can export your key from that and import it into DeDRM.  I haven't used this myself as my ADE setup works fine with calibre/DeDRM.

**Comment by Calbooks** [comment]
De-authorizing did not work. 

deACSM plug in anonymous mode did the trick!  It's superior to using ADE as it eliminates one step in the process.

Is this plug in updated at all ?

Thanks for your suggestion.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by Calbooks** [comment]
UPDATE:  deACSM plug in worked foe one day. It is once again unable to bring in and descript a book.
