### ISSUE TITLE
Not working with ADE 2.0

### ISSUE THREAD

**Issue by rolim-gabriel** [noDRM/DeDRM_tools#678]
Hi I have been trying to open in calibre Libby/Overdrive download books after they passed though my ADE 2.0, and the DeDRM has its key. However, all books so far I tried cannot open in calibre due to DRM.

Here is my Setup:
Windows 11
Calibre 7.21
DeDRM 10.0.3
ADE 2.0

Here is a log for an epub trying to convert and import:
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.21  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 7.21  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 157.8252427184466 x 158.5664739884393
[0.00] Starting up...
[0.02] Showing splash screen...
[1.30] splash screen shown
[1.30] Initializing db...
[1.38] db initialized
[1.38] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[2.06] GUI main window shown
[2.20] main UI initialized...
[2.20] Hiding splash screen
[2.20] splash screen hidden
[2.22] Started up in 2.22 seconds with 169 books
DeDRM v10.0.3: Trying to decrypt The Sugar King of Havana.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: The Sugar King of Havana.epub is a secure Adobe Adept ePub for UUID 44eaebee-4710-428a-bb20-2baf94625782
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xd21\xa4\x04+\x9a\xd3\xc5\xb5\x02\x9f\xa7\xd0<\xbf\xea\xb8\xb9c\x1cB?\xe2_\xac\xbe\x9c|\x95Q\xda\xae', b'C:\\Users\\G\\Documents\\My Digital Editions\\The Sugar King of Havana.epub']
Added The Sugar King of Havana to db in: 0.1
Added 1 books in 0.8 seconds

**Comment by ElleKayEm** [comment]
Try DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by rolim-gabriel** [comment]
It worked! Appreciate it!
