### ISSUE TITLE
B&N epub book wont DeDRM

### ISSUE THREAD

**Issue by bwaslo** [noDRM/DeDRM_tools#682]
### Question / bug report

I installed the plugin, removed the book, restarted Calibre, reloaded the book and tried to convert, but it is the same as without the plugin -- I get the DRM  no-can-do message.  It's a book that I bought today and just wanted to be able to convert and read it on a Kindle.  Guessing this isn't doable?

### Which version of Calibre are you running?

7.21

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
You need to get your B&N key.  The easiest way is from the Windows Nook app.  Unfortunately the Nook app is no longer available in the Microsoft store.  But it is possible to get the app and install it.  See this post: https://www.mobileread.com/forums/showpost.php?p=4414584&postcount=33

Once you have it installed and you're logged in, you will be able to go into the B&N part of DeDRM's customization, click the green plus sign, and choose to extract your key from the Windows app.

**Comment by bwaslo** [comment]
Thanks.  I'll look for the key .
I assume you mean in "ADE PassHash (B&N) ebooks", is the correct?

**Comment by ElleKayEm** [comment]
Yes.

**Comment by bwaslo** [comment]
Thanks.  Worked great.
Now I can buy ebooks again without buying them from Amazon.
Appreciate it.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
