### ISSUE TITLE
DRM Not Working on AZW3

### ISSUE THREAD

**Issue by Tamarissa** [noDRM/DeDRM_tools#686]
### Question / bug report

I am trying to convert a kindle book I purchased, but for some reason the DRM will not unlock. I am using the download & transfer via usb method. This is with an old Kindle (I have Fire & e-ink ones connected to my account, neither worked), definitely prior to 2024. I have not had any issues converting kindle files since the 10.0.3 update (that version did not work either; I had that version originally & then checked for a new version and installed it when this error happened). 10.0.9 obviously did not DeDRM the book either. I had no issues with the other kindle book I purchased and loaded into Calibre at the same time. Hopefully that covers all the basic starting questions... let me know if you need more info. Thanks!
(had to add the debug report as a text file... said it was too long/too many characters)

### Which version of Calibre are you running?

7.22

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

download & transfer via usb

### Log output

[tmp4u7k37i2.txt](https://github.com/user-attachments/files/17972140/tmp4u7k37i2.txt)

**Comment by ElleKayEm** [comment]
Make sure you choose an E-ink Kindle for the device when you download and have that Kindle's serial number entered into DeDRM's customization.

**Comment by Tamarissa** [comment]
As I stated, neither the e-ink nor the fire worked, and as the other kindle ebook successfully dedrm'd during the same session, same as all previous kindles since 10.0.3, the issue is also not related to a serial number.

**Comment by ElleKayEm** [comment]
The log shows otherwise.  Won't work for a Fire, but should work for an E-ink Kindle.  Try copy paste of the serial number from the website and click ok and apply on your way out of the dialog boxes.

**Comment by Tamarissa** [comment]
Okay, here is the log from my e-ink kindle download still not dedrm'ing.
[tmpzy8uufii.txt](https://github.com/user-attachments/files/17979414/tmpzy8uufii.txt)

**Comment by ElleKayEm** [comment]
Still not showing that you have any serial number entered in there.

**Comment by Tamarissa** [comment]
Well, here is the other book I did the exact same way as the one that won't work, and it worked just fine. It has been working since the day I got the kindle years and years and years ago.
[tmpnf_rtsi9.txt](https://github.com/user-attachments/files/17983679/tmpnf_rtsi9.txt)

**Comment by ElleKayEm** [comment]
That is a DRM-free book.

**Comment by Tamarissa** [comment]
I have no idea how the serial number disappeared out of Calibre... I couldn't even remember where the serial number goes; I had to look it up. I got it put back now though with no more issues. The file worked fine this time. Thank you for your help :)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
