### ISSUE TITLE
Cannot remove DRM from epub file from ADE

### ISSUE THREAD

**Issue by jellejans** [noDRM/DeDRM_tools#70]
### Question / bug report

Hi, 

Calibre is unable to remove the DRM from my file. File was generated with Leseratte10/acsm-calibre-plugin.
Working fine in Adobe Digital editions

### Which version of Calibre are you running?

5.41

### Which version of the DeDRM plugin are you running?

10.0.2

### Log output

DeDRM v10.0.2: Trying to decrypt blabla.epub
DeDRM v10.0.2: Verifying zip archive integrity
DeDRM v10.0.2: “blabla.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub

**Comment by ElleKayEm** [comment]
Well, that's odd.  That error usually means the book doesn't have the rights.xml file inside the epub which DeDRM needs in order to decrypt it.  The installation of ADE which you can read it in is authorized with the same Adobe ID you set up the ACSM plugin with?

**Comment by jellejans** [comment]
Yes same account on same computer. Is it possible that it's a higher DRM encryption ?

**Comment by jellejans** [comment]
Latest ADE version 4.5.11. The book is from Hewlett-Packard. hpepress.hpe.com. 
Is there a test build I can try that includes the latest source code ?

**Comment by jellejans** [comment]
Yes it's working with the beta build ! thnx
