### ISSUE TITLE
Problem installing DeDRM_tools, Pop!_OS 22.04

### ISSUE THREAD

**Issue by baslow** [noDRM/DeDRM_tools#75]
### Question / bug report

I have newly installed Calibre 5.42 and am trying to install DeDRM_tools, which I downloaded from github earlier today, first by downloading the ZIP file, then by installing `gh` and cloning. In each case, when I tried to install the plugin through Calibre I couldn't find an appropriate ZIP file to install. From the command line, doing a `find` at the top of each directory tree, the only ZIP files I find are: 
alfcrypto_src.zip and rebhack.zip.
Am I missing a step? Is there something I should be running to produce the zip file(s) I can load as Calibre plugins? The only installation instructions I can find suggest that this isn't the case but in that case I don't know what I am doing wrong.

### Which version of Calibre are you running?

5.42

### Which version of the DeDRM plugin are you running?

10.0.2 

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Download DeDRM_tools_10.0.2.zip from here:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2

Unzip that and load DeDRM_plugin.zip.

**Comment by baslow** [comment]
Thanks! That worked!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
