### ISSUE TITLE
How to use command line tools only?

### ISSUE THREAD

**Issue by codrutP** [noDRM/DeDRM_tools#77]
### Question / bug report

I don't want to use Calibre,  but I'm trying to convert my ebooks from Amazon to be readable on macOS as epubs in Apple Books. The platform is macOS arm64. I have installed Kindle 1.26.1 on macOS Monterey 12.3.1 M1 CPU and I was able partially to achieve something using only the command line. I usually avoid getting my ebooks from Amazon, but a few of them are only available via Kindle.

openssl 1.1.1o and Python 3.10.4 both arm64 versions are installed with pycryptodome 3.14.1 installed via pip3. 
These are the steps I've followed:

Before downloading the Kindle ebooks locally I have run:

```
chmod -w  ~/Library/Application\ Support/Kindle/updates
chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test
```

`cd <working directory>`

Get the files:
```
curl -LJO https://raw.githubusercontent.com/noDRM/DeDRM_tools/master/DeDRM_plugin/kindlekey.py
curl -LJO https://raw.githubusercontent.com/noDRM/DeDRM_tools/master/DeDRM_plugin/k4mobidedrm.py
curl -LJO https://raw.githubusercontent.com/noDRM/DeDRM_tools/master/DeDRM_plugin/kfxdedrm.py
curl -LJO https://raw.githubusercontent.com/apprenticeharper/DeDRM_tools/master/DeDRM_plugin/mobidedrm.py
curl -LJO https://raw.githubusercontent.com/apprenticeharper/DeDRM_tools/master/DeDRM_plugin/topazextract.py
curl -LJO https://raw.githubusercontent.com/apprenticeharper/DeDRM_tools/master/DeDRM_plugin/alfcrypto.py
curl -LJO https://raw.githubusercontent.com/apprenticeharper/DeDRM_tools/master/DeDRM_plugin/kgenpids.py
curl -LJO https://raw.githubusercontent.com/apprenticeharper/DeDRM_tools/master/DeDRM_plugin/androidkindlekey.py
curl -LJO https://raw.githubusercontent.com/apprenticeharper/DeDRM_tools/master/DeDRM_plugin/ion.py
```

Generate the Kindle Key file kindlekey1.k4i (one time only):

`python3 kindlekey.py`

and then I tried to decrypt:

```
python3 k4mobidedrm.py -k ./kindlekey1.k4i ~/Library/Application\ Support/Kindle/My\ Kindle\ Content/B08HQWYQ28_EBOK/B08HQWYQ28_EBOK.azw .
K4MobiDeDrm v6.0.
Copyright © 2008-2020 Apprentice Harper et al.
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Japanese From Zero! 1: Proven Methods to Learn Japanese with integrated Workbook and Online Support
Got DSN key from database ./kindlekey1.k4i
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
File is encoded with PID yhuRbOPKX3.
Decrypting. Please wait . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . done
Decryption succeeded after 29.4 seconds
Saved decrypted book B08HQWYQ28_EBOK_Japanese From Zero! 1  Proven Methods to Learn Japanese with integrated Workbook and Online Support_nodrm after 29.4 seconds
```

However the resulting mobi file is not readable, it looks like it's still enncryted. What am I missing?
It's possible this is due to the fact that the ebook contains Japanese characters?

### Which version of Calibre are you running?

0

### Which version of the DeDRM plugin are you running?

v10.0.2

### If applicable, which version of the Kindle software are you running?

1.26.1

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
There's a bug which misidentifies these as mobi files.  It's a pdf in an Amazon wrapper.  The Kindle Unpack plugin can be used to extract the pdf.  I don't know anything about doing that without calibre though.

**Comment by altitudedashboard** [comment]
You have been right. I used a different python script than the plugin:
https://github.com/kevinhendricks/KindleUnpack
But this unpacked it and indeed I could see the pdfs.
Thank you so much!

**Comment by ElleKayEm** [comment]
Ah, I thought there was a stand-alone, but I'm only familiar with the plugin myself.
