### ISSUE TITLE
Ubuntu 18.04, Calibre 5.32, DRM not removed.

### ISSUE THREAD

**Issue by algreen702021** [noDRM/DeDRM_tools#8]
Ubuntu 18.04, Calibre 5.32, DRM not removed.
Plugin DeDRM 10.0.2

.epub from italian public library. 

screenshot of Calibre response
`https://i.ibb.co/LPGVHDN/drm.png`

Any help please?
Thanks
Alex

**Comment by noDRM** [comment]
Please provide a debug log file so I can check why that happens. This screenshot doesn't tell much, other than the book still has DRM. 

https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by algreen702021** [comment]
here...LCPL error?

```
calibre Debug log
calibre 5.32  embedded-python: True is64bit: True
Linux-5.4.0-91-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-91-generic', '#102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: LCPL Input (0, 0, 5) && DeDRM (10, 0, 2) && KoboTouchExtended (3, 5, 4)
calibre 5.32  embedded-python: True is64bit: True
Linux-5.4.0-91-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-91-generic', '#102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: LCPL Input (0, 0, 5) && DeDRM (10, 0, 2) && KoboTouchExtended (3, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 100.55257731958763
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[1.13] main UI initialized...
[1.13] Hiding splash screen
Starting QuickView
DeDRM v10.0.2: Trying to decrypt L'Invincibile - Stanislaw Lem.epub
DeDRM v10.0.2: Verifying zip archive integrity
LCP: Found LCP-encrypted book 28df291b-8ca5-4588-8a37-b4731b30599c
LCP: Book is using lcp/profile-1.0 encryption
LCP: None of the passphrases could decrypt the book ...
LCP: Enter the correct passphrase in the DeDRM plugin settings, then try again.
LCP: The book distributor has given you the following passphrase hint: "Enter your passphrase"
LCP: You can visit the following webpage to reset your LCP passphrase: https://help.cantook.net
Looks like that didn't work:
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 899, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 294, in ePubDecrypt
    retval = lcpdedrm.decryptLCPbook(path_to_ebook, dedrmprefs['lcp_passphrases'], self)
  File "calibre_plugins.dedrm.lcpdedrm", line 385, in decryptLCPbook
    raise LCPError("No correct passphrase found")
calibre_plugins.dedrm.lcpdedrm.LCPError: No correct passphrase found
[25.02] splash screen hidden
[25.02] Started up in 25.02 seconds with 39 books
['zenity', '--modal', '--file-selection', '--title=Select books', '--separator=\n', '--attach=58720279', '--filename=/home/tess/Downloads/.fgdfg.gdfhjdhf*&^839', '--file-filter=Books | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf *.lcpl', '--file-filter=EPUB books | *.epub *.kepub', '--file-filter=Kindle books | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=PDF books | *.pdf *.azw4', '--file-filter=HTML books | *.htm *.html *.xhtm *.xhtml', '--file-filter=LIT books | *.lit', '--file-filter=Text books | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Comics | *.cbz *.cbr *.cbc', '--file-filter=Archives | *.zip *.rar', '--file-filter=Wordprocessor files | *.odt *.doc *.docx', '--file-filter=All files | *', '--multiple']
Added L’Invincibile to db in: 0.1
Added 1 books in 1.0 seconds
Worker Launch took: 0.01 seconds
```

**Comment by noDRM** [comment]
This means that that eBook isn't using the usual Adobe DRM, but instead the Readium / LCP DRM. 

The book is protected with a particular passphrase. That's the same passphrase you would enter when reading that eBook on a standalone eBook reader device. Usually, whatever source the book is from will provide the user (= you) with information about what the passphrase is. Unfortunately the "help page" given by the distributor - https://help.cantook.net as displayed in the log - doesn't seem to be that helpful, at least I can't find any hint on what the passphrase is supposed to be on there.

Once you figure out what the passphrase is - you should find that somewhere on the web page where you got the book from -  you can go into the plugin settings, then to "Readium LCP ebooks", then enter your passphrase in there. Then import the book again and it should work. 

If you cannot figure out what the passphrase is, can you post the link to that library so I can check if I can find something?

**Comment by algreen702021** [comment]
Sure...
[https://www.medialibrary.it/home/index.aspx]
Users are not provided with epub/pdf pwd.
After 30 days ebook is no more readable. In my case since first day I could not read the epub.
User can download DRM or Readium crypted ebook, in this case I choose the DRM but no way.
thanks

**Comment by algreen702021** [comment]
Library users own a Login/pwd but not is ebook pwd. I guess ebook just expire after 30 days. The ebook I have is not time expired. Since is not readable If you like I can send it to you.

**Comment by noDRM** [comment]
If users do not get access to the password, what is the legitimate way of reading the book? An app by the library?
My email is in my Github profile if you want to send me the DRMed book - I can take a look but it's unlikely that the book can be decrypted if you don't have the password.

**Comment by noDRM** [comment]
Take a look at the FAQs on that libraries' website: 

`Readium LCP è l’innovativa protezione che abbiamo di recente affiancato al DRM Adobe, di facilissimo utilizzo: gli ebook che sceglierai di prendere in prestito con questa protezione saranno riconosciuti automaticamente dalla app MLOL Ebook Reader, e non ti verrà richiesta la creazione di un ulteriore account. L'unico dettaglio che dovrai tenere a mente è la tua Passphrase personale: ti verrà richiesta in rari casi, e l'avrai comunque sempre a disposizione nel menu Account > I Miei Dati del sito MLOL.`

I don't speak Italian but according to Google Translate this means "The only detail you'll have to keep in mind is your personal Passphrase: it will be required in rare cases, and you'll always have it available in the Account > My Data menu of the MLOL website.". 

Can you get your passphrase by checking the "My Data" menu?

**Comment by algreen702021** [comment]
Yes there is a desktop reader called MlolEbookReader-1.0.3  (93mg)
It does not run in my ubuntu 18.04 (ask for glibc 2.28, I have 2.27). Anyway I think MLOLreaader it's too invasive, I do not like share my data with that MLOL guys.  ;)
"your personal Passphrase: it will be required in rare cases"  since 2001 nobody asked me for pwd to open ebooks, I'll check if something changed.  Another IMHO  interesting file is the .acsm to retrieve the ebook  through adobe digital (tried to install but wine does not support it in my PC)
please note that downloaded .acsm does not contain my mlol (www.medialibrary.it)  website user/pwd

```
<fulfillmentToken fulfillmentType="loan" auth="user" xmlns="http://ns.adobe.com/adept">
  <distributor>urn:uuid:dc4373cc-2c3c-45dc-b8e2-83ed3f4f7c3a</distributor>
  <operatorURL>http://acs4.cantook.net/fulfillment</operatorURL>
  <transaction>v1:en:61b5006e:edgt:1030:1613983374:905079019:896452132:37.162.57.114:7514735:v1</transaction>
  <expiration>2021-12-12T01:47:58+00:00</expiration>
  <resourceItemInfo>
    <resource>urn:uuid:3a42cc96-6ede-441e-82de-3aba426734fd</resource>
    <resourceItem>1</resourceItem>
    <metadata>
      <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">La fontana rotta</dc:title>
      <dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Thomas Belmonte</dc:creator>
      <dc:publisher xmlns:dc="http://purl.org/dc/elements/1.1/">EINAUDI</dc:publisher>
      <dc:identifier xmlns:dc="http://purl.org/dc/elements/1.1/"></dc:identifier>
      <dc:format xmlns:dc="http://purl.org/dc/elements/1.1/">application/epub+zip</dc:format>
      <dc:language xmlns:dc="http://purl.org/dc/elements/1.1/">it-IT</dc:language>
    </metadata>
    <licenseToken>
      <resource>urn:uuid:3a42cc96-6ede-441e-82de-3aba426734fd</resource>
      <permissions>
        <display>
          <until>2021-12-24T23:00:00+00:00</until>
        </display>
        <play>
          <until>2021-12-24T23:00:00+00:00</until>
        </play>
      </permissions>
    </licenseToken>
  </resourceItemInfo>
  <hmac>JEJYoK4zHlPTRX9Mp99COR/miKw=</hmac>
</fulfillmentToken>
```

please note that .ascm (still not retrieved epub)  and LCPL encrypted one concern different ebooks.

**Comment by noDRM** [comment]
The ACSM is something completely different. 
You can either use ADE or ADE-compatible software to download the book with Adobe DRM, then you won't need a password. Or, you download it in LCP(L) format, and then you will need a password, which is provided by the library. 

LCP is a fairly new DRM, they only began adding that to various libraries over the last 1-2 years or so, and it requires a user passphrase to read the book, even when reading it the legit way on an eBook reader. 

So you can either use the ACSM to download the book using ADE or the ACSM Input Plugin for Calibre, or you use the LCP file you've got, and follow the instructions in the FAQ to find out the passphrase you need for DRM removal.

**Comment by noDRM** [comment]
Closing this issue as there hasn't been any further responses. 

I'm assuming that once you get the correct LCP passphrase from the libraries' webpage, the DRM removal will work. Or just use the Adobe version and not the LCP version of the books.

If you still have issues with LCP DRM removal after adding the correct passphrase as mentioned in the quote above, feel free to re-open this issue.
