### ISSUE TITLE
Latest Calibre beta breaks DeDRM

### ISSUE THREAD

**Issue by muhlman** [noDRM/DeDRM_tools#84]
### Question / bug report

Running the latest Calibre beta of 5.99.9 on macOS 12.4 when trying to run anything through the plugin it hangs for a minute and then errors out with the error below, I am also unable to load the settings for the plugin. I started with the beta for ARM support, reverting to 5.43 or disabling DeDRM resolves the issue. 

I do realize I am running a beta so this may be an issue with Calibre as well but wanted to give a heads up here just in case some work may need to be done.

### Which version of Calibre are you running?

5.99.9

### Which version of the DeDRM plugin are you running?

10.0.2

### If applicable, which version of the Kindle software are you running?

NA

### Log output

```log
DeDRM v10.0.2: Trying to decrypt 66akn8bs.epub
DeDRM v10.0.2: Verifying zip archive integrity
WARNING: /Applications/calibre.app/Contents/MacOS/calibre-parallel is loading libcrypto in an unsafe way
```

**Comment by ElleKayEm** [comment]
Answered over here: https://github.com/noDRM/DeDRM_tools/discussions/54

**Comment by muhlman** [comment]
Thanks, totally missed that, hopefully the new version is released soon.
