### ISSUE TITLE
DeDRM on old pdb from Palm Ereader

### ISSUE THREAD

**Issue by vguard** [noDRM/DeDRM_tools#88]
### Question / bug report

Trying to open in Calibre old pdb files purchased 2000-2010 for the Palm.
Did it already in 2014 for a few books (with Calibre/DeDRM available at that time).
Installed latest Calibre and DeDRM on a new PC Windows. Configured key for epub.
When Adding the pdb file, nothing wrong happens, no messages. Book is from unknown author, and unreadable due to DRM.
The same file opens in ereader for Windows, with same values used for the key.
Went thru wiki, discussions, issues. Can't find what I did wrong, or missing.
Any suggestion?

### Which version of Calibre are you running?

5.43

### Which version of the DeDRM plugin are you running?

v10.0.2

### Log output

```log
Paste log output here.
```

**Comment by noDRM** [comment]
I wouldn't be surprised if that was the case. 

Can you post a full log? Maybe the error is visible in there and can be fixed. Just restart Calibre with `calibre-debug -g` or click "Preferences"-> Restart in debug mode, then try to add the book, then post the log file.

**Comment by vguard** [comment]
Thanks, noDRM: I tried restart in debug mode, but was unable to find a log file...

Thanks ElleKayEm, I installed as per your suggestion and now I have the file in MOBI on my Kindle

**Comment by ElleKayEm** [comment]
The log file automatically opens when you close calibre after opening in debug mode.
