### ISSUE TITLE
Can't import books from Kobo via Obok

### ISSUE THREAD

**Issue by Striker243** [noDRM/DeDRM_tools#89]
### Question / bug report

Hi fellow Obokusers,

I installed Calibre with DeDRM and Obok on my new PC (W10 21H2) and tried to import my Kobo library via the Kobo desktop app. The Kobo app syncs fine with my account but when trying to add the books via Obok in Calibre I get an error:

```
calibre, version 5.43.0
ERROR: Obok DeDRM v10.0.0: <p>Could not find Kobo Library
<p>Windows/Mac: do you have Kobo Desktop installed?
<p>Windows/Mac/Linux: In case you have an Kobo eInk device, connect the device.
```

I don't have a Kobo reader of any sort, but on my old computer I ran an older version in a VM and everything was fine (Calibre 4.23 / DeDRM 6.6.3 / Obok DeDRM 6.5.4).
I already reinstalled Calibre and the plugins but the error stays the same.

Hope someone can help me with this problem :)

### Which version of Calibre are you running?

5.43

### Which version of the DeDRM plugin are you running?

v10.0.2

### Log output

```
calibre Debug log
calibre 5.43 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (10, 0, 0)
calibre 5.43 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (10, 0, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.23899371069182 x 102.35820895522387
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.73] main UI initialized...
[0.73] Hiding splash screen
Starting QuickView
[5.84] splash screen hidden
[5.84] Started up in 5.84 seconds with 0 books
Running Obok DeDRM v10.0.0
DEBUG:    8.7 didn't find device
Obok v4.0.0
Copyright © 2012-2020 Physisticated et al.
DEBUG:    8.7 got kobodir 
```

**Comment by ElleKayEm** [comment]
Is your Kobo directory here?  C:\Users\%USERNAME%\AppData\Local\Kobo\Kobo Desktop Edition\kepub

Assume calibre with Obok is on the same machine and user.   And you have some books downloaded in Kobo Desktop?

**Comment by Striker243** [comment]
Sorry for the late answer.
Yes, my kobo directory is there and I have a book inside which I can view view Kobo Desktop.

**Comment by ElleKayEm** [comment]
I don't know.  That's my setup too and it's working.

**Comment by JohannesGaessler** [comment]
I had to set my kobo directory to `C:\Users\%USERNAME%\AppData\Local\Kobo\Kobo Desktop Edition`, then it worked.

**Comment by ElleKayEm** [comment]
I believe they are referring to setting it in Obok.

**Comment by JohannesGaessler** [comment]
Preferences -> Plugins -> Show only user installed plugins -> Obok DeDRM -> Kobo directory

**Comment by Striker243** [comment]
Thanks @JohannesGaessler, I set the Kobo directory as you explained and now it can import and decrypt my test ebook. This is amazing 😃

**Comment by Striker243** [comment]
Closed the issue as the import and decryption works after setting the Kobo directory as explained further up.
