### ISSUE TITLE
fix for DeDRM problem on macOS

### ISSUE THREAD

**Issue by ZolaLa9** [noDRM/DeDRM_tools#97]
Calibre's KovidGoyal offers the following fix for DeDRM on macOS related to system libcrypto vs the one bundled with calibre. 

He asked that the info be passed to @noDRM. 

KovidGoyal says: So the plugin should be changed to something like this:

`if hasattr(sys, 'frameworks_dir'):`
`   lib = glob.glob(os.path.join(sys.frameworks_dir, 'libcrypto*.dylib'))[0]`
`else:`
`   lib = find_library('crypto')`

Details here: https://www.mobileread.com/forums/showpost.php?p=4237911&postcount=74

Hope this helps. Thank you

**Comment by sidney** [comment]
This is a duplicate of issue #96. The fix is already in the repo. Here is a comment that says how to download an unreleased version that contains the fix https://github.com/noDRM/DeDRM_tools/issues/96#issuecomment-1182492150

**Comment by ZolaLa9** [comment]
> This is a duplicate of issue #96. The fix is already in the repo. Here is a comment that says how to download an unreleased version that contains the fix [#96 (comment)](https://github.com/noDRM/DeDRM_tools/issues/96#issuecomment-1182492150)

Awesome. I was just relaying KovidGoyal's post since he asked that the info be passed to noDRM. Didn't realize it was already in master. 

Closing issue ...
