### ISSUE TITLE
can't open azw4 file

### ISSUE THREAD

**Issue by yabo-boye** [noDRM/DeDRM_tools#99]
### Question / bug report

i tried to use the plugin under calibre to decode a azw4 file extracted from kindle macos. The file does get added to the library after sometime but no cover is shown, and when i try to open it the e-book viewer hangs. So I am supposing the the conversion did not work. 

This seems to be an older style kindle file from amazon, does anyone have a clue on how to fix that? 

### Which version of Calibre are you running?

5.44

### Which version of the DeDRM plugin are you running?

v10.0.2

### If applicable, which version of the Kindle software are you running?

1.25

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
AZW4 is a pdf in an Amazon wrapper.  Try extracting the pdf with the Kindle Unpack plugin.  Then use an actual pdf app to view it rather than calibre's ebook viewer.

**Comment by yabo-boye** [comment]
this worked perfectly, thank you so much!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
